- e2e/run-okd-tests.sh
- pkg/controller/che/che_controller.go
- pkg/controller/che/create.go
- pkg/controller/che/k8s_helpers.go
- pkg/deploy/deployment_keycloak.go
- pkg/util/util.go
This PR adds the following functionality to the operator:
1. Automatically get OpenShift baseURL and extract crt chain.
2. Add this crt to Keycloak container via secret and env variable that gets its values from secret's ca.crt
3. As a result, in Keycloak entrypoint maximum 3 certs are added:
* router crt (if `CHE_SELF__SIGNED__CERT` is not null )
* OpenShift baseURL crt (if `OPENSHIFT_SELF__SIGNED__CERT` is not null - this PR ntroduces it)
* crt mounted at `/var/run/secrets/kubernetes.io/serviceaccount/ca.crt`
In fact, just `/var/run/secrets/kubernetes.io/serviceaccount/ca.crt` should be enough, however, there are use cases when the crt mounted at /var/run/secrets/kubernetes.io/serviceaccount/ca.crt != crt that OpenShiftbaseURL endpoint actually uses. Router crt is added to trus store …
> Get crt of OpenShift baseURL for Keycloak

- build_deploy_local.sh
- deploy/crds/org_v1_che_cr.yaml
- pkg/apis/org/v1/che_types.go
- pkg/controller/che/che_controller.go
- pkg/controller/che/create.go
- pkg/controller/che/k8s_helpers.go
- pkg/controller/che/update.go
- pkg/deploy/defaults.go
- pkg/deploy/deployment_che.go
- pkg/deploy/route.go
- pkg/deploy/service.go
This PR:
1. Changes the way services and routes are created (slice of ports and names for services, target port for routes)
2. Makes mem request and limit for Che deployment configurable with  `serverMemoryRequest` and `serverMemoryLimit` spec.server fields, as well as updated Che deployment when those are updated in runtime (after installation).
> Smarter svc and route functions. Configurable mem settings

- pkg/deploy/che_configmap.go
- pkg/util/util.go
- pkg/util/util_test.go
This PR automatically adds value of `KUBERNETES_SERVICE_HOST` to non proxy hosts for a workspace master. This makes it possible not to worry about workspace master talking to OpenShift API when https proxy is defined.
> Auto fill non proxy with kube api url

- deploy/role.yaml
Hey, hope it's alright if I open a PR here! I understand this repo is still in a beta stage.
I've been playing around with the Che operator (really neat stuff by the way!) on a variety of different Kubes, and found that it was failing due to this error:
```
E0424 17:27:48.536731       1 reflector.go:134] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to list *v1beta1.Ingress: ingresses.extensions is forbidden: User "system:serviceaccount:che:che-operator" cannot list resource "ingresses" in API group "extensions" in the namespace "che"
E0424 17:27:49.547908       1 reflector.go:134] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to list *v1beta1.Ingress: ingresses.extensions is forbidden: User …
```
> Use extensions apiGroup instead of extensions/v1beta1

- deploy/crds/org_v1_che_cr.yaml
- pkg/apis/org/v1/che_types.go
- pkg/controller/che/che_controller.go
- pkg/deploy/che_configmap.go
- pkg/deploy/defaults.go
- pkg/deploy/deployment_che.go
- pkg/deploy/deployment_postgres.go
- pkg/deploy/exec_commands.go
This PR fixes some problems encountered during the upgrade of the Che operator to the `7.0.0-beta-5.0` upstream Che release:
- `kcadm.sh` configuration could not be created on the read-only `/opt/jboss` folder in the Keycloak container when running under an arbitrary UID on Openshift.
- Postgres deployment on Kubernetes should contain a security context that avoids it to run as `root`, just as it is done on upstream deployment method: https://github.com/eclipse/che/blob/master/deploy/kubernetes/helm/che/custom-charts/che-postgres/templates/deployment.yaml#L26
This was  tested on both Openshift 4.1 (POC 4.1.0-rc.5) and Minikube 1.1.0
> Fix Che operator to upgrade to 7.0.0-beta-5.0

- deploy/crds/org_v1_che_cr.yaml
- pkg/apis/org/v1/che_types.go
- pkg/controller/che/che_controller.go
- pkg/controller/che/che_controller_test.go
Ports https://github.com/eclipse/che/pull/13178 to the Che operator
Adds an option for the user to specify an additional cluster role for workspaces.
This allows the user to create/use workspaces that require further roles than are provided by default (such as sidecar that needs to list/edit ConfigMaps, creating a service, etc).
**Note:** Some of the changes are from VS Code running `gofmt` upon save. I couldn't find a way to disable it.
> Add field for workspace cluster role to operator

- cmd/manager/main.go
- deploy/cluster_role.yaml
- pkg/controller/che/che_controller.go
- pkg/controller/che/che_controller_test.go
- pkg/controller/che/create.go
- pkg/controller/che/update.go
- pkg/deploy/che_configmap.go
- pkg/deploy/deployment_che.go
- pkg/deploy/deployment_keycloak.go
- pkg/deploy/exec_commands.go
- pkg/deploy/oauthclient.go
- pkg/util/util.go
This PR introduces required changes to support the new Openshift v4 identity provider that will be provided by PR https://github.com/eclipse/che/pull/13554.
Along with the mentioned upstream Che PR, this work is the upstream fix for the following CRW issue: https://issues.jboss.org/browse/CRW-202.
In order to integrate this fix into downstream CRW, we should:
- Wait for the new openshift v4 provider fix (https://github.com/slaskawi/KEYCLOAK-10169-OpenShift4-User-Provider) to be integrated in the next RHSSO release 
- Do some work / testing to identify any required adjustments related to the use of RHSSO instead of upstream Keycloak.
> Support the new `openshift-v4` identity provider

- pkg/controller/che/create.go
- pkg/deploy/che_configmap.go
- pkg/deploy/defaults.go
This PR fixes the issue for the community Che operator (the bug was only in the community Eclipse Che operator).
This PR is flagged WIP since I build it against the `openshift-v4-support`. I'll update it as soon as PR https://github.com/eclipse/che-operator/pull/34 is merged.
> Fix issue #32 (Che install fails due to failed image pulls from registry.redhat.io)

- pkg/controller/che/che_controller.go
- pkg/util/util.go
This PR is to fix an unnecessary requirement of cluster roles for the `che-operator` running on Openshift 4 without Openshift OAuth.
> Fix unnecessary cluster perm requirement

- pkg/deploy/che_configmap.go
According to a recent discussion on IM, the obsolete `` environment variable should be replaced by a new one in the generated `custom` config map.
Here is  a quote of @skabashnyuk from the discussion:
> `che.workspace.agent.dev.inactive_stop_timeout_ms` is an old property
>> `#     The length of time that a user is idle with their workspace when the system will`
>> `#     suspend the workspace and then stopping it. Idleness is the`
>> `#     length of time that the user has not interacted with the workspace, meaning that`
>> `#     one of our agents has not received interaction. Leaving a browser window open`
>> `#     counts toward idleness.`
> > `che.limits.workspace.idle.timeout=-1`
>
> CHE_LIMITS_WORKSPACE_IDLE_TIMEOUT - is the correct one
> Change an obsolete env variable

- pkg/controller/che/che_controller.go
- pkg/controller/che/finalizer.go
- pkg/controller/che/get.go
- pkg/deploy/defaults.go
- pkg/deploy/deployment_keycloak.go
- pkg/deploy/exec_commands.go
- pkg/util/util.go
This PR updates the default tags for images the Che and keycloak images to the `7.0.0-RC-2.0`.
But it also fixes a number of bugs found in the last round of tests performed for the RC 2 update:
- The Che operator did crash badly on Openshift V4 when enabling Openshift OAuth without the related cluster permissions. Implemented graceful failure => commit 34a9c62
- When disabling Openshift AOuth, the command run inside the Keycloak POD was failing due to file system permissions => commit 46803d8
- When enabling Openshift OAuth (=> adding the OS API certificate for Keycloak), the Keycloac server was not automatically restarted, and Openshift OAuth was failing => commit 7cc07ca
- After a rolling update of the Keycloak deployment, the controller reference was lost on the Keycloak deployment, so …
> Update to the `7.0.0-RC-2.0` release after some last fixes

- deploy/operator.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1563282936/eclipse-che-preview-kubernetes.crd.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1563282936/eclipse-che-preview-kubernetes.v9.9.9-nightly.1563282936.clusterserviceversion.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/eclipse-che-preview-kubernetes.package.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1563282936/eclipse-che-preview-openshift.crd.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1563282936/eclipse-che-preview-openshift.v9.9.9-nightly.1563282936.clusterserviceversion.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/eclipse-che-preview-openshift.package.yaml
- olm/update-nightly-olm-files.sh
This PR:
- Manages the move of the Che operator docker image from the `eclipse-che` Quay.io organization to the `eclipse` organization.
- Fixes some remaining small bugs, in the `update-nightly-olm-files.sh` script, that were discovered when using it to update the docker image version
> Switch from `eclipse-che` org to `eclipse`

- pkg/apis/org/v1/che_types.go
- pkg/deploy/che_configmap.go
- pkg/deploy/defaults.go
This is to support https://github.com/che-incubator/chectl/issues/114 (implemented in https://github.com/che-incubator/chectl/pull/189).
> Add support for configuring devfile registry

- deploy/crds/org_v1_che_cr.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1563804656/eclipse-che-preview-kubernetes.crd.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1563804656/eclipse-che-preview-kubernetes.v9.9.9-nightly.1563804656.clusterserviceversion.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/eclipse-che-preview-kubernetes.package.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1563804657/eclipse-che-preview-openshift.crd.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1563804657/eclipse-che-preview-openshift.v9.9.9-nightly.1563804657.clusterserviceversion.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/eclipse-che-preview-openshift.package.yaml
This PR fixes a number of inconsistencies between OLM files (CSVs) and the main custom resource example used by  `CheCtl` to start workspaces, so that installing from CheCtl, and from the OperatorHub would result in the same settings being applied.
> Fix installation defaults for Chectl and OLM files.  

- pkg/controller/che/che_controller.go
- pkg/deploy/deployment_devfile_registry.go
This PR fixes the labels and names of the registry deployments, as well as the plugin registry probe path, to be consistent with the change made in the [corresponding Helm PR](https://github.com/eclipse/che/pull/13890) in commits:
https://github.com/eclipse/che/pull/13890/commits/bb0af81a7d5144d6d38190ba00bc3603480f56c5
and
https://github.com/eclipse/che/pull/13890/commits/56c9f831a184e6d9b528cdd34da8ab8e46f7b4cc
> Fix registry labels and probes

- deploy/keycloak_provision
This PR fixes issue https://github.com/eclipse/che/issues/13975:
Weird Login flow when Che is installed from the Operator with Openshift OAuth
> Add the `read-token` role by default for new users

- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/7.0.0-rc-4.0/eclipse-che-preview-kubernetes.crd.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/7.0.0-rc-4.0/eclipse-che-preview-kubernetes.v7.0.0-rc-4.0.clusterserviceversion.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/eclipse-che-preview-kubernetes.package.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/7.0.0-rc-4.0/eclipse-che-preview-openshift.crd.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/7.0.0-rc-4.0/eclipse-che-preview-openshift.v7.0.0-rc-4.0.clusterserviceversion.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/eclipse-che-preview-openshift.package.yaml
- pkg/deploy/defaults.go
This is required to keep the history of previous OLM package versions, as well as update the defaults in the operator Go code.
> Reintegrate the `7.0.0 rc 4.0` release branch to master

- pkg/apis/org/v1/che_types.go
- pkg/controller/che/che_controller.go
- pkg/deploy/defaults.go
- pkg/deploy/deployment_che.go
- pkg/deploy/deployment_keycloak.go
- pkg/deploy/deployment_postgres.go
Currently, the pull policy for the Che, Keycloak and Postgres containers is fixed and set at `IfNotPresent`.
Obviously this make the use of the `nightly` operator (and nightly Che components) useless.
This PR:
- adds fields in the `CheCluster` custom resource to drive the image pull policy of the various Che components (Che, Keycloak, etc...)
- If those fields are not set (or set to empty string) then a default pull policy is applied according to the following rule:
- use `Always` if the related docker image tag is `latest` or `nightly`
- use `IfNotPresent` in other cases
Please consider this PR as a followup of issue https://github.com/eclipse/che/issues/13780 that was part of endgame plan.
> Allow configuring pull policy (with `Always` by default for nightlies)

- olm/check-yq.sh
- olm/prepare-community-operators-update.sh
- olm/push-olm-files-to-quay.sh
- olm/release-olm-files.sh
- olm/update-nightly-olm-files.sh
- release-operator-code.sh
This PR fixes a number of bugs / enhancements found when applying the release scripts during the `7.0.0-rc-4.0` release of Che Operator.
In brief this PR:
- Fixes a bug introduced by a weird copy paste in a script shell file
- Fixes a typo in a regular expression during the `nightly` version replacement in the OLM files releasing script
- Complete PR-preparing script in order to :
- name the branch with the release number instead of a timestamp
- clone from the `che-incubator` fork
- fetch from the upstream (`operator-framework`) repo
- create the branch starting from the upstream master
- commit the changes
- push the branch to the fork if user creds are provided.
> Fix release scripts after first use

- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1564753341/eclipse-che-preview-kubernetes.crd.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1564753341/eclipse-che-preview-kubernetes.v9.9.9-nightly.1564753341.clusterserviceversion.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/eclipse-che-preview-kubernetes.package.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1564753341/eclipse-che-preview-openshift.crd.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1564753341/eclipse-che-preview-openshift.v9.9.9-nightly.1564753341.clusterserviceversion.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/eclipse-che-preview-openshift.package.yaml
It provides new documentation for Kubernetes (not openshift)
as current doc for Kubernetes was more for OpenShift
Maybe I don't need to provide new nightly package for openshift then ? 
You can try new doc by pasting CRD content into https://operatorhub.io/preview
There are lot of changes but in fact only description field was updated.
Change-Id: Id493209bda96df42e16ebdf4f50e5b0d4f75d690
Signed-off-by: Florent Benoit <fbenoit@redhat.com>
> docs(kubernetes): Update documentation (description field)

- deploy/crds/org_v1_che_cr.yaml
I noticed that the `che-plugin-registry` was failing with an ImagePullBackOff error for me. I looked into it and saw that the `pluginRegistryImage` had a slight typo in it. This PR fixes it.
> Fix typo in CheCluster CR yaml

- pkg/deploy/deployment_che.go
This PR aims at fixing an inconsistency in Che deployment readiness and liveness probes that used to prevent correct Che deployment on RHPDS Openshift 4 clusters.
The root cause was that Che start was quite long, and liveness probe was expired before the expiration of the readiness probe, which cause the Che POD to be constantly restarted.
@slemeur Did you have created an issue for your initial problem ? We could link it to the PR, and add it for triage to include it in 7.0.0 if you think it is critical.
> Inconsistent probes prevented deploying on RHPDS

- deploy/cluster_role.yaml
- olm/README.md
- olm/docker-run.sh
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/csv-config.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1564753341/eclipse-che-preview-kubernetes.v9.9.9-nightly.1564753341.clusterserviceversion.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1567437268/eclipse-che-preview-kubernetes.crd.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1567437268/eclipse-che-preview-kubernetes.v9.9.9-nightly.1567437268.clusterserviceversion.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1567437268/eclipse-che-preview-kubernetes.v9.9.9-nightly.1567437268.clusterserviceversion.yaml.diff
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/eclipse-che-preview-kubernetes.package.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/csv-config.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1567437269/eclipse-che-preview-openshift.crd.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1567437269/eclipse-che-preview-openshift.v9.9.9-nightly.1567437269.clusterserviceversion.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1567437269/eclipse-che-preview-openshift.v9.9.9-nightly.1567437269.clusterserviceversion.yaml.diff
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/eclipse-che-preview-openshift.package.yaml
- olm/release-olm-files.sh
- olm/update-nightly-olm-files.sh
- pkg/apis/org/v1/che_types.go
- pkg/controller/che/che_controller.go
- pkg/controller/che/che_controller_test.go
- pkg/controller/che/status.go
This PR fixes the issue https://github.com/eclipse/che/issues/14013 : it prevents using Openshift OAuth if no real user exists in the OpenShift cluster.  
It also provides a way to show an error reason when the Che Operator cannot start a Che server, as well as a detailed explanation, and possibly a link to point to the related documentation.
The result in the OperatorHub shown in the following image:
> Don't allow installing Che with Openshift Oauth when no OAuth user exist

- pkg/controller/che/create.go
- pkg/deploy/exec_commands.go
This PR is the implementation of issue https://github.com/eclipse/che/issues/14012
When the Openshift OAuth is configured, it configure the Keycloak server so that it directly uses the OpenShift login page when connecting to Che.
> Directly login through the `openshift` provider when OpenShift OAut is enabled

- deploy/keycloak_provision
The addition of the `read-token` permission by default, that had been cherry-picked recently from the master branch, had the `che` realm hard-coded, instead of using a configurable realm according to the custom resource Che flavor. And it prevents the CRW server to start correctly.
This PR is fixing this and should unblock issue https://github.com/redhat-developer/codeready-workspaces-deprecated/pull/44#issuecomment-529869654
> Don't hard-code the `che` realm !

- pkg/deploy/che_configmap.go
Che server will require different ingress annotations and a new config variable to support single-host mode. This brings the operator inline with what is going to be required once https://github.com/eclipse/che/pull/14134 is merged.
> Bring che operator in line with the latest changes coming to Che server to support single-host mode.

- Dockerfile
- README.md
- deploy/oauth_provision
- pkg/controller/che/che_controller.go
- pkg/controller/che/create.go
- pkg/controller/che/exec.go
- pkg/deploy/deployment_keycloak.go
- pkg/deploy/exec_commands.go
This PR allows enabling the Keycloak Token Exchange feature in the Che setup when the OpenShift OAuth integration is enabled.
This allows grabbing a Che authentication token from the OpenShift token of a user, making it easier to integrate Che with third-party tools running in a overall OpenShift environment.
https://github.com/eclipse/che/issues/14390
https://github.com/eclipse/che-docs/pull/826
> Enable token exchange

- pkg/deploy/che_configmap.go
Removed some defaults to be closer to upstream configuration
- CHE_PREDEFINED_STACKS_RELOAD__ON__START - not used in Che 7
- CHE_WORKSPACE_AUTO_START - wrong parameter, has to be CHE_WORKSPACE_AUTO__START, upstream default value - ```true```
- CHE_INFRA_KUBERNETES_WORKSPACE__UNRECOVERABLE__EVENTS - upstream value ```FailedMount,FailedScheduling,MountVolume.SetUp failed,Failed to pull image,FailedCreate```
- CHE_LIMITS_WORKSPACE_IDLE_TIMEOUT - upstream value ```1800000```
- CHE_INFRA_KUBERNETES_SERVICE__ACCOUNT__NAME - Not changed since it has ```NULL``` value in upstream. To remove it we need to investigate if it's safe to do or not.
Refer to https://github.com/eclipse/che/issues/14614
> Sync default properties with upstream

- pkg/apis/org/v1/che_types.go
- pkg/controller/che/che_controller.go
- pkg/deploy/che_configmap.go
- pkg/deploy/defaults.go
- pkg/deploy/defaults_test.go
- pkg/deploy/deployment_keycloak.go
- pkg/deploy/deployment_postgres.go
- pkg/deploy/extra_images.go
- release-operator-code.sh
This PR addresses https://github.com/eclipse/che/issues/14734
- Add 3 CR fields, `airGapMode`, `airGapContainerRegistryHostname`, `airGapContainerRegistryRepository`
- If `airGapMode` is true, all of the images will be pulled from their airgapped repository location instead of `registry.redhat.io`, `docker.io`, etc.
We are thinking that this doesn't need a docs PR as this will mostly be covered in https://github.com/eclipse/che/issues/13886
> Add airgap mode

- pkg/deploy/deployment_che.go
Since we're swithing to JGroups 4,  need to update property name to avoid ugly warnings in logs.
> Fix property name to avoid JGroups4 warnings

- pkg/controller/che/che_controller.go
In history it was not appended, when flavor was codeready (backwards compatibility). I think this is not needed anymore.
Should fix https://issues.jboss.org/browse/CRW-430
Signed-off-by: Radim Hopp <rhopp@redhat.com>
> Append `/v3` to pluginRegistryURL in all cases.

- pkg/controller/che/che_controller.go
- pkg/deploy/defaults.go
Che issue - https://github.com/eclipse/che/issues/14809
ConsoleLink functionality works just fine
Verified against crc:
`./run server:start -a operator -p crc -b console-openshift-console.apps-crc.testing -n crw-link --che-operator-image=quay.io/ibuziuk/che-operator:che-14809-new --che-operator-cr-yaml=crw.yaml`
crw.yaml:
```
apiVersion: org.eclipse.che/v1
kind: CheCluster 
metadata:
name: eclipse-che
spec:
server:
cheImage: 'quay.io/crw/server-rhel8'
cheImageTag: '2.0-377'
devfileRegistryImage: 'quay.io/crw/devfileregistry-rhel8:2.0-159'
pluginRegistryImage: 'quay.io/crw/pluginregistry-rhel8:2.0-203'
cheFlavor: 'codeready'
selfSignedCert: true
tlsSupport: true
customCheProperties:
CHE_WORKSPACE_SIDECAR_IMAGE__PULL__POLICY: 'Always'
CHE_DOCKER_ALWAYS__PULL__IMAGE: 'true' …
```
> che #14809 Enable CodeReady branding on the ConsoleLink elements created by the che operator with 'codeready' flavor

- pkg/controller/che/che_controller.go
- pkg/deploy/registry_configmap.go
This PR adds the `CHE_DEVFILE_HTTPS_ENDPOINT` variable when configuring the registries in airgap mode.  It uses the public-facing route of the devfile registry, and places it in the `devfile-registry` config map, and redeploys a new version of the registry based on changes to the route.
Enables https://github.com/eclipse/che/issues/14880
> Set CHE_DEVFILE_REGISTRY_URL to allow airgap operation

- pkg/deploy/che_configmap.go
- pkg/deploy/che_configmap_test.go
The env var `CHE_INFRA_KUBERNETES_BOOTSTRAPPER_BINARY__URL` is from Che 6 and no longer needed/useful.
See: https://github.com/eclipse/che/issues/14633
> Remove deprecated BootstrapperBinaryUrl from configmaps

- olm/prepare-community-operators-update.sh
Now the `community-operators` GH repo has been changed to support a nested OLM package structure instead of a flattened one.
The ` olm/prepare-community-operators-update.sh` script, that automatically prepares `community-operators` PRs for Eclipse Che operator releases should be updated accordingly.
This is the purpose of this PR
> Support the new nested structure in `community-operators`

- pkg/deploy/che_configmap.go
- pkg/deploy/defaults.go
- pkg/deploy/extra_images.go
- release-operator-code.sh
This PR is a fix in the operator for the issue https://issues.jboss.org/browse/CRW-468
It enables correctly getting CRW-specific images for the 3 containers whose docker images is specified in the upstream Che server `che.properties` file.
> Correctly manage `che.properties`-located docker images for CRW (jira crw-468) 

- deploy/crds/org_v1_che_cr.yaml
- pkg/deploy/che_configmap.go
The default is still the current namespace if there is no oauth in the infra
With Openshift OAuth, the namespace is now `<username>-che` or
`<username>-codeready` depending on the che flavor.
Note that this change amounts to no workspace breakage even in case of upgrade from previous versions because of the workspace namespace resolution logic implemented in the che server.
The new logic (implemented in https://github.com/eclipse/che/pull/14828) does the following when determining a workspace namespace during workspace **start** (not creation):
1. Take the legacy `che.infra.kubernetes.namespace` or `che.infra.openshift.project` property (defaulting to `<workspaceid>` placeholder)
1. See if a namespace with the above determined name exists, use it for deploying the workspace if it does
1. …
> Support for the new way of specifying the workspace namespace in Che.

- pkg/controller/che/create.go
- pkg/deploy/defaults.go
This PR is a fix for https://issues.jboss.org/browse/CRW-455.
It should avoid the requirement of manually cleaning the CustomResource when upgrading CRW from 1.2 to 2.0
> Provide easier migration from 1.2 to 2.0

- pkg/deploy/defaults.go
This is a fixup of PR #119 (Provide easier migration from 1.2 to 2.0).
There was a wrong docker image references, that finally prevented the 1.2 Che server docker to e automatically updated to the 2.0 one.
> fix: This is a fixup of PR #119 (Provide easier migration from 1.2 to 2.0)

- pkg/deploy/defaults.go
Set new default tag of `quay.io/crw/pluginregistry-rhel8:2.0-217` image.
> Update pluginregistry-rhel8 tag.

- pkg/deploy/defaults.go
Need to update defaults to point to release of Eclipse Che 7.3.2 and new bits on https://quay.io/organization/crw
(it could also require further update of pluginregistry image as well)
> Update to 7.3.2

- pkg/deploy/che_configmap.go
- pkg/util/util.go
JGroups is using labels to detect pods where replication should be enabled (to avoid pinging all containers in deployment). Since CRW using different value for `app` and `component`  labels, they should be set via environment variable.
> Add environment variable for JGroups labels

- pkg/deploy/che_configmap.go
- pkg/util/util.go
This PR cherry-picks the PR #126: Add environment variable for JGroups labels
This is import to allow JGroups labels to correctly reference the CRW Che server PODS. in the case of CRW, the labels for Che server pods use the `codeready` flavor, instead of `che`, and it has to be propagated to the Che server through this new environment variable.
If it is not the case, restarting the CRW Che server with running workspaces may lead to inconsistencies.
> Cherry-pick PR #126 (Add environment variable for JGroups labels)

- pkg/deploy/che_configmap.go
Align JGroups labels property name with original one in `KUBE_PING`
(see https://github.com/jgroups-extras/jgroups-kubernetes/blob/master/src/main/java/org/jgroups/protocols/kubernetes/KUBE_PING.java#L81) 
So possible naming confusions may be avoided in future.
Issue to `KUBE_PING` upstream to align their documentation: https://github.com/jgroups-extras/jgroups-kubernetes/issues/79
> Align JGroups labels property name with original one in KUBE_PING

- pkg/util/util.go
This PR fixes the bug https://issues.jboss.org/browse/CRW-514 that was introduced by PR https://github.com/eclipse/che-operator/pull/126
In order to fix this bug, it mainly orders map keys in alphabetic order when converting a map to string
> Fix the JIRA issue CRW-514 (constant Che server rollout) 

- build_deploy_local.sh
It doesn't make sense to run `build_deploy_local.sh` without namespace parameter. This PR checks the parameter and `exit 1` with meaningful message if it's missing.
> check script parameter

- deploy/crds/org_v1_che_crd.yaml
- olm/README.md
This PR fixes issue https://github.com/eclipse/che/issues/15396 :
*Invalid CRD openAPIV3Schema on OpenShift 3.11*
It seems that the last CRD generation that was applied on this repository was probably done with an `operator-sdk` > 0.10.0.
It added a `type: object` field  (and description) at the root of the `spec.validation.openAPIV3Schema` field.
This makes the CRD invalid for Kubernetes 1.11 (on which Openshift 3.11 is based), since this version of Kubernetes had the following bug: https://github.com/kubernetes/kubernetes/issues/65293.
This PR removes the added optional fields that made the CRD invalid for OS 3.11
> Fix a CRD change that is incompatible with OS 3.11

- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/7.6.0/eclipse-che-preview-kubernetes.crd.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/7.6.0/eclipse-che-preview-kubernetes.v7.6.0.clusterserviceversion.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/7.6.0/eclipse-che-preview-kubernetes.v7.6.0.clusterserviceversion.yaml.diff
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/eclipse-che-preview-kubernetes.package.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/7.6.0/eclipse-che-preview-openshift.crd.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/7.6.0/eclipse-che-preview-openshift.v7.6.0.clusterserviceversion.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/7.6.0/eclipse-che-preview-openshift.v7.6.0.clusterserviceversion.yaml.diff
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/eclipse-che-preview-openshift.package.yaml
- pkg/deploy/defaults.go
Issue #15504
Release 7.6.0 version of the che-operator
- update defaults.go files 
- release 7.6.0 OLM files
OLM packages on the Quay.io preview applications:
- https://quay.io/application/eclipse-che-operator-kubernetes/eclipse-che-preview-kubernetes
- https://quay.io/application/eclipse-che-operator-openshift/eclipse-che-preview-openshift
> che #15504 Release 7.6.0 version of the che-operator

- deploy/crds/org_v1_che_cr.yaml
- deploy/crds/org_v1_che_crd.yaml
- pkg/apis/org/v1/che_types.go
- pkg/controller/che/che_controller.go
- pkg/deploy/deployment_che.go
Add new boolean property `gitSelfSignedCert`that applies environment variables that contain SSL certificate and git host written from `che-git-self-signed-cert` config map.
The same logic is applied for the helm deployment: https://github.com/eclipse/che/pull/15218
fixes https://github.com/eclipse/che/issues/15285
Docs PR: https://github.com/eclipse/che-docs/pull/1001
> Apply git self-signed SSL certs

- deploy/crds/org_v1_che_crd.yaml
The `gitSelfSignedCert` item has incorrect description format. This fixes the formatting and prevents an error: 
```
✖ Create CRD checlusters.org.eclipse.che
→                           ^
Waiting 5 seconds for the new Kubernetes resources to get flushed
Create deployment che-operator in namespace che
Create Che Cluster eclipse-che in namespace che
Eclipse Che logs will be available in '/home/tolusha/projects/chectl/bin/logs'
YAMLException: can not read a block mapping entry; a multiline key may not be an implicit key at line 395, column 23:
type: boolean
^
at generateError (~/projects/chectl/node_modules/js-yaml/lib/js-yaml/loader.js:167:10)
at throwError (~/projects/chectl/node_modules/js-yaml/lib/js-yaml/loader.js:173:9)
at readBlockMapping …
```
> Add missing separating spaces to che_crd.yaml

- pkg/deploy/che_service.go
- pkg/deploy/che_service_test.go
- pkg/deploy/defaults.go
Signed-off-by: Tom George <tg82490@gmail.com>
setting `Spec.Server.CheDebug` to `true` will make `che-server` listen on port 8000 for debugging purposes.  However, the `che-host` service does not currently expose port 8000.  This change adds a debug port at port 8000 for the `che-host` service, so you can `port-forward` it and attach a debugger from your laptop into a running che instance.  
If `Spec.Server.CheDebug` is set to `true` it will add a route to port 8000 inside the pod, and will remove it from the service when `CheDebug` is set to false.
I needed this as part of https://github.com/eclipse/che/issues/15709.  It may be that you don't want users to attach a debugger to the che-operator, but it is useful when you are working on che.
> Add the debug port to che-host svc to expose the debug port

- RELEASE.md
- make-release.sh
- olm/release-olm-files.sh
- Adds `make-release.sh` to automate most of the steps.
- Adds `RELEASE.md`
`make-release.sh` hasn't been tested yet since it requires a real release to perform.
> Add RELEASE.md

- RELEASE.md
- make-release.sh
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/7.8.0/eclipse-che-preview-kubernetes.crd.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/7.8.0/eclipse-che-preview-kubernetes.v7.8.0.clusterserviceversion.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/7.8.0/eclipse-che-preview-kubernetes.v7.8.0.clusterserviceversion.yaml.diff
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/eclipse-che-preview-kubernetes.package.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/7.8.0/eclipse-che-preview-openshift.crd.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/7.8.0/eclipse-che-preview-openshift.v7.8.0.clusterserviceversion.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/7.8.0/eclipse-che-preview-openshift.v7.8.0.clusterserviceversion.yaml.diff
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/eclipse-che-preview-openshift.package.yaml
- olm/prepare-community-operators-update.sh
- olm/release-olm-files.sh
- olm/testUpdate.sh
- pkg/deploy/che_configmap.go
- pkg/deploy/defaults.go
- pkg/deploy/extra_images.go
- release-operator-code.sh
> Release 7.8.0

- pkg/deploy/deployment_che.go
https://github.com/eclipse/che/issues/14976
> Disable readiness probe in case of debug Eclipse Che Server

- cmd/manager/main.go
- deploy/operator-local.yaml
- deploy/operator.yaml
- make-release.sh
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1581975496/eclipse-che-preview-kubernetes.crd.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1581975496/eclipse-che-preview-kubernetes.v9.9.9-nightly.1581975496.clusterserviceversion.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1581975496/eclipse-che-preview-kubernetes.v9.9.9-nightly.1581975496.clusterserviceversion.yaml.diff
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/eclipse-che-preview-kubernetes.package.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1581975497/eclipse-che-preview-openshift.crd.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1581975497/eclipse-che-preview-openshift.v9.9.9-nightly.1581975497.clusterserviceversion.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1581975497/eclipse-che-preview-openshift.v9.9.9-nightly.1581975497.clusterserviceversion.yaml.diff
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/eclipse-che-preview-openshift.package.yaml
- pkg/controller/che/che_controller.go
- pkg/deploy/che_configmap.go
- pkg/deploy/defaults.go
- pkg/deploy/defaults_test.go
- pkg/deploy/deployment_che.go
- pkg/deploy/deployment_keycloak.go
- pkg/deploy/deployment_postgres.go
- pkg/deploy/extra_images.go
- release-operator-code.sh
Remove image refs in `defaults.go` and replace by env vars
https://github.com/eclipse/che/issues/15874
> feat: Remove image refs in `defaults.go` and replace by env vars

- .gitignore
- .vscode/launch.json
Improve debug configuration. Add debug binary to .gitignore. In the latest vscode-go extension we have an issue with cutting strings to 64 characters, and cut array by length. `maxStructFields` - means evaluate all nested fields in the structure. `followPointers` - usefull when we have an structure with nested structures in the fields.
> Improve debug configuration. Add debug binary to .gitignore

- deploy/crds/org_v1_che_cr.yaml
- deploy/crds/org_v1_che_crd.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1582643605/eclipse-che-preview-kubernetes.crd.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1582643605/eclipse-che-preview-kubernetes.crd.yaml.diff
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1582643605/eclipse-che-preview-kubernetes.v9.9.9-nightly.1582643605.clusterserviceversion.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1582643605/eclipse-che-preview-kubernetes.v9.9.9-nightly.1582643605.clusterserviceversion.yaml.diff
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/eclipse-che-preview-kubernetes.package.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1582643605/eclipse-che-preview-openshift.crd.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1582643605/eclipse-che-preview-openshift.crd.yaml.diff
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1582643605/eclipse-che-preview-openshift.v9.9.9-nightly.1582643605.clusterserviceversion.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1582643605/eclipse-che-preview-openshift.v9.9.9-nightly.1582643605.clusterserviceversion.yaml.diff
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/eclipse-che-preview-openshift.package.yaml
- pkg/apis/org/v1/che_types.go
- pkg/apis/org/v1/zz_generated.openapi.go
- pkg/controller/che/che_controller.go
- pkg/controller/che/get.go
- pkg/deploy/deployment_che.go
Add a property to configure propagation of custom public certificate from config-map to environment variable
https://github.com/eclipse/che/issues/16002
> Propagate custom public certificate to env variable

- .ci/cico_operator_prcheck.sh
- .ci/util/ci_common.sh
Some times running e2e in ci.centos with minishift fail because the Github Token is not set. With this PR should be solved
Reference issue: 
> https://github.com/eclipse/che/issues/16214
> Add github token for minishift installation

- deploy/crds/org_v1_che_cr.yaml
Backports https://github.com/eclipse/che-operator/pull/186 to 7.9.x
> Set tlsSupport to true by default

- pkg/deploy/ingress.go
Uses default `che-tls` secret name for securing Che ingresses if TLS is turned on and `tlsSecretName` is not provided in Che CR.
https://github.com/eclipse/che/issues/16280
> Fallback to default Che secret name if none is given in case of turned on tls

- pkg/deploy/ingress.go
Remove redundant parsing of string to boolean and second tls flag.
Follow up to: https://github.com/eclipse/che-operator/pull/191
> Refactor setting of tlsSecretName in NewIngress

- pkg/deploy/che_configmap.go
Sets default Che TLS secret name in Che config map if Che CR doesn't specify it when TLS is turned on.
https://github.com/eclipse/che/issues/16280
> Set default Che secret name in Che server config map if tlsSecretName is not specified in CR

- local-debug.sh
- pkg/controller/che/che_controller.go
- pkg/controller/che/che_controller_test.go
- pkg/controller/che/create.go
- pkg/controller/che/exec.go
- pkg/controller/che/k8s_helpers.go
- pkg/deploy/che_configmap.go
- pkg/deploy/defaults.go
- pkg/deploy/deployment_che.go
- pkg/deploy/deployment_postgres.go
https://github.com/eclipse/che/issues/13420
CR resource should contains:
```yaml
spec:
server:
customCheProperties:
CHE_MULTIUSER: "false"
```
> Support single-user mode

- build/Dockerfile
https://github.com/eclipse/che/issues/16206
For some tasks `operator-sdk` requires `Dockerfile` to be located into `build` directory otherwise it fails with the error:
`FATA[0000] must run command in project root dir: project structure requires build/Dockerfile `
I don't want to remove it from the root of the project since it is used by some build jobs.
Duplication it is enough for operator-sdk
> Duplicate Dockerfile in the build directory

- deploy/crds/org_v1_che_crd.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1584615281/eclipse-che-preview-kubernetes.crd.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1584615281/eclipse-che-preview-kubernetes.crd.yaml.diff
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1584615281/eclipse-che-preview-kubernetes.v9.9.9-nightly.1584615281.clusterserviceversion.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1584615281/eclipse-che-preview-kubernetes.v9.9.9-nightly.1584615281.clusterserviceversion.yaml.diff
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/eclipse-che-preview-kubernetes.package.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1584615281/eclipse-che-preview-openshift.crd.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1584615281/eclipse-che-preview-openshift.crd.yaml.diff
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1584615281/eclipse-che-preview-openshift.v9.9.9-nightly.1584615281.clusterserviceversion.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1584615281/eclipse-che-preview-openshift.v9.9.9-nightly.1584615281.clusterserviceversion.yaml.diff
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/eclipse-che-preview-openshift.package.yaml
- pkg/apis/org/v1/che_types.go
- pkg/apis/org/v1/zz_generated.openapi.go
- pkg/controller/che/che_controller.go
- pkg/controller/che/create.go
- pkg/controller/che/exec.go
- pkg/controller/che/update.go
- pkg/deploy/che_configmap.go
- pkg/deploy/defaults.go
- pkg/deploy/deployment_che.go
- pkg/deploy/deployment_keycloak.go
- pkg/deploy/deployment_postgres.go
- pkg/deploy/exec_commands.go
- pkg/deploy/secret.go
- pkg/util/k8s_helpers.go
- pkg/util/k8s_helpers_test.go
- pkg/util/util.go
- pkg/util/util_test.go
PR allows to use secret to store user's credentials. 
New fields are introduced:
```
spec.database.chePostgresSecret
spec.auth.identityProviderPostgresSecret
spec.auth.identityProviderSecret
```
There are several scenarios:
1. If user set credentials in a CR then the behavior won't be changed. 
2. To use secret with custom user/password user should create it first and then set the secret name in a corresponding field of the CR. `operator` will mount corresponding env variables using the given secret.
```bash
kubectl create secret generic <SECRET> --from-literal=username=<USERNAME> --from-literal=password=<PASSWORD> -n <CHE_NAMESPACE>
```
3. If use won't set neither credentials no secrets in the CR then operator will create secret by himself with default usernames and auto-generated …
> Store credentials into secrets instead of plain text of CheCluster CR fields

- .ci/cico_olm_prcheck.sh
- .ci/start-minikube.sh
In order to install minikube in ci.centos.org needed to install with vm-driver=none flag.
> Add minikube installation without vm-driver

- pkg/controller/che/che_controller.go
- pkg/controller/che/update.go
https://github.com/eclipse/che/issues/15345
> Add error status if operator hasn't got permission to count users.

- olm/addDigests.sh
- olm/buildDigestMap.sh
- olm/dockerContainerExtract.sh
Related to CRW-579 and CRW-563
*  if podman not installed fall back to docker; slighly noisier console ouptu while pulling images (long operation) nboldt@redhat.com
* do not use dockerContainerExtract.sh -- not required; support a quieter console mode; if podman not installed fall back to docker; allow secondary level of skopeo inspection (for Brew images not yet in RHCC or any other additional parsing rules) nboldt@redhat.com
* implement overwriting csv with generated digests and related images; add tags as comments into sources too; support a quieter console mode; if podman not installed fall back to docker 
Change-Id: I7ea9db2baab32ed03cef71aa7aac6c80a95d6850
> CRW-563 improve generation of digests from tags in registries and operator

- pkg/deploy/che_configmap.go
This fixes issue https://github.com/eclipse/che/issues/16574 that also affects CRW 2.1 (which is why this PR is done against the `7.9.x` branch).
This could be included in `CRW 2.1.0`, if the issue is considered as blocking the release, or kept for a `2.1.1`.
I tested that on the staging-based CRW 2.1 QE cluster on this Che server: https://console-openshift-console.apps.test-ocp43.codereadyqe.com/k8s/ns/david-test/clusterserviceversions/crwoperator.v2.1.0/org.eclipse.che~v1~CheCluster/codeready-workspaces/
Fixed operator docker image: `quay.io/dfestal/che-operator:fix-che-16574` 
In terms of potential respins, this only impacts the `che-operator` and `operator-metadata` and the catalog itself.
> Take `WorkspaceNamespaceDefault` into account even when OpenShift OAuth is enabled

- pkg/controller/che/che_controller.go
- pkg/controller/che/che_cr_validator.go
This PR adds simple validation of Che CR at the beginning of reconcile loop. If an mistake found in the CR, corresponding message will be printed into Operator logs and it will wait till CR is changed.
For now it checks very basic things, like ingress domain for Kubernetes, but could be easily extended for other cases.
I ran into issue that Che operator may fall into infinite reconcile loop if some fields of CR are misconfigured. It wasn't fault of reconcile logic as it is just required to have some fields specified.
So this is additional changes in terms of https://github.com/eclipse/che-operator/pull/220
> Add Che CR validator

- .ci/operator_code_check.sh
This PR contain new features to ensure all Pull request contains all necessary changes:
Cases:
-  if developer modify `*che_types.go` file then should exist modifications in `deploy/crds/*`.
-  if are changes in `deploy/*` folder then should exist new nightly files in PR. 
More info in reference issue:
> https://github.com/eclipse/che/issues/16077
> Add extra checks to operator to check generated code and nightly files

- pkg/deploy/defaults.go
More effective usage of heap && Make Che server JAVA_OPTS suitable for Java 8 and Java 11
For 1 GB container 842.94M  instead of 455.50M
```
docker run -m 1GB openjdk:8u242-jre-slim java \
-XX:MaxRAMPercentage=85.0 \
-XshowSettings:vm \
-version
VM settings:
Max. Heap Size (Estimated): 842.94M
Ergonomics Machine Class: server
Using VM: OpenJDK 64-Bit Server VM
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-b08)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)
```
```
docker run -m 1GB openjdk:8u242-jre-slim java \
-XX:MaxRAMFraction=2 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true …
```
> More effective usage of heap && Make Che server JAVA_OPTS suitable for Java 8 and Java 11

- deploy/crds/org_v1_che_cr.yaml
- deploy/operator-local.yaml
- deploy/operator.yaml
- make-release.sh
- pkg/deploy/defaults_test.go
- release-operator-code.sh
> Include operator image in the release process

- olm/olm.sh
Update 0.12.0 olm version to 0.14.1. Testing che-operator updates seems is more stable in 0.14.1 than 0.12.0.
Also OLM catalogsource CRD is deprecated: https://raw.githubusercontent.com/operator-framework/operator-marketplace/master/deploy/upstream/02_catalogsourceconfig.crd.yaml
Related issue:https://github.com/eclipse/che/issues/16738
> Update OLM installation version

- deploy/crds/org_v1_che_cr.yaml
This PR removes default value for Keycloak admin user password which makes operator generate random password for Keycloak on each Che deploy and store it in secret.
> Make default Keycloak password generated

- .vscode/launch.json
- deploy/operator-local.yaml
- deploy/operator.yaml
- go.mod
- local-debug.sh
- make-release.sh
- pkg/controller/che/che_controller.go
- pkg/controller/che/che_controller_test.go
- pkg/controller/che/create.go
- pkg/controller/che/status.go
- pkg/deploy/che_configmap.go
- pkg/deploy/defaults.go
- pkg/deploy/defaults_test.go
- pkg/deploy/deployment_che.go
- pkg/deploy/deployment_keycloak.go
- pkg/deploy/exec_commands.go
- pkg/deploy/job.go
- pkg/deploy/labels.go
- pkg/deploy/registry_configmap.go
- pkg/deploy/role.go
- pkg/deploy/rolebinding.go
- pkg/deploy/route.go
- pkg/deploy/secret.go
- pkg/deploy/service.go
- pkg/deploy/service_account.go
- replace-images-tags.sh
https://github.com/eclipse/che/issues/16868
Move some defaults to env var
> Move some defaults to env

- Dockerfile
I have added support for ppc64le architecture with reference to the [PR](https://github.com/eclipse/che-operator/pull/203) merged for s390x architecture.
> Added support for ppc64le

- .ci/cico_updates_minikube.sh
- .ci/util/ci_common.sh
- .ci/util/devfile-test.yaml
- olm/testCatalogSource.sh
- olm/testUpdate.sh
This PR add scripts to check updates on minikube platform. This script have next tasks:
- Install minikube
- Install eclipse che previous stable version and then update to last stable version
- Create workspace using chectl 
Ref. issue: https://github.com/eclipse/che/issues/15814
> Add scripts to create a job in CENTOS CI to test operator updates

- pkg/deploy/deployment.go
- pkg/deploy/deployment_keycloak.go
- templates/keycloak_provision
- templates/oauth_provision
We have `serverTrustStoreConfigMapName` parameter in Che CR, which hold name of config map with custom CA certificates. They are added into Che server trust store only, but to fully support trusting to custom CA certificates we need to propagate them into Keycloak and user workspaces.
This PR adds functionality which propagates custom CA certificates into Keycloak trust store.
https://issues.redhat.com/browse/CRW-336
1. Create a configmap which has CA certificates only.
This could be done via `kubectl apply -f <yaml>` where the config map definition could be like:
```yaml
--- 
apiVersion: v1
kind: ConfigMap
metadata: 
name: ca-certs
data: 
demoCA.crt: |
-----BEGIN CERTIFICATE----- …
```
> Propagate custom CA certificate into Keycloak trust store

- pkg/deploy/deployment_keycloak.go
https://github.com/eclipse/che/issues/17058
It is enough to import `/etc/pki/ca-trust/extracted/java/cacerts`
```bash
sh-4.4$ ls -l ./etc/java/java-11-openjdk/java-11-openjdk-11.0.7.10-1.el8_1.x86_64/lib/security/cacerts
lrwxrwxrwx. 1 root root 21 Apr 15 12:51 ./etc/java/java-11-openjdk/java-11-openjdk-11.0.7.10-1.el8_1.x86_64/lib/security/cacerts -> /etc/pki/java/cacerts
sh-4.4$ ls -l ./etc/pki/java/cacerts
lrwxrwxrwx. 1 root root 40 Oct 18  2019 ./etc/pki/java/cacerts -> /etc/pki/ca-trust/extracted/java/cacerts
sh-4.4$ ls -l ./etc/pki/ca-trust/extracted/java/cacerts
-r--r--r--. 1 root root 161905 Mar  2 17:42 ./etc/pki/ca-trust/extracted/java/cacerts
```
> Fix certs paths to import into truststore

- olm/release-olm-files.sh
- olm/update-nightly-olm-files.sh
- replace-images-tags.sh
https://github.com/eclipse/che/issues/17048
> Some release improvements

- deploy/crds/org_v1_che_cr.yaml
- deploy/crds/org_v1_che_crd.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1594019197/eclipse-che-preview-kubernetes.crd.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1594019197/eclipse-che-preview-kubernetes.crd.yaml.diff
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1594019197/eclipse-che-preview-kubernetes.v9.9.9-nightly.1594019197.clusterserviceversion.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1594019197/eclipse-che-preview-kubernetes.v9.9.9-nightly.1594019197.clusterserviceversion.yaml.diff
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/eclipse-che-preview-kubernetes.package.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1594019198/eclipse-che-preview-openshift.crd.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1594019198/eclipse-che-preview-openshift.crd.yaml.diff
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1594019198/eclipse-che-preview-openshift.v9.9.9-nightly.1594019198.clusterserviceversion.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1594019198/eclipse-che-preview-openshift.v9.9.9-nightly.1594019198.clusterserviceversion.yaml.diff
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/eclipse-che-preview-openshift.package.yaml
- pkg/apis/org/v1/che_types.go
https://github.com/eclipse/che/issues/17186
CHE_METRICS_ENABLED will be set to true by default in the cm
list of metrics available in the Prometheus format - https://gist.github.com/ibuziuk/1859a134bb7575cecd7f7669100a14f4
> che #17186 Enabling metrics by default

- .ci/cico_updates_openshift.sh
- .ci/openshift-ci/Dockerfile
- .ci/util/ci_common.sh
This PR includes:
- Bash script to run Che Operator Updates against OCP 4.X cluster installed in AWS
- DockerFile with dependencies used by PROW to build job container
Ref. Issue: https://github.com/eclipse/che/issues/17073
> Add scripts to run che updates against OCP4.X

- .ci/cico_olm_prcheck.sh
- .ci/cico_operator_prcheck.sh
- .ci/util/ci_common.sh
- .gitignore
- .vscode/launch.json
- deploy/crds/org_v1_che_cr.yaml
- deploy/operator-local.yaml
- deploy/operator.yaml
- make-release.sh
- olm/addDigests.sh
- olm/buildDigestMap.sh
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1594133420/eclipse-che-preview-kubernetes.crd.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1594133420/eclipse-che-preview-kubernetes.v9.9.9-nightly.1594133420.clusterserviceversion.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1594133420/eclipse-che-preview-kubernetes.v9.9.9-nightly.1594133420.clusterserviceversion.yaml.diff
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/eclipse-che-preview-kubernetes.package.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1594133421/eclipse-che-preview-openshift.crd.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1594133421/eclipse-che-preview-openshift.v9.9.9-nightly.1594133421.clusterserviceversion.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1594133421/eclipse-che-preview-openshift.v9.9.9-nightly.1594133421.clusterserviceversion.yaml.diff
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/eclipse-che-preview-openshift.package.yaml
- olm/images.sh
- olm/release-olm-files.sh
- olm/update-nightly-olm-files.sh
- pkg/deploy/defaults.go
- pkg/deploy/defaults_test.go
- pkg/deploy/deployment_registry.go
- pkg/util/util.go
- replace-images-tags.sh
https://github.com/eclipse/che/issues/14993
https://github.com/eclipse/che/issues/16815
> feature: Use image digest in csv

- .vscode/launch.json
- deploy/cluster_role.yaml
- deploy/operator-local.yaml
- deploy/operator.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1594209360/eclipse-che-preview-kubernetes.crd.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1594209360/eclipse-che-preview-kubernetes.v9.9.9-nightly.1594209360.clusterserviceversion.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1594209360/eclipse-che-preview-kubernetes.v9.9.9-nightly.1594209360.clusterserviceversion.yaml.diff
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/eclipse-che-preview-kubernetes.package.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1594209361/eclipse-che-preview-openshift.crd.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1594209361/eclipse-che-preview-openshift.v9.9.9-nightly.1594209361.clusterserviceversion.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1594209361/eclipse-che-preview-openshift.v9.9.9-nightly.1594209361.clusterserviceversion.yaml.diff
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/eclipse-che-preview-openshift.package.yaml
- pkg/controller/che/che_controller.go
- pkg/controller/che/create.go
- pkg/controller/che/proxy.go
- pkg/deploy/che_configmap.go
- pkg/deploy/che_configmap_test.go
- pkg/deploy/configmap.go
- pkg/deploy/configmap_cert.go
- pkg/deploy/data_types.go
- pkg/deploy/defaults.go
- pkg/deploy/deployment_che.go
- pkg/deploy/deployment_keycloak.go
- pkg/deploy/proxy.go
- pkg/deploy/proxy_test.go
- pkg/deploy/registry_configmap.go
- pkg/deploy/secret.go
- pkg/deploy/tls.go
- pkg/util/util.go
- pkg/util/util_test.go
https://issues.redhat.com/browse/CRW-732
- reuses openshift cluster wide proxy configuration https://docs.openshift.com/container-platform/4.3/networking/enable-cluster-wide-proxy.html
Tested on OpenShift with proxy configured. Workspace was successfully created and project was cloned.
> Respect openshift cluster wide proxy

- .ci/cico_updates_minikube.sh
- .ci/cico_updates_minishift.sh
- .ci/util/che-cert-generation.sh
- .ci/util/ci_common.sh
- olm/olm.sh
This PR add the ability to use tls support in CI.
Reference issue: https://github.com/eclipse/che/issues/17337
> Add tls support to che operator updates

- make-release.sh
- olm/prepare-community-operators-update.sh
- olm/release-olm-files.sh
- olm/update-nightly-olm-files.sh
- Do not push nightly OLM files during release in 7.15.x branch
- Do not create PR to master branch during release
- Remove certain `-x` flags
> Do not push nightly OLM files during release in 7.15.x branch

- pkg/deploy/proxy.go
- pkg/deploy/proxy_test.go
To be able to work with authenticated proxies, special Java authenticator should be used. Besides that, using custom authenticator requires special properties to be set.
```
jdk.http.auth.proxying.disabledSchemes=
jdk.http.auth.tunneling.disabledSchemes=
```
More info:
https://www.oracle.com/java/technologies/javase/8u111-relnotes.html
https://stackoverflow.com/questions/41806422/java-web-start-unable-to-tunnel-through-proxy-since-java-8-update-111
(yes java 11 requires it too)
> Add property to allow use authenticator for proxies;

- .ci/cico_updates_minishift.sh
- .ci/util/ci_common.sh
Copy minishift bin to `/usr/local/bin` instead of `/usr/bin`.
> Fix minishift install

- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1594657565/eclipse-che-preview-kubernetes.crd.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1594657565/eclipse-che-preview-kubernetes.v9.9.9-nightly.1594657565.clusterserviceversion.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1594657565/eclipse-che-preview-kubernetes.v9.9.9-nightly.1594657565.clusterserviceversion.yaml.diff
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/eclipse-che-preview-kubernetes.package.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1594657566/eclipse-che-preview-openshift.crd.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1594657566/eclipse-che-preview-openshift.v9.9.9-nightly.1594657566.clusterserviceversion.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1594657566/eclipse-che-preview-openshift.v9.9.9-nightly.1594657566.clusterserviceversion.yaml.diff
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/eclipse-che-preview-openshift.package.yaml
operatorframework.io/cluster-monitoring: "true" is a pre-requirement for openshift cluster monitoring - https://github.com/openshift/enhancements/blob/master/enhancements/olm/olm-managed-operator-metrics.md#namespace-requirements
Once the label is applied it will be possible to opt in for the cluster monitoring:
> crw-927 Adding 'operatorframework.io/cluster-monitoring: true' label to the OpenShift nightly csv files

- pkg/deploy/che_configmap.go
https://github.com/eclipse/che/issues/17407
It simply adds truststore config map name to che config map.
Che server will use this config map name to mount certificates into workspace pod containers
> Add truststore config map name to che config map

- RELEASE.md
- make-release.sh
- olm/prepare-community-operators-update.sh
- remove interactive bits that couldn't run on a non-interactive CI
- also remove GIT_USER and GIT_PASSWORD and use ssh links instead to push community operator updates
> Fix release scripts for CI integration

- pkg/deploy/che_configmap.go
https://github.com/eclipse/che/issues/17407
Updates the property name in che configmap:
`CHE_TRUSTSTORE__CONFIGMAP__NAME` -> `CHE_TRUSTED__CA__BUNDLES__CONFIGMAP`
> Update the configmap property name

- pkg/controller/che/che_controller.go
- pkg/controller/che/get.go
- pkg/deploy/deployment_keycloak.go
- pkg/deploy/exec_commands.go
- templates/keycloak_provision
https://github.com/eclipse/che/issues/17274
Allows to use external PostgreSQL
> Allow to use external PostgreSQL

- .ci/cico_minishift_nightly.sh
This PR create a new ci script which will deploy Eclipse che nightly in minishift platform and verify if workspaces start successfully...
Red. issue: https://github.com/eclipse/che/issues/17514
> Create Eclipse Che nightly deployment in minishift

- pkg/deploy/tls.go
https://github.com/eclipse/che/issues/17556
> Ignore the error if test route already exists

- pkg/deploy/tls.go
https://github.com/eclipse/che/issues/17556
https://github.com/eclipse/che-operator/pull/383
Ignore errors if `test` route already exists.
> [Backport] Ignore the error if test route already exists (#383)

- olm/digestExcludeList
https://github.com/eclipse/che/issues/17580
Exclude image `quay.io/eclipse/che-sidecar-workspace-data-sync:latest` from digest usage
> Add quay.io/eclipse/che-sidecar-workspace-data-sync:latest to digestExcludeList

- .ci/openshift-ci/.dockerignore
- .ci/openshift-ci/Dockerfile.catalog
In openshift CI we are not able to build the catalog source from `olm/eclipse-che-preview-openshift/Dockerfile`. I create a new catalog dockerfile in .ci/openshift-ci/ folder where Openshift CI will be able to read...
> Add catalog source dockerfile openshfit ci

- pkg/deploy/defaults.go
- pkg/util/util.go
https://issues.redhat.com/browse/CRW-1131
Using architecture dependent images.
> Use architecture dependent images

- deploy/crds/org_v1_che_cr.yaml
https://github.com/eclipse/che/issues/17488
Set the default value for openShiftoAuth to true
> Set the default value for openShiftoAuth to true

- .ci/cico_minishift_nightly.sh
- .ci/cico_olm_minikube.sh
- .ci/cico_olm_openshift.sh
- .ci/cico_updates_minishift.sh
- .ci/util/ci_common.sh
- deploy/crds/org_v1_che_crd.yaml
- deploy/operator-local.yaml
- deploy/operator.yaml
- deploy/role.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1597060381/eclipse-che-preview-kubernetes.crd.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1597060381/eclipse-che-preview-kubernetes.crd.yaml.diff
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1597060381/eclipse-che-preview-kubernetes.v9.9.9-nightly.1597060381.clusterserviceversion.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1597060381/eclipse-che-preview-kubernetes.v9.9.9-nightly.1597060381.clusterserviceversion.yaml.diff
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/eclipse-che-preview-kubernetes.package.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1597060382/eclipse-che-preview-openshift.crd.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1597060382/eclipse-che-preview-openshift.crd.yaml.diff
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1597060382/eclipse-che-preview-openshift.v9.9.9-nightly.1597060382.clusterserviceversion.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1597060382/eclipse-che-preview-openshift.v9.9.9-nightly.1597060382.clusterserviceversion.yaml.diff
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/eclipse-che-preview-openshift.package.yaml
- olm/testCatalogSource.sh
- pkg/apis/org/v1/che_types.go
- pkg/apis/org/v1/zz_generated.openapi.go
- pkg/controller/che/che_controller.go
- pkg/deploy/data_types.go
- pkg/deploy/devfile_registry.go
- pkg/deploy/ingress.go
- pkg/deploy/plugin_registry.go
- pkg/deploy/route.go
- pkg/deploy/tls.go
- Allows to customize cheHost + secure cheHost ingress/route with a certificate
https://issues.redhat.com/browse/CRW-1022
https://github.com/eclipse/che-docs/pull/1442
> Allow to customize cheHost

- pkg/deploy/tls.go
We use test route to retrieve cluster CA certificate. However, in case of using proxy, it might change the packets routing which may cause retrieving another certificate. This PR aims to fix such problem. (This behaviour was faced with a proxy with SSL Bump enabled. Then we get proxy certificate instead of Openshift one).
https://github.com/eclipse/che/issues/17552
> Do not use proxy settings for test route while getting cluster CA certificate

- pkg/controller/che/che_controller.go
- pkg/controller/che/create.go
- pkg/controller/che/proxy.go
- pkg/deploy/che_configmap.go
- pkg/deploy/che_configmap_test.go
- pkg/deploy/che_service_test.go
- pkg/deploy/configmap.go
- pkg/deploy/configmap_cert.go
- pkg/deploy/data_types.go
- pkg/deploy/deployment.go
- pkg/deploy/deployment_che.go
- pkg/deploy/deployment_keycloak.go
- pkg/deploy/deployment_postgres.go
- pkg/deploy/deployment_registry.go
- pkg/deploy/devfile_registry.go
- pkg/deploy/ingress.go
- pkg/deploy/job.go
- pkg/deploy/plugin_registry.go
- pkg/deploy/proxy.go
- pkg/deploy/pvc.go
- pkg/deploy/role.go
- pkg/deploy/rolebinding.go
- pkg/deploy/route.go
- pkg/deploy/secret.go
- pkg/deploy/service.go
- pkg/deploy/service_account.go
- pkg/deploy/tls.go
- pkg/deploy/update.go
Reference issue: https://github.com/eclipse/che/issues/17589
> Create a general deployContext to pass to all functions instead of pass numerous arguments

- pkg/deploy/che_configmap.go
- pkg/deploy/che_configmap_test.go
If Eclipse Che is configured to use a separate namespace for Che workspaces via `CHE_INFRA_KUBERNETES_NAMESPACE_DEFAULT` Che property, then add into Che config map Che server TLS secret (key and certificate) in order for Che server to be able to configure workspace components with right TLS key and certificate (as it is not possible to access Che server TLS secret from a separate namespace) .
https://github.com/eclipse/che/issues/17631
> Add server TLS key and cert into Che configmap if a separate namespace for Che workspaces is configured

- pkg/deploy/tls.go
Adds second attempt to retrieve cluster CA certificate in case if Openshift cluster uses proxy and first request without the proxy failed. The second request uses proxy, but adds warning that this could be not accurate.
> Make additional requiest for test route certs if first one fails without proxy

- pkg/deploy/deployment_che.go
Single user Che is not compatible with rolling update, so after any change in CheCluster CR Che deployment is failed to start with the following error
```
20) Error injecting constructor, org.eclipse.che.core.db.schema.SchemaInitializationException: Cannot create PoolableConnectionFactory (Database may be already in use: null. Possible solutions: close all other connection(s); use the server mode [90020-196])
```
This PR is supposed to fix that issue but I haven't tested it.
> Fix reconciling of single user Che

- olm/update-nightly-olm-files.sh
Add a check in olm/update-nightly-olm-files.sh to check that the correct version of operator-sdk is installed. Otherwise, if a newer version is installed, the command will fail with a cryptic error message.
I've tested changes with `operator-sdk v0.14.0`, `operator-sdk v0.10.1` and no operator-sdk in the `$PATH`.
> Check Operator SDK version in update nightly script

- pkg/deploy/deployment_keycloak.go
- pkg/deploy/proxy.go
- pkg/deploy/proxy_test.go
Correctly converts wildcards from nonProxyHosts in Che CR for JAVA_OPTS.
For Java, wildcards should look like `*.domain.com` instead of just `.domain.com`
https://github.com/eclipse/che/issues/17831
> Correctly convert wildcards in nonProxyHosts for JAVA_OPTS

- deploy/crds/org_v1_che_cr.yaml
https://github.com/eclipse/che/issues/17888
Since `spec.server.singleHostGatewayConfigMapLabel` is type of `labels.Set` the default value should be set to `{}` instead of `""`
> Set default value to {} for singleHostGatewayConfigMapLabels

- templates/keycloak_provision
https://github.com/eclipse/che/issues/14083
Disable self registration of users by default
> Disable selfregistration users by default

- .github/workflows/che-nightly.yaml
- .github/workflows/che-operator-updates.yaml
- .github/workflows/e2e.yaml
- .github/workflows/olm_checks_platforms.yaml
This PR fix GH api response in PR.
Example of fails:https://github.com/eclipse/che-operator/pull/474/checks?check_run_id=1166233363
LOG: `Running pre-create checks...
(default) Image cache directory does not exist, creating it at /Users/runner/.docker/machine/cache...
(default) No default Boot2Docker ISO found locally, downloading the latest release...
Error with pre-create check: "failure getting a version tag from the Github API response (are you getting rate limited by Github?)"
`
Also I add to artifacts load to execute always in jobs even if previous steps of actions fails.
> Fix api limitation minishift

- .github/action_scripts/build_olm_bundle_images.sh
Check if the bundle was already pushed to the catalog source. In case if the bundle was not pushed, build the bundles container and push to quay.io
Refference issue: https://github.com/eclipse/che/issues/17907
> Build a catalog source image only if there is a new nightly bundle image

- .github/workflows/operator-build-nightly.yaml
After migrating normal jobs in PR from centos ci to GH actions is time to migrate nightly build from centos ci to GH actions.
> Build nightly images of operator in github actions

- .vscode/launch.json
- .vscode/tasks.json
- local-debug.sh
- pkg/util/util.go
> Fix debugger for openshift cluster.

- Dockerfile
- deploy/olm-catalog/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
- deploy/olm-catalog/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- deploy/operator-local.yaml
- deploy/operator.yaml
- olm/update-nightly-bundle.sh
- pkg/deploy/defaults.go
fix: Revert "CRW-1254 can we use the standard ubi URLs" (turns out no, it breaks stuff); also bump versions to 7.20.0-13.nightly
Change-Id: I7006cbb4676157e0837e1cd5df702c4165bb5c91
> fix: Revert "CRW-1254 can we use the standard ubi URLs" (turns out no, it breaks stuff); also bump versions to 7.20.0-13.nightly

- .ci/cico_minishift_nightly.sh
- .ci/cico_openshift_shost.sh
- .ci/cico_updates_minishift.sh
- .github/action_scripts/nightly/minikube/single-host-gateway.sh
- .github/action_scripts/nightly/minikube/single-host-native.sh
- README.md
- RELEASE.md
https://github.com/eclipse/che/issues/18057
> Deprecate server:start command

- templates/keycloak_provision
https://github.com/eclipse/che/issues/17902
> Limit keycloak redirect urls

- .github/action_scripts/build_olm_bundle_images.sh
- .github/action_scripts/operator_code_check.sh
- .github/action_scripts/provideNewNightlyBundle.sh
- .github/workflows/checkNightlyOpmBundle.yaml
- .github/workflows/pushCatalogImages.yaml
- olm/incrementNightlyBundles.sh
- olm/update-nightly-bundle.sh
https://github.com/eclipse/che/issues/17338
Add commit new nightly bundle github action: if developer changed deployment yaml files, then github action at the night should commit new bundle and bundle images will be pushed. If there is no changes in the deployment yamls - then nothing to commit.
Fix not needed push bundle images, when we have had already pushed images.
> Add commit new nightly bundle github action.

- deploy/crds/org_v1_che_cr.yaml
- deploy/crds/org_v1_che_crd.yaml
- deploy/olm-catalog/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
- pkg/apis/org/v1/che_types.go
- pkg/apis/org/v1/zz_generated.openapi.go
- pkg/controller/che/che_controller.go
- pkg/deploy/ingress.go
- pkg/deploy/secret.go
- pkg/deploy/server/che_configmap.go
- pkg/deploy/tls.go
Adds ability to tell Che operator to use default ingress TLS certificate to secure Che endpoints.
To use default ingress certificate, field `k8s.tlsSecretName` should be empty string or absent.
https://github.com/eclipse/che/issues/18079
1. Create a new Minikube instance.
2. Enable ingress addon: `minikube addons enable ingress`
3. Change the default ingress certificate
<details>
<summary>Automation script</summary>
```sh
#!/bin/bash
MINIKUBE_DOMAIN=$(minikube ip).nip.io
CA_CN='Custom Minikube CA'
CA_KEY_FILE='ca.key'
CA_CERT_FILE='ca.crt'
CN_SERVER='Minikube Ingress'
SERVER_KEY_FILE='domain.key'
SERVER_CERT_REQUEST_FILE='domain.csr'
SERVER_CERT_FILE='domain.crt'
CHAIN_FILE='chain.pem'
OPENSSL_CNF='/etc/pki/tls/openssl.cnf'
if [ ! -f …
```
> Implement ability to use default ingress TLS certificate

- pkg/deploy/identity-provider/deployment_keycloak.go
https://issues.redhat.com/browse/CRW-1379
> Add codeready user readonly theme

- deploy/olm-catalog/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
- deploy/olm-catalog/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- deploy/role.yaml
- pkg/controller/che/che_controller.go
- pkg/deploy/role.go
- pkg/deploy/tls.go
Signed-off-by: svor <vsvydenk@redhat.com>
- Adds new verb **get**  with " " APIGroups  to get an information about limited resources 
- Adds new APIGroups  **metrics.k8s.io** to get an information from Metric server
https://github.com/eclipse/che/issues/17205
> Add metrics role and extend view role

- pkg/controller/che/che_controller_test.go
- pkg/deploy/gateway/gateway.go
- pkg/deploy/identity-provider/identity_provider.go
- pkg/deploy/sync.go
When changing the `serverExposureStrategy` between `multi-host` and `single-host`, the URL of the keycloak server changes. This must be reflected in the OAuthClient object on OpenShift when using OpenShift OAuth otherwise OpenShift won't allow the users to login.
This fixes eclipse/che#17886.
> Refresh oauth client

- pkg/controller/che/che_controller_test.go
- pkg/deploy/data_types.go
- pkg/deploy/identity-provider/deployment_keycloak.go
- pkg/deploy/identity-provider/identity_provider.go
- pkg/deploy/server/che_configmap.go
Add ability to use internal network for keycloak.
https://github.com/eclipse/che/issues/17644
> feat: Add ability to use internal network for Keycloak

- pkg/controller/che/che_controller.go
- pkg/controller/che/proxy.go
- pkg/deploy/configmap.go
- pkg/deploy/defaults.go
- pkg/deploy/identity-provider/deployment_keycloak.go
- pkg/deploy/server/che_configmap.go
- pkg/deploy/server/configmap_cert.go
- pkg/deploy/server/deployment_che.go
- pkg/deploy/tls.go
This PR merged all config maps with CA certificates that marked with `che-ca-certs:true` label into single config and then pass resulting config map to Che server.
`spec.server.serverTrustStoreConfigMapName` CR field is supported too and the config map, if any, added into resulting one as well.
https://github.com/eclipse/che/issues/17634
1. Deploy Eclipse Che
2. Create a few config maps in `che` namespace with CA certs
3. Mark some of them with `che-ca-certs:true` label
4. Start a workspace, check `/public-certs` folder
To generate CA certs, one may use the following script:
```bash
#!/bin/bash
OPENSSL_CNF='/etc/pki/tls/openssl.cnf'
if [ ! -f $OPENSSL_CNF ]; then
OPENSSL_CNF='/etc/ssl/openssl.cnf'
fi
for ((i=1;i<=5;i++)); do
openssl genrsa …
```
> Implement addition CA config maps merge and propagation to Che server

- deploy/olm-catalog/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
- deploy/olm-catalog/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- deploy/operator-local.yaml
- deploy/operator.yaml
Used images that moved from docker hub
https://github.com/eclipse/che/issues/18292
> Replace postgres image

- pkg/deploy/identity-provider/deployment_keycloak.go
Makes it possible to import several CA certificates from a single file into Keycloak's java trust store.
https://github.com/eclipse/che/issues/18339
1. Create a *.pem file that contains several root CA certificates
2. Create a configmap with single data field which contains the *.pem file
3. Add the configmap as trusted for Che
4. Check that all CA certs are added into Keycloak's trust store
> Import all certificates from propagated bundles into Keycloak's truststore

- make-release.sh
Change-Id:...
add missing path to olm folder
Change-Id: Ia1827dd5c6ebf48fd80bd7976778998d342013b2
N/A
N/A (or see commit messasge above for issue number)
N/A
> add missing path to olm folder

- local-debug.sh
- pkg/deploy/server/che_configmap.go
Prevents potential NPE.
Fixes local debug command
https://github.com/eclipse/che/issues/18474
> Fix potential NPE

- pkg/controller/che/che_controller.go
- pkg/deploy/defaults.go
- pkg/deploy/deployment.go
- pkg/deploy/deployment_test.go
- pkg/deploy/tls.go
https://github.com/eclipse/che/issues/18607
Allows to mount secrets as file or env variable in che/postgres/keycloak/registries containers.
> Mount secrets in containers

- cmd/manager/main.go
- deploy/olm-catalog/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
- deploy/olm-catalog/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- deploy/operator-local.yaml
- deploy/operator.yaml
- pkg/deploy/identity-provider/deployment_keycloak.go
- pkg/deploy/postgres/deployment_postgres.go
- pkg/deploy/registry/registry.go
https://issues.redhat.com/browse/CRW-683
https://issues.redhat.com/browse/CRW-916
- add liveness and readiness probes for operator
- add liveness probe for keycloak and postgres containers
> Add liveness and readiness probes

- .github/workflows/minikube-stable-updates.yaml
- .github/workflows/minishift-stable-updates.yaml
There is no sense to run stable tests in every PR. Move stable tests to release branches and run only when a new release it is created.
Ref issue: https://github.com/eclipse/che/issues/18293
> Move stable tests to release branches

- cmd/manager/main.go
- deploy/olm-catalog/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
- deploy/olm-catalog/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- deploy/operator.yaml
Revert recreate strategy and probes for operator
> Revert recreate strategy and probes for operator

- .github/workflows/build.yml
- .github/workflows/nightly-image-build.yaml
- Dockerfile
- go.mod
- vendor/modules.txt
- Reverts golang version from 1.14 to 1.13 (1.14 causes failed build on different platforms)
- Added github action to check multi-platform build
https://github.com/eclipse/che/issues/18768
> Revert golang version to 1.13

- pkg/deploy/identity-provider/exec.go
The latest rh-sso Dockerfile doesn't contain `WORKDIR` instruction. 
```
WORKDIR /home/jboss
```
So, we have to `cd /home/jboss` before doing exec.
https://issues.redhat.com/browse/CRW-1458
> `cd /home/jboss` before exec into identity provider container

- deploy/crds/org_v1_che_crd.yaml
- deploy/olm-catalog/eclipse-che-preview-kubernetes/manifests/org_v1_che_crd.yaml
- deploy/olm-catalog/eclipse-che-preview-openshift/manifests/org_v1_che_crd.yaml
- pkg/apis/org/v1/che_types.go
Backports https://github.com/eclipse/che-operator/pull/627 to 7.24.x
> Backport image puller docstring change to 7.24.x

- pkg/deploy/deployment.go
Adds `SecurityContext` of `Containers` field of pod template spec of `Deployment` into ignore list.
This will prevent from infinite loop in Operator when infrastructure sets own defaults (so operator will ignore that and will not try to set own value against platform defaults).
Should fix https://github.com/eclipse/che/issues/18828
Use image built from this PR within CRW CCI
> Add 'SecurityContext' of Containers into diff ignore on Deployments comparison

- .github/CODEOWNERS
Remove @davidfestal from code owners, since it doesn't make sense anymore.
> Remove @davidfestal from code owners

- pkg/deploy/identity-provider/deployment_keycloak.go
- pkg/deploy/server/deployment_che.go
Increases initial delay for Keycloak and Che server in liveness probe configuration to prevent failure in case of longer start of the components. It might be caused by different reasons, but what was spotted is importing of a big bundle of CA certificates that takes some time to finish.
N/A
Create a big bundle of self-signed CA certificates (100 or 200) and add all of them as trusted. Now CHe server and Keycloak should be able to start.
> Increase liveness probe initial delay for Keycloak and Che server

- pkg/controller/che/init_test.go
- pkg/controller/che/proxy.go
- pkg/controller/che/proxy_test.go
- pkg/deploy/defaults.go
- pkg/deploy/proxy.go
- pkg/deploy/proxy_test.go
1. NoProxy hosts configured in checluster and in clusterwide proxy should be merged
2. Add '.svc` to nonProxy for OpenShift 3.x and k8s
https://issues.redhat.com/browse/CRW-1520
1. Deploy Eclipse Che in a OpenShift cluster with cluster wide proxy configured.
2. Set proxy configuration in checluster as well.
3. Che server started
> Fix proxy and internal hostname case (#646)

- deploy/crds/org_v1_che_crd.yaml
- deploy/olm-catalog/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
- deploy/olm-catalog/eclipse-che-preview-kubernetes/manifests/org_v1_che_crd.yaml
- deploy/olm-catalog/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- deploy/olm-catalog/eclipse-che-preview-openshift/manifests/org_v1_che_crd.yaml
- pkg/apis/org/v1/che_types.go
Fix numerous doc issues
it is a prerequisite for https://github.com/eclipse/che-docs/pull/1803
https://issues.redhat.com/browse/RHDEVDOCS-2216
> Fix numerous doc issues

- .ci/cico_updates_openshift.sh
- .ci/oci-nightly-olm.sh
- .ci/oci-single-host.sh
- .github/bin/common.sh
- .github/bin/oauth-provision.sh
- .github/bin/resources/htpasswdProvider.yaml
- .github/bin/resources/users.htpasswd
This PR cover all our openshift tests with OAUTH.
Reff issue: https://github.com/eclipse/che/issues/17939
> Add oauth to tests

- .ci/cico_updates_openshift.sh
- .ci/oci-nightly-olm.sh
- .ci/oci-single-host.sh
- .github/bin/common.sh
- .github/bin/minikube/test-olm.sh
- .github/bin/minikube/test-operator-singlehost-gateway.sh
- .github/bin/minikube/test-operator-singlehost-native.sh
- .github/bin/minikube/test-operator-update.sh
- .github/bin/minikube/test-stable-olm-update.sh
- .github/bin/minishift/test-operator-update.sh
- .github/bin/minishift/test-operator.sh
- .github/bin/minishift/test-stable-operator-update.sh
- .github/workflows/minishift-operator-update.yaml
- .github/workflows/minishift-operator.yaml
Login using OCP token for e2e tests
https://github.com/eclipse/che/issues/17939
> Login using OCP token for e2e tests

- deploy/crds/org_v1_che_crd.yaml
- deploy/olm-catalog/eclipse-che-preview-kubernetes/manifests/org_v1_che_crd.yaml
- deploy/olm-catalog/eclipse-che-preview-openshift/manifests/org_v1_che_crd.yaml
- pkg/apis/org/v1/che_types.go
- pkg/controller/che/che_controller.go
- pkg/controller/che/che_controller_test.go
- pkg/deploy/deployment.go
- pkg/deploy/devfile-registry/devfile_registry.go
- pkg/deploy/expose/expose.go
- pkg/deploy/identity-provider/identity_provider.go
- pkg/deploy/ingres_test.go
- pkg/deploy/ingress.go
- pkg/deploy/plugin-registry/plugin_registry.go
- pkg/deploy/route.go
- pkg/deploy/route_test.go
- pkg/deploy/secret.go
- pkg/deploy/server/che_configmap.go
- pkg/deploy/server/che_configmap_test.go
- pkg/deploy/tls.go
Allow to configure domain for routes.
The host will be constructed as `<route-name>-<namespace>.<domain>`
https://issues.redhat.com/browse/CRW-1466
> Allow to configure domain to create routes

- Dockerfile
- deploy/olm-catalog/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
- deploy/olm-catalog/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- deploy/operator.yaml
- go.sum
- pkg/deploy/defaults.go
- pkg/deploy/deployment.go
- pkg/deploy/identity-provider/deployment_keycloak.go
- pkg/deploy/identity-provider/deployment_keycloak_test.go
- pkg/deploy/identity-provider/identity_provider.go
- pkg/deploy/identity-provider/identity_provider_test.go
- pkg/deploy/postgres/deployment_postgres.go
- pkg/deploy/secret.go
- pkg/deploy/sercet_test.go
- pkg/deploy/server/che_configmap.go
- pkg/deploy/server/che_configmap_test.go
- pkg/deploy/server/deployment_che.go
- pkg/deploy/server/deployment_che_test.go
- pkg/util/test_util.go
- pkg/util/util.go
Allow to configure github and bitbucket oauth config
https://github.com/eclipse/che/issues/18932
> Allow to configure github and bitbucket oauth config

- .github/bin/minishift/test-stable-operator-update.sh
- .github/workflows/minishift-stable-operator-update.yaml
User --version flag to deploy and update Eclipse Che
> Use --version flag to deploy and update Eclipse Che

- pkg/deploy/server/che_configmap.go
- pkg/deploy/server/che_configmap_test.go
Resolve partially https://github.com/eclipse/che/issues/18872#issuecomment-767376941
Currently, che always communicates with theia and plugin broker via public endpoint.
This PR fixes for plugin broker.
> Allow to use internal host name for CHE_WEBSOCKET_ENDPOINT and CHE_WEBSOCKET_ENDPOINT__MINOR

- deploy/crds/org_v1_che_cr.yaml
- deploy/crds/org_v1_che_crd.yaml
- deploy/olm-catalog/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
- deploy/olm-catalog/eclipse-che-preview-kubernetes/manifests/org_v1_che_crd.yaml
- deploy/olm-catalog/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- deploy/olm-catalog/eclipse-che-preview-openshift/manifests/org_v1_che_crd.yaml
- pkg/apis/org/v1/che_types.go
Delete tls switcher. Add plugin and devfile registry links.
https://issues.redhat.com/browse/CRW-1613
Install Eclipse Che using OLM installer. On the Openshift UI go to: Operators -> Installed operators -> Select and click on CheCluster item and take a look descriptions tab.
> Delete tls switcher. Add plugin and devfile registry links.

- .ci/oci-nightly-olm.sh
- .github/bin/common.sh
- Dockerfile
- deploy/cluster_role.yaml
- deploy/olm-catalog/nightly/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
- deploy/olm-catalog/nightly/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- local-debug.sh
- make-release.sh
- pkg/deploy/dev-workspace/dev_workspace.go
- pkg/deploy/dev-workspace/dev_workspace_test.go
Che Operator should be able to install the Devworkspace che operator
Fixes https://github.com/eclipse/che/issues/19142
> Che Operator should be able to install the Devworkspace che operator

- pkg/deploy/kubernetes_image_puller.go
Do not fail if imagePuller CRD does not exist.
I did the minimal changes which should fix the issue but that logic in general it seems complex and may have other bugs.
It fixes https://github.com/eclipse/che/issues/19207 on my RHPDS instance.
I tested only deploying Che with imagePuller disabled, before it failed with 
```
"Error uninstalling Image Puller: no matches for kind \"KubernetesImagePuller\" in version \"che.eclipse.org/v1alpha1\""
```
> Do not fail if imagePuller CRD does not exist

- pkg/controller/che/proxy.go
- pkg/controller/che/proxy_test.go
Includes CA certificates configured in `proxy/cluster` into list of trusted by Che certificates even if no proxy configuration added.
https://github.com/eclipse/che/issues/17938
1. Configure Openshift router with a custom certificate chain
2. Add all the CA certificates from the chain into `proxy/cluster` (excluding server one).
3. Deploy Che using operator from this branch
4. Start a workspace, ensure everything works as expected
> Include additional cluster-wide trusted CA into Che

- go.mod
- go.sum
- local-debug.sh
- pkg/controller/che/che_controller.go
- pkg/controller/che/che_controller_test.go
- pkg/controller/che/cluster_permissions_finalizer.go
- pkg/controller/che/workspace_namespace_permission.go
- pkg/deploy/clusterrole.go
- pkg/deploy/clusterrole_test.go
- pkg/deploy/clusterrolebinding.go
- pkg/deploy/clusterrolebinding_test.go
- pkg/deploy/consolelink.go
- pkg/deploy/consolelink_test.go
- pkg/deploy/dev-workspace/dev_workspace.go
- pkg/deploy/finalizer.go
- pkg/deploy/finalizer_test.go
- pkg/deploy/identity-provider/identity_provider.go
- pkg/deploy/kubernetes_image_puller.go
- pkg/deploy/sync.go
- pkg/deploy/sync_test.go
- pkg/util/util.go
- pkg/util/util_test.go
Remove consolelink object when CheCluster is removed
https://github.com/eclipse/che/issues/18501
> Remove consolelink object when CheCluster is removed

- README.md
- pkg/deploy/dev-workspace/dev_workspace.go
PR https://github.com/devfile/devworkspace-operator/pull/336 removes the Component CRD from the DevWorkspace Operator. As a result, depending on the components file will cause issues going forward in chectl, and it should be removed.
No issue created yet, but we'll see failures soon as https://github.com/devfile/devworkspace-operator/pull/336 is merged to main
Test deploying with DWO as normal.
> Remove components CRD from DevWorkspace Operator deployment

- .ci/oci-devworkspace-happy-path.sh
This PR changes waiting for **happy-path** pod in `Running` state to 4 min. Sometimes 1 min not enough for the pod to start([example](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/17107/rehearse-17107-pull-ci-eclipse-che-che-operator-master-v7-devworkspace-happy-path/1375101093381410816/artifacts/devworkspace-happy-path/devworkspace-happy-path/build-log.txt)).
> Stabilize devworkspace-happy-path job

- .ci/oci-devworkspace-happy-path.sh
- .ci/openshift-ci/happy-path-che.yaml
1. Update **APPY_PATH_DEVFILE**  to  [devfile](https://gist.githubusercontent.com/l0rd/71a04dd0d8c8e921b16ba2690f7d5a47/raw/d520086e148c359b18c229328824dfefcf85e5ef/spring-petclinic-devfile-v2.0.0.yaml).
2. Set **TS_SELENIUM_LOG_LEVEL** to **TRACE** for more informative logs.
3. Set namespace field in `happy-path-che.yaml` file to `${NAMESPACE}` env.
4. Check `EXIT_CODE` env in happy-path-pod for checking test result(`EXIT_CODE=1` means failing).
5. Use builded che-operator image in Eclipse Che deployment(using  `--che-operator-image` option).
> Update happy-path test devfile url, use builded che-operator image for Che deployment

- .github/workflows/nightly-image-build.yaml
Allow to trigger image build manually
> Allow to trigger image build manually

- .github/bin/common.sh
After merging: https://github.com/che-incubator/chectl/pull/1165, Some PR are failing like here: https://github.com/eclipse-che/che-operator/pull/762/checks?check_run_id=2297829370 with error:
```log
2021-04-08T20:48:19.5725009Z [20:48:19] Verify Kubernetes API...OK [title changed]
2021-04-08T20:48:19.5957906Z [20:48:19] Verify Kubernetes API...OK [completed]
2021-04-08T20:48:19.5963556Z [20:48:19] 👀  Looking for an already existing Eclipse Che instance [started]
2021-04-08T20:48:19.5967138Z [20:48:19] Verify if Eclipse Che is deployed into namespace "eclipse-che" [started]
2021-04-08T20:48:19.6036002Z [20:48:19] Verify if Eclipse Che is deployed into namespace "eclipse-che"...it is not [title changed]
2021-04-08T20:48:19.6037680Z …
```
> Fix che operator single-host tests by adding devworkspace templates to chectl command

- pkg/controller/che/che_controller.go
- pkg/deploy/devfile-registry/devfile_registry.go
- pkg/deploy/expose/expose.go
- pkg/deploy/gateway/gateway.go
- pkg/deploy/identity-provider/deployment_keycloak.go
- pkg/deploy/identity-provider/identity_provider.go
- pkg/deploy/ingres_test.go
- pkg/deploy/ingress.go
- pkg/deploy/oauthclient.go
- pkg/deploy/plugin-registry/plugin_registry.go
- pkg/deploy/route.go
- pkg/deploy/route_test.go
- pkg/deploy/server/che_configmap.go
- pkg/deploy/server/che_configmap_test.go
- pkg/deploy/tls.go
Refactor exposure to have an ability to share host among components.
It's needed since even in multi-host dashboard used to share Che API host and we're not going to change it for time being.
Its usage can be found at another PR where a dedicated pod for Che Dashboard is implemented: https://github.com/eclipse-che/che-operator/pull/684/commits/736efef02175397f3ffe7b0603736335eb96391d#diff-a434bd1b85e2ebded7afe3539d59f554f735b7890ad997c99d170ef0f813a4a9R56
It's prereq for dashboard in a separate deployment https://github.com/eclipse-che/che-operator/pull/684
Nothing should be changed in user-facing stuff.
I tested:
**OpenShift (RHPDS):**
- multihost
- gateway singlehost
:notebook: I tested with dashboard changes but haven't retested after dropping it.
But nothing should change I believe. …
> Refactor exposure to have an ability share host among components

- .ci/oci-devworkspace-happy-path.sh
Happy Path tests should use current templates to avoid inconsistency in testing.
For instance [1] Happy Path tests failed because new dashboard image wasn't used in deployment.
[1] https://github.com/eclipse-che/che-operator/pull/684 
> Make happy path tests to use latest templates from PR

- .github/workflows/pr-check.yml
- deploy/crds/org_v1_che_crd-v1beta1.yaml
- deploy/crds/org_v1_che_crd.yaml
- deploy/olm-catalog/nightly/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
- deploy/olm-catalog/nightly/eclipse-che-preview-kubernetes/manifests/org_v1_che_crd.yaml
- deploy/olm-catalog/nightly/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- deploy/olm-catalog/nightly/eclipse-che-preview-openshift/manifests/org_v1_che_crd.yaml
- deploy/operator.yaml
- make-release.sh
- olm/release-olm-files.sh
- pkg/apis/org/v1/che_types.go
- pkg/controller/che/che_controller.go
- pkg/deploy/dashboard/dashboard.go
- pkg/deploy/dashboard/dashboard_deployment_test.go
- pkg/deploy/dashboard/dashboard_test.go
- pkg/deploy/dashboard/deployment_dashboard.go
- pkg/deploy/dashboard/init_test.go
- pkg/deploy/defaults.go
- pkg/deploy/defaults_test.go
- replace-images-tags.sh
It makes the Che operator run the dashboard as a separate Deployment. The same was previously done for helm charts.
The main reason why these changes were made, it's
> STEP1 - running the HTTP server that serves the dashboard in its own pod: customising the dashboard is just a matter of rebuilding the dashboard container image.
from https://github.com/eclipse/che/issues/15778#issuecomment-692535413
Now things changed and we have a plan to introduce a backend for the dashboard. So, it becomes a need.
It depends on https://github.com/eclipse-che/che-operator/pull/760
It's the first step for https://github.com/eclipse/che/issues/15778
It's the second step for https://github.com/eclipse/che/issues/17802
And a prerequisite for Dashboard backend (not sure if an issue exists at this point)
Test …
> Run dashboard as separate deployment

- pkg/deploy/dashboard/dashboard.go
- pkg/deploy/dashboard/dashboard_test.go
- pkg/deploy/dashboard/deployment_dashboard.go
Add common labelSelector for che-dashboard like other components have. In our helm chart we are including a `component: che-dashboard` https://github.com/eclipse/che/blob/master/deploy/kubernetes/helm/che/templates/dashboard-deployment.yaml#L15
N/A
https://github.com/eclipse/che/issues/19605
1. Build che-operator image and deploy with chectl: `chectl server:deploy -p minikube --installer=operator --che-operator-image=<image-builded>`
2. check the labels using: `kubectl get pod <dashboard-pod> --show-labels`
> fix: Add common selector for che-dashboard

- README.md
- deploy/cluster_role.yaml
- deploy/olm-catalog/nightly/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
- deploy/olm-catalog/nightly/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- pkg/controller/che/workspace_namespace_permission.go
Signed-off-by: svor <vsvydenk@redhat.com>
Adds role for **metrics.k8s.io** into cluster role to get an information from Metric server. It is need in case when workpsaces are running in different namespace than che
https://github.com/eclipse/che/issues/18812
> Add metrics role to the cluster role

- .github/workflows/release.yml
- make-release.sh
Fix release script to check resources only once
Error log:
https://github.com/eclipse-che/che-operator/runs/2519813147?check_suite_focus=true
Release process
N/A
> Fix release script to check resources only once

- deploy/crds/org_v1_che_crd-v1beta1.yaml
- deploy/crds/org_v1_che_crd.yaml
- deploy/olm-catalog/nightly/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
- deploy/olm-catalog/nightly/eclipse-che-preview-kubernetes/manifests/org_v1_che_crd.yaml
- deploy/olm-catalog/nightly/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- deploy/olm-catalog/nightly/eclipse-che-preview-openshift/manifests/org_v1_che_crd.yaml
- pkg/apis/org/v1/che_types.go
- pkg/controller/che/che_controller.go
- pkg/controller/che/che_controller_test.go
- pkg/controller/che/che_cr_validator.go
- pkg/controller/che/workspace_namespace_permission.go
- pkg/deploy/server/che_configmap.go
- pkg/deploy/server/deployment_che.go
- pkg/util/util.go
- Do not allow to upgrade che 7.31 or later to upgrade installation that configured with namespace strategies other than "per user"
- Operator delegates permissions that are needed to start a workspace in a dedicated namespace
- Previous permissions (that are needed to start a workspace in the same namespace) are not removed to allow to start previously created workspaces
N/A
https://github.com/eclipse/che/issues/19537
N/A
@abazko: Manually checked updates to `per-user`  namespace strategy. New and previously workspaces are started on both k8s and OpenShift clusters.
> Do not allow to upgrade che 7.31 or later to upgrade installation that configured with namespace strategies other than "per user"

- pkg/controller/che/che_controller.go
Use OpenShift API internal URL to fetch API certificate. 
It does not require setting `spec.server.nonProxyHosts: api.<DOMAIN>` in the CR.
N/A
https://github.com/eclipse/che/issues/19668
Run tests Eclipse Che in a OpenShift restricted environment.
> Use OpenShift API internal URL to fetch API certificate

- .github/bin/common.sh
- .github/bin/minikube/test-operator-singlehost-gateway.sh
- .github/bin/minikube/test-operator-singlehost-native.sh
- .github/workflows/minikube-operator-singlehost.yaml
- Tests will fail sooner if workspace failed to start
- Disable devworkspace startup on minikube for single-host mode
https://github.com/eclipse/che/issues/19765
N/A
https://github.com/eclipse/che/issues/19765
N/A
> Remove devworkspace start in single-host in minikube

- .ci/cico_updates_openshift.sh
- .ci/oci-multi-host.sh
- .ci/oci-single-host.sh
- .github/bin/common.sh
- Dockerfile
- deploy/cluster_role.yaml
- deploy/olm-catalog/nightly/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
- deploy/olm-catalog/nightly/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- deploy/operator.yaml
- olm/olm.sh
- pkg/deploy/defaults.go
- pkg/deploy/dev-workspace/dev_workspace.go
- pkg/deploy/dev-workspace/dev_workspace_test.go
- pkg/deploy/sync.go
- pkg/deploy/test_util.go
- pkg/util/test_util.go
- pkg/util/util.go
- Che Operator sets annotations DWO and DWCO resources
- Che Operator syncs DWO and DWCO resources by updating them if hashes are different 
- Add DWO and DWCO tests for OCP
N/A
Che Operator does not update DWO and DWCO resources https://github.com/eclipse/che/issues/19664
1. Run OCP cluster
2. Update ./local-debug.sh [1] by setting some old version of DWO and DWCO, for instance 
```
DEV_WORKSPACE_CONTROLLER_VERSION="v0.2.1"
DEV_WORKSPACE_CHE_OPERATOR_VERSION="v7.28.0"
```
3. Update CR [2] to turn off OAuth (spec.auth.openShiftoAuth: false)
4. Update CR [2] to turn on DevWorkspace (spec.devWorkspace.enable: true)
5. Run `./local-debug.sh`, wait until everything is deployed
6. Stop `./loca-debug.sh` and update DWO and DWCO, for instance: …
> Che Operator updates DWO and DWCO resources

- Dockerfile
- deploy/cluster_role.yaml
- deploy/olm-catalog/nightly/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
- deploy/olm-catalog/nightly/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- pkg/controller/che/workspace_namespace_permission.go
This PR adds delete permissions for the Che service account to allow deleting PVCs.
Che service account is now able to delete PVCs:
Fixes https://github.com/eclipse/che/issues/19867
Here is the Che operator image: `quay.io/dkwon17/che-operator:19867`
1. Start minikube and deploy Che with the operator with `chectl`
```
minikube start --addons=ingress --vm=true --memory=8192
chectl server:deploy --installer operator -p minikube --che-operator-image=quay.io/dkwon17/che-operator:19867
```
2. Create a workspace, which creates a PVC named `claim-che-workspace` (here the PVC strategy is `common`) in the `admin-che` namespace:
3. Delete the PVC using `oc`
```
oc login --token=<che service account token>
oc project admin-che
oc delete pvc …
```
> fix: Add PVC delete permission to che service account

- deploy/olm-catalog/nightly/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
- deploy/olm-catalog/nightly/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- pkg/controller/che/workspace_namespace_permission.go
- pkg/controller/che/workspace_namespace_permission_test.go
che-operator delegates some permissions to manipulates with devworkspace resources
N/A
https://github.com/eclipse/che/issues/19920
1. deploy Eclipse Che
2. check if `eclipse-che-cheworkspaces-devworkspace-clusterrole` cluster role & cluster role binding are created
Image to test: `docker.io/abazko/operator:19920`
> chore: Ensure that che-server's SA have enough permission to manipulate with devworkspaces resource on kubernetes

- pkg/apis/org/conversion.go
- pkg/apis/org/conversion_test.go
- pkg/apis/org/v2alpha1/checluster.go
This adds the ability to configure the labels that should be put on the config maps with the traefik configuration for workspaces. This is needed for the future where che-operator and dwco will share a single gateway.
N/A
eclipse/che#19846
This does not introduce any runtime behavior in che-operator.
> Add support for configuring the labels for gateway configmaps

- Dockerfile
https://github.com/eclipse/che/issues/19762# - can't use ubi8-minimal:8.4 and then install golang as Brew builds fail with
error: No available modular metadata for modular package 'golang-1.15.7-1.module+el8.4.0+9580+3b0e6c24.ppc64le'; cannot be installed on the system
Change-Id: If0dc121ed855da22cea36d078dd6df05a340e66d
don't need to install bzip2 or unzip; already in the go toolset image
Change-Id: If6110970de17482c1c1c39f5b5fe0f094f7d74e8
N/A
N/A
Reviewers, please comment how you tested the PR …
> chore: eclipse/che#19762 - can't use ubi8-minimal:8.4 and then install golang as Brew builds fail

- .github/bin/check-resources.sh
- deploy.sh
- deploy/olm-catalog/nightly/eclipse-che-preview-kubernetes/csv-config.yaml
- deploy/olm-catalog/nightly/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
- deploy/olm-catalog/nightly/eclipse-che-preview-kubernetes/manifests/org.eclipse.che_chebackupserverconfigurations_crd.yaml
- deploy/olm-catalog/nightly/eclipse-che-preview-openshift/csv-config.yaml
- deploy/olm-catalog/nightly/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- deploy/olm-catalog/nightly/eclipse-che-preview-openshift/manifests/org.eclipse.che_chebackupserverconfigurations_crd.yaml
- local-debug.sh
- make-release.sh
- olm/prepare-community-operators-update.sh
- olm/release-olm-files.sh
- olm/update-resources.sh
Update scripts to handle `org.eclipse.che_chebackupserverconfigurations` CRD
N/A
Follow up PR for https://github.com/eclipse-che/che-operator/pull/844
Run scripts:
- `olm/update-resources.sh`
- `deploy.sh`
- `local-debug.sh`
- `make-release.sh`
- `olm/release-olm-files.sh`
- `olm/prepare-community-operators-update.sh`
> Update scripts to handle chebackupserverconfigurations CRD

- pkg/deploy/kubernetes_image_puller.go
Sometimes when we create in Che Cluster the specs for KIP we don't add the configMapName and deploymentName. This is a conflict for operator because ImagePuller operator already add this values if che operator create them empty and in reconcile cheCluster expect this values to be empty always.
https://issues.redhat.com/browse/CRW-1953
Execute local-debug
> fix: Fix image puller reconcile infinite loop when checluster image puller deployment name and configmap name are empty

- pkg/deploy/kubernetes_image_puller.go
Sometimes when we create in Che Cluster the specs for KIP we don't add the configMapName and deploymentName. This is a conflict for operator because ImagePuller operator already add this values if che operator create them empty and in reconcile cheCluster expect this values to be empty always.
https://issues.redhat.com/browse/CRW-1953
> fix: [Backport] Fix image puller reconcile infinite loop when checluster image puller deployment name and configmap name are empty #877

- pkg/deploy/kubernetes_image_puller.go
Sometimes when we create in Che Cluster the specs for KIP we don't add the configMapName and deploymentName. This is a conflict for operator because ImagePuller operator already add this values if che operator create them empty and in reconcile cheCluster expect this values to be empty always.
Main fix: https://github.com/eclipse-che/che-operator/pull/877
N/A
https://issues.redhat.com/browse/CRW-1953
N/A
> fix: [Backport] Fix image puller reconcile infinite loop when checluster image puller deployment name and configmap name are empty

- deploy.sh
- deploy/cluster_role.yaml
- deploy/olm-catalog/nightly/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
- deploy/olm-catalog/nightly/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- local-debug.sh
- pkg/apis/org/conversion.go
- pkg/apis/org/conversion_test.go
- pkg/deploy/dev-workspace/dev_workspace.go
- pkg/deploy/dev-workspace/dev_workspace_test.go
This PR changes the devworkspace deployment and doesn't deploy the `CheManager` resource, which the DWCO is phasing out. This should be merged RIGHT AFTER https://github.com/che-incubator/devworkspace-che-operator/pull/49 is merged.
N/A
eclipse/che#19847
1. There is a test image of DWCO built from https://github.com/che-incubator/devworkspace-che-operator/tree/issue-19847
2. Build che-operator from this PR that sources the deployment files from the above DWCO:
```
export IMAGE="quay.io/lkrejci/che-operator:issue-19847" && docker build -t $IMAGE --build-arg=DEV_WORKSPACE_CHE_OPERATOR_VERSION=issue-19847 --no-cache . && docker push $IMAGE
```
(replace `quay.io/lkrejci/che-operator:issue-19847` with your image name or you can actually just use that image and skip this step, if you want to). …
> feat: Don't deploy CheManager - it no longer is a thing

- deploy/olm-catalog/nightly/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
- deploy/olm-catalog/nightly/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- pkg/controller/checlusterbackup/internal_backup_server.go
Do not set controller references on objects created by backup controller that are related to internal backup server in order to be able to reuse it for several backups in a row.
https://github.com/eclipse/che/issues/18703
https://github.com/eclipse/che/issues/19932
1. Schedule a backup by creating backup custom resource:
```yaml
apiVersion: org.eclipse.che/v1
kind: CheClusterBackup
metadata:
name: eclipse-che-backup
spec:
useInternalBackupServer: true
```
2. Delete created backup CR after backup successfully finishes.
3. Make sure that internal backup server resources (deployment, backup server config and secrets) are not deleted.
4. Request another backup by creating backup CR again
5. Check that new backup created. …
> fix: Do not delete internal backup server on backup CR deletion

- olm/addDigests.sh
- olm/license.txt
- olm/release-olm-files.sh
Add RELATED_IMAGES environment variables to operator.yaml on release
N/A
https://github.com/eclipse/che/issues/20005
1. `./olm/addDigests.sh -w . -s 'deploy/olm-catalog/nightly/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml' -o deploy/operator.yaml -t 7.32.0`
2. check `deploy/operator.yaml`
> feat: Add RELATED_IMAGES environment variables to operator.yaml on release

- deploy/crds/org_v1_che_crd-v1beta1.yaml
- deploy/crds/org_v1_che_crd.yaml
- deploy/olm-catalog/nightly/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
- deploy/olm-catalog/nightly/eclipse-che-preview-kubernetes/manifests/org_v1_che_crd.yaml
- deploy/olm-catalog/nightly/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- deploy/olm-catalog/nightly/eclipse-che-preview-openshift/manifests/org_v1_che_crd.yaml
- pkg/apis/org/v1/che_types.go
- pkg/controller/che/che_controller_test.go
- pkg/deploy/kubernetes_image_puller.go
- vendor/github.com/che-incubator/kubernetes-image-puller-operator/pkg/apis/che/v1alpha1/kubernetesimagepuller_types.go
This PR reads the RELATED_IMAGES environment variables ([link](https://github.com/eclipse-che/che-operator/blob/c9890991e831a8ca8f1db2a20ec066833778a52b/deploy/olm-catalog/stable/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml#L1029-L1142)) and sets images of interest to the image puller spec.
Images that correspond to images from [codeready-image-puller.yaml](https://github.com/codeready-toolchain/sandbox-sre/blob/master/resources/sandbox-stage.gb17.p1.openshiftapps.com/configure/member/crw/codeready-image-puller.yaml#L13) are chosen. As a result the theia, theia-endpoint, plugin broker, and cpp/php/golang images are chosen. Currently, 9 images are being chosen.
Thanks to this PR, when the Kubernetes image puller is installed with `--olm-channel=stable` …
> feat: set RELATED_IMAGES images to image puller spec

- .ci/cico_updates_openshift.sh
- .ci/oci-multi-host.sh
- .ci/oci-single-host.sh
- .github/bin/common.sh
Start devfile v1 when devworkspace is not enabled and start workspace v2 when devworkspace engine it is enabled
N/A
https://github.com/eclipse/che/issues/20072
N/A
> fix: Start workspace with devfilev2 when devworkspace is enabled in our e2e tests

- Dockerfile
For a proper downstreaming it is needed to download zip instead of using git clone command.
N/A
https://issues.redhat.com/browse/CRW-1956
N/A
> chore: download restic in zip format instead of using git clone

- pkg/deploy/identity-provider/deployment_keycloak.go
Sets keycloak system properties for rh-sso to fix issues with authentication errors
N/A
https://issues.redhat.com/browse/CRW-1426
N/A
> fix: setting keycloak system properties for rh-sso

- pkg/deploy/ingres_test.go
- pkg/deploy/ingress.go
Adds `nginx.org/websocket-services: che-host` annotation for che ingress
N/A
https://github.com/eclipse/che/issues/19434
N/A
> fix: adds nginx.org/websocket-services annotation for che ingress

- .github/workflows/build-catalog-and-bundle-images.yaml
Add ability to rebuild nightly OLM images manually.
N/A
https://github.com/eclipse/che/issues/19466
N/A
> feat: Add ability to rebuild OLM images manully

- pkg/deploy/gateway/gateway.go
- pkg/deploy/service.go
Reuse ServiceDefaultDiffOpts for gateway service
N/A
N/A
1. Check operator logs in PR check to ensure there is no endless reconcile loops
> fix: Reuse ServiceDefaultDiffOpts for gateway service

- .github/bin/common.sh
- .github/bin/minishift/test-operator-update.sh
- Dockerfile
- Makefile
- bundle/nightly/eclipse-che-preview-kubernetes/bundle.Dockerfile
- bundle/nightly/eclipse-che-preview-openshift/bundle.Dockerfile
- bundle/stable/eclipse-che-preview-kubernetes/bundle.Dockerfile
- bundle/stable/eclipse-che-preview-openshift/bundle.Dockerfile
Use vendor folder to speed up image build.
N/A
Part of the https://github.com/eclipse/che/issues/19466
N/A
> fix: Use vendor folder to speed up image build.

- controllers/checlusterrestore/backup_data_restorer.go
Don't ignore restore status error. I hope it will make restore feature more stable.
None. But ci fails very often. Looks like restore feature is unstable.
N/A
N/A
> fix: Don't ignore restore status error. I hope it will make restore feature more stable.

- controllers/che/checluster_controller.go
- pkg/deploy/deployment.go
- pkg/deploy/deployment_test.go
- templates/keycloak-provision.sh
- templates/keycloak-update.sh
It's a draft since some of the corner cases are not tested yet.
The purpose of this PR is adding an ability to add localhost to allow list for keycloak,
but since such kind of data is not secret, it also add a mechanism for mounting additional configmap into deployment.
It's just a copying/pasting mechanism we have for secrets, sorry about that, I did not manage to prepare the better solution in my Hack&Hustle.
it solves https://github.com/eclipse/che/issues/19158
I did the following two stories
:warning: Known limitation: Che Operator should be rescaled after configmap is created/updated/removed, since update script is executed only on Keycloak host change:
https://github.com/eclipse-che/che-operator/blob/main/pkg/deploy/identity-provider/identity_provider.go#L134
@tolusha is aware of it …
> feat: add an ability to add localhost to allows list for keycloak

- .github/bin/recovery-olm-channels.sh
- .github/workflows/recovery-index-images.yaml
Recover OLM channels for preview catalog source images.
N/A
N/A
N/A
> fix: Add OLM channels recovery script.

- olm/testUpdate.sh
Fail update tests if bundle contains only one bundle.
N/A
N/A
> fix: Fail update tests if bundle contains only one bundle.

- Makefile
This PR add two features into makefile:
1. Introduce VERBOSE mode, so we see only meaningful output by default, like makefile does not duplicate the whole commands before executing:
```
$ export VERBOSE=true
$ make debug
/home/sleshche/projects/che-operator/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
/home/sleshche/projects/che-operator/bin/controller-gen "crd:trivialVersions=true,crdVersions=v1beta1" rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases
mv """config/crd/bases"/org.eclipse.che_checlusters.yaml"" """config/crd/bases"/org_v1_che_crd-v1beta1.yaml""
mv """config/crd/bases"/org.eclipse.che_chebackupserverconfigurations.yaml"" """config/crd/bases"/org.eclipse.che_chebackupserverconfigurations_crd-v1beta1.ya …
```
> chore(debug): Improve debug UX

- controllers/che/checluster_controller_test.go
- pkg/deploy/kubernetes_image_puller.go
- pkg/util/util.go
- pkg/util/util_test.go
If the `spec.imagePuller.spec.images` contains default images, and when the CSV file updates with new default images (i.e. image with different tag), then the new default images will replace the old default images in the `spec.imagePuller.spec.images`. This PR will not add new default images; it only updates default images that already exist in `spec.imagePuller.spec.images`. 
Default images are `RELATED_IMAGE` images that match any of these patterns here: https://github.com/eclipse-che/che-operator/blob/ac0bd56e41a96d797d59414ede24509549cedcd4/pkg/deploy/kubernetes_image_puller.go#L415-L431
Image: `quay.io/dkwon17/che-operator:20081`
Updating default images in CSV file (by changing the tag from `v3.4.0` to `nightly`), updates the default …
> feat: Update image puller default images when CSV file is updated

- olm/addDigests.sh
- olm/release-olm-files.sh
Remove previous RELATED_IMAGES before adding new ones to `config/manager/manager.yaml`
N/A
https://github.com/eclipse/che/issues/20171
Run twice, make sure that content of the `config/manager/manager.yaml` is not changes after the second try.
`./olm/addDigests.sh -w . -s bundle/stable/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml -o config/manager/manager.yaml -t 7.32.0`
> fix: Remove previous RELATED_IMAGES before adding new ones

- .ci/oci-stable-all-namespaces.sh
- .gitignore
- README.md
- bundle/stable-all-namespaces/eclipse-che-preview-openshift/bundle.Dockerfile
- bundle/stable-all-namespaces/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- bundle/stable-all-namespaces/eclipse-che-preview-openshift/manifests/org.eclipse.che_chebackupserverconfigurations_crd.yaml
- bundle/stable-all-namespaces/eclipse-che-preview-openshift/manifests/org.eclipse.che_checlusterbackups_crd.yaml
- bundle/stable-all-namespaces/eclipse-che-preview-openshift/manifests/org.eclipse.che_checlusterrestores_crd.yaml
- bundle/stable-all-namespaces/eclipse-che-preview-openshift/manifests/org_v1_che_crd.yaml
- bundle/stable-all-namespaces/eclipse-che-preview-openshift/metadata/annotations.yaml
- bundle/stable-all-namespaces/eclipse-che-preview-openshift/metadata/dependencies.yaml
- bundle/stable-all-namespaces/eclipse-che-preview-openshift/tests/scorecard/config.yaml
- make-release.sh
- olm/prepare-community-operators-update.sh
- olm/release-olm-files.sh
- pkg/deploy/dev-workspace/dev_workspace.go
- pkg/deploy/dev-workspace/dev_workspace_test.go
Create a new channel to install Che Operator in AllNamespace Mode:
1. Install Che using stable-all-namespaces channel
To install Eclipse Che in cluster wide availability after uploading the new bundles for `stable-all-namespaces` we need to go to OperatorHub, select Eclipse Che and then select the new channel `stable-all-namespaces`. By default the che operator will be installed in AllNamespace mode and will start to listen for all CheCluster APIS in all cluster.
2. Migrate che from single Namespace mode to all Namespace mode
If you already have an Eclipse Che installed from stable/nightly channel and you want to try the new channel you need to consider the following:
- It is not possible to have Eclipse Che installed in single Namespace (currently the default one) and then try to install …
> feat: Add DevWorkspace as a dependency in che operator

- Dockerfile
- Makefile
- controllers/che/checluster_controller_test.go
* Remove redundant check. 
* Pass tests on image build. 
* Remove test execution on make file image build.
N/A
https://issues.redhat.com/browse/CRW-1956
N/A
> build: Remove redundant check. Pass tests on image build. Remove test execution on make file image build.

- olm/olm.sh
Use return from function instead of full exit when build catalog source.
> Use return from function instead of full exit.

- pkg/deploy/server/server_configmap.go
- pkg/deploy/server/server_configmap_test.go
Don't set public url value to internal url settings.
https://github.com/eclipse/che/issues/18643
> fix: Don't set public url value to internal url settings.

- .ci/oci-devworkspace-happy-path.sh
- .github/bin/common.sh
- .github/bin/minikube/test-olm.sh
- .github/bin/minikube/test-operator-singlehost-gateway.sh
- .github/bin/minikube/test-operator-singlehost-native.sh
- bundle/nightly/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
- bundle/nightly/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- config/rbac/cluster_role.yaml
- controllers/che/workspace_namespace_permission.go
Adds "get" and "update" roles for secrets for Che SA to be able to renew Git credential secrets etc
https://github.com/eclipse/che/issues/20212
> fix: Add "get" and "update" roles for secrets for Che SA;

- bundle/next/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
- bundle/next/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- config/rbac/cluster_role.yaml
- config/rbac/role.yaml
- controllers/che/checluster_controller.go
- controllers/che/workspace_namespace_permission.go
- controllers/checlusterrestore/backup_data_restorer.go
- pkg/deploy/expose/expose.go
- pkg/deploy/ingres_test.go
- pkg/deploy/ingress.go
- pkg/deploy/server/server.go
- pkg/deploy/tls.go
Generates networking.k8s.io/v1 version of Ingress
N/A
https://github.com/eclipse/che/issues/20182
N/A
> chore: generate networking.k8s.io/v1 version of Ingress

- bundle/next/eclipse-che-preview-openshift/bundle.Dockerfile
- olm/release-olm-files.sh
Limit new all-namespaces-stable channel to OpenShift 4.8+
see docs: 
https://redhat-connect.gitbook.io/certified-operator-guide/ocp-deployment/operator-metadata/bundle-directory/managing-openshift-versions
N/A
https://github.com/eclipse/che/issues/20234
N/A
> chore: Limit new all-namespaces-stable channel to OpenShift 4.8+

- controllers/che/checluster_controller.go
- controllers/checlusterrestore/backup_data_restorer.go
- controllers/checlusterrestore/checlusterrestore_controller.go
- controllers/checlusterrestore/restore_context.go
- pkg/util/util.go
* fix problem with removing CheCluster custom resource several time
* fix problem when restore is triggered twice
N/A
N/A
N/A
> fix: improve restore stability

- pkg/deploy/sync.go
Set `GroupVersionKind` to object after getting it from a cluster
```
level=info msg="Recreating existing object: v1.Service, name: devworkspace-controller-manager-service"
```
https://github.com/eclipse/che/issues/20278
N/A
> fix: Set `GroupVersionKind` to object after getting it from a cluster

- controllers/che/checluster_controller.go
I think after some refactoring the order to deploy registries was changed.
`chectl` expect devfile registry to be deployed first.
```
✔ Devfile Registry pod bootstrap
✔ Scheduling...done
✔ Downloading images...done
✔ Starting...done
✔ Plug-in Registry pod bootstrap
✔ Scheduling...done
✔ Downloading images...done
✔ Starting...done
```
This PR restore the previous order.
N/A
N/A
N/A
> fix: Plugin registry is deployed after devfile registry

- pkg/deploy/dashboard/dashboard.go
Add missing slash to che-dashboard route
Reff issue: https://github.com/eclipse/che/issues/20318
> fix: Add missing slash to che dashboard routes/ingress

- bundle/next/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
- bundle/next/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- controllers/devworkspace/defaults/defaults.go
- pkg/deploy/defaults.go
update traefik to 2.5.0
https://github.com/eclipse/che/issues/20142
Prerequisite: use template from PR branch -> clone `https://github.com/sparkoo/che-operator/tree/gh20142-updateTraefik` and build the templates https://github.com/eclipse-che/che-operator#deploy-che-operator-with-chectl-using---installer-operator-flag. Then always deploy with these templates.
1. deploy Che with `server.serverExposureStrategy: single-host`
2. check that traefik container in gateway is 2.5.0
3. start a workspace
_
1. deploy Che with devworkspaces enabled
2. check that traefik container in gateway is 2.5.0
3. start a workspace
[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and …
> feat: update traefik to 2.5.0

- bundle/next/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
- bundle/next/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
after updating to traefik 2.5.0 with this PR https://github.com/eclipse-che/che-operator/pull/1023, we no longer need 2nd gateway env variable
https://github.com/eclipse/che/issues/20142
Prerequisite: use template from PR branch -> clone https://github.com/sparkoo/che-operator/tree/gh20142-updateTraefik and build the templates https://github.com/eclipse-che/che-operator#deploy-che-operator-with-chectl-using---installer-operator-flag. Then always deploy with these templates.
deploy Che with server.serverExposureStrategy: single-host
check that traefik container in gateway is 2.5.0
start a workspace
_
deploy Che with devworkspaces enabled
check that traefik container in gateway is 2.5.0
start a workspace
[As the author of this Pull Request I …
> chore: remove unused env

- controllers/che/checluster_controller_test.go
- pkg/deploy/dashboard/deployment_dashboard.go
- pkg/deploy/server/server.go
- pkg/util/util.go
Set Che host url in the CR status when Che server deployment is ready
https://github.com/eclipse/che/issues/20372
Install Che using OLM. 
```bash
git clone git@github.com:eclipse-che/che-operator.git
cd che-operator
git checkout setCheHostUrlInTheCRStatusWhenCheServerDeploymentIsReady
```
Edit config/manger.yaml set che-operator image: quay.io/aandriienko/che-operator:next-che-host-url
Build and push your bundle image(VSCode task "Build and push custom che-operator image: '${IMAGE_REGISTRY_HOST}/${IMAGE_REGISTRY_USER_NAME}/che-operator:next'"):
```bash
export BUNDLE_IMG="${IMAGE_REGISTRY_HOST}/${IMAGE_REGISTRY_USER_NAME}/che-operator-bundle:v0.0.1"
make bundle IMG=${BUNDLE_IMG} platform="openshift" -s
make bundle-build bundle-push -s BUNDLE_IMG=${BUNDLE_IMG} platform="openshift"
``` …
> fix: Set Che host url in the CR status when Che server deployment is ready

- olm/prepare-community-operators-update.sh
This PR prepare the community operators to have new bundles format
https://github.com/eclipse/che/issues/19244
> feat: Prepare community operators scripts to add new bundles format

- Makefile
- PROJECT
- api/v1/chebackupserverconfiguration_types.go
- api/v1/checluster_types.go
- api/v1/checlusterbackup_types.go
- api/v1/checlusterrestore_types.go
- bundle/next/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
- bundle/next/eclipse-che-preview-kubernetes/manifests/org.eclipse.che_chebackupserverconfigurations.yaml
- bundle/next/eclipse-che-preview-kubernetes/manifests/org.eclipse.che_checlusterbackups.yaml
- bundle/next/eclipse-che-preview-kubernetes/manifests/org.eclipse.che_checlusterrestores.yaml
- bundle/next/eclipse-che-preview-kubernetes/manifests/org_v1_che_crd.yaml
- bundle/next/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- bundle/next/eclipse-che-preview-openshift/manifests/org.eclipse.che_chebackupserverconfigurations.yaml
- bundle/next/eclipse-che-preview-openshift/manifests/org.eclipse.che_checlusterbackups.yaml
- bundle/next/eclipse-che-preview-openshift/manifests/org.eclipse.che_checlusterrestores.yaml
- bundle/next/eclipse-che-preview-openshift/manifests/org_v1_che_crd.yaml
- config/crd/bases/org.eclipse.che_chebackupserverconfigurations_crd-v1beta1.yaml
- config/crd/bases/org.eclipse.che_chebackupserverconfigurations_crd.yaml
- config/crd/bases/org.eclipse.che_checlusterbackups_crd-v1beta1.yaml
- config/crd/bases/org.eclipse.che_checlusterbackups_crd.yaml
- config/crd/bases/org.eclipse.che_checlusterrestores_crd-v1beta1.yaml
- config/crd/bases/org.eclipse.che_checlusterrestores_crd.yaml
- config/crd/bases/org_v1_che_crd-v1beta1.yaml
- config/crd/bases/org_v1_che_crd.yaml
- config/manifests/bases/che-operator.clusterserviceversion.yaml
> fix: Improve Che presentation on the OperatorHub ui.

- .ci/oci-devworkspace-happy-path.sh
Use up-to-date project for devworkspace happy path test.
N/A
It's a tiny piece for https://github.com/eclipse/che/issues/20385
N/A
> fix: Use up-to-date project for devworkspace happy path test

- controllers/devworkspace/solver/che_routing.go
- controllers/devworkspace/solver/che_routing_test.go
Fix kubernetes gateway rules creation to avoid traefik misconfiguration by unexisting (on K8S) plugin.
https://github.com/eclipse/che/issues/20375
Run devworkspace on minikube. Workspaces is started but there is error opening workspace by its URL and errors in the logs of the gateway pod.
Use test image `mshaposh/che-operator:nightly` fixes the situation.
> Fix devworkspaces gateway rules creation on kubernetes

- controllers/che/checluster_controller.go
Don't add intial OpenShift OAuth user if native user mode is on
N/A
https://github.com/eclipse/che/issues/20442
1. Deploy on OpenShift with devworkspace enabled
2. Check what there is additional user besides kubeadmin and you are able to log in.
> fix: don't add intial OpenShift OAuth user if native user mode is on

- pkg/deploy/kubernetes_image_puller.go
- pkg/deploy/kubernetes_image_puller_test.go
* Updates regex for java devfile registry related images to allow the `maven` part of the name to be optional.
* Updates the `devfile_registry_image`regexes to be more lenient. "Stack" images are now covered by the updated `devfile_registry_image`regexes.
The images that are collected are unchanged:
Image: [quay.io/dkwon17/che-operator:update-regexp](quay.io/dkwon17/che-operator:update-regexp)
1. Start crc and deploy 
```
$ crc start --memory=16192 --cpus=4
$ chectl server:deploy -n eclipse-che --olm-channel=stable -p openshift --che-operator-image=quay.io/dkwon17/che-operator:update-regexp
```
2. Enable the kubernetes image puller from the `eclipse-che` `CheCluster` custom resource yaml file by setting `spec.imagePuller.enable` to true and …
> fix: update regexes for KIP default images

- Dockerfile
- api/v1/checlusterbackup_types.go
- bundle/next/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
- bundle/next/eclipse-che-preview-kubernetes/manifests/org.eclipse.che_checlusterbackups.yaml
- bundle/next/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- bundle/next/eclipse-che-preview-openshift/manifests/org.eclipse.che_checlusterbackups.yaml
- config/crd/bases/org.eclipse.che_checlusterbackups_crd-v1beta1.yaml
- config/crd/bases/org.eclipse.che_checlusterbackups_crd.yaml
- controllers/che/backup.go
- controllers/che/backup_test.go
- controllers/che/checluster_controller.go
- controllers/checlusterbackup/checlusterbackup_controller.go
- go.mod
- pkg/deploy/server/server.go
- vendor/modules.txt
Makes Che Operator to create a backup of Che installation before upgrading it to newer version.
As operator cannot know when it will be replaced with a newer version, it is the newer operator that does the backup before updating Che to newer version. The backup is sent to internal backup server to have the behavior more predictable (and to not to guess in case several backup servers configured). Backup CRs are named after version to upgrade to: `backup-before-update-to-<version>` (for example: `backup-before-update-to-7-36-2`). Also, to be able to know the version of the operator needed to reastore the backup, `cheVersion` field is added to the backup CRD status.
N/A
Is a part of https://issues.redhat.com/browse/CRW-1497
1. Create a new fake version in stable channel that uses operator …
> Create backup on each update

- api/conversion.go
- controllers/devworkspace/defaults/defaults.go
- controllers/devworkspace/solver/che_routing.go
- controllers/devworkspace/solver/che_routing_test.go
- controllers/devworkspace/solver/endpoint_exposer.go
- controllers/devworkspace/solver/solver.go
- pkg/deploy/defaults.go
- pkg/deploy/expose/expose.go
- pkg/deploy/gateway/gateway.go
- pkg/deploy/server/server.go
Secures workspace services with devworkspace engine on OpenShift. 
There is a slight change in exposing logic. The ingresses/routes are not merged into one when exposing same port.
Beside that, it also always deploys with gateway on kubernetes when devworkspaces are enabled.
Nowdays, workspace service is open to the cluster. It exposes all workspace ports and communication goes directly to target container, so anyone in the cluster can access it.
This patch adds traefik container into workspace pod and narrows the service to only single port (targeting to the traefik) for all endpoints that exposes on subpath. That means that all communication that is coming to the workspace service, must go through the traefik. The traefik is configured so it checks the requests with kube-rbac-proxy (in …
> feat: secure workspace services

- pkg/deploy/dashboard/dashboard_deployment_test.go
- pkg/deploy/dashboard/deployment_dashboard.go
- pkg/deploy/server/server_deployment.go
- pkg/deploy/tls.go
This PR about provisioning internal URLs, CAs and proxy settings into dashboard.
It's for https://github.com/eclipse-che/che-dashboard/pull/348
Note that dashboard will always use public Keycloak URL, since it needs user's info endpoint, and it gets it from Che Server.
Potentially it could evaluate it for itself, but I don't think it worthes the afford since:
- it's used only on Kubernetes and we expect it be dropped once we have native auth for Kubernetes;
This is prereq for Dashboard part for https://github.com/eclipse/che/issues/20367
Http proxy and custom certs are not easy to test, so I just copied Theia solution on dashboard side and assume it works.
1. For Che Self Signed certs verification you need to test Che on minikube:
```sh
cat EOF << > /tmp/che-cluster-patch.yaml
spec:
k8s: …
```
> Provision internal URLs, CAs and proxy settings into dashboard

- pkg/deploy/gateway/gateway.go
- pkg/deploy/gateway/gateway_test.go
Makes plugin and devfile registries accessible without authentication with native auth.
https://github.com/eclipse/che/issues/20449
image: `quay.io/mvala/che-operator:gh20449-unauthRegistries`
```bash
--installer=operator \
--platform=openshift \
--che-operator-image=quay.io/mvala/che-operator:gh20449-unauthRegistries \
--workspace-engine=dev-workspace
```
1. deploy with devworkspaces and che-operator image ^
2. without prior logging into Che, open `<che-url>/plugin-registry` or `<che-url>/devfile-registry`. You should be able to access those without login.
Reviewers, …
> fix: registries accessible without auth

- controllers/checlusterbackup/backup_context.go
- controllers/checlusterbackup/internal_backup_server.go
- pkg/backup_servers/backup_servers.go
Change default internal server server configuration to use full URL to the backup server. This allows to access it from a different namespace. Such behaviour is needed for operator running in all namespaces mode.
N/A
https://issues.redhat.com/browse/CRW-1497
Try to create a backup using internal backup server in all namespaces operator mode.
> fix: internal backup server url

- controllers/devworkspace/solver/che_routing.go
- controllers/devworkspace/solver/che_routing_test.go
Signed-off-by: Max Shaposhnik <mshaposh@redhat.com>
Adds Traefic gateway container CPU & RAM request/limit resources
https://github.com/eclipse/che/issues/20520
Run devworkspace mode, check Traefic container limits.
> feat: Add Traefik gateway container CPU & RAM request/limit resources

- .github/bin/minikube/test-olm.sh
- .github/bin/minikube/test-operator-singlehost-gateway.sh
- .github/bin/minikube/test-operator-singlehost-native.sh
Don't test workspace startup for devworkspace controller due to limited resources in GitHub action
(only 2cpu).
N/A
N/A
N/A
> ci: don't test workspace startup for devworkspace controller due to limited resources

- controllers/che/backup.go
- controllers/che/checluster_controller.go
Stops creating internal backup server and store backups on updates automatically. Does it if at least one backup server configuration is present.
N/A
https://github.com/che-incubator/chectl/pull/1680
1. Deploy previous version of Che.
2. Update to a newer version
3. Only if a backup server configuration existed, a new backup was created.
> Do not automatically backup to internal backup server if it doesn't exist

- controllers/checlusterrestore/backup_data_restorer.go
Skips deleting Keycloak pod step if pod not found
N/A
N/A
Try to restore Che when delete keycloak pod manually (not later than restoring database phase).
> fix: restore process if keycloak is already deleted

- controllers/che/checluster_controller.go
Makes Che operator always create a backup on update Che version
The behavior is the following:
- if there is no backup servers configured, then internal backup server is deployed and configured and used.
- if only one backup server is configured, then it is used
- if several backup servers configured, then:
- server configuration with `che.eclipse.org/backup-before-update: true` annotation is used
- internal backup server deployed and used if no annotation found
N/A
https://issues.redhat.com/browse/CRW-1497
1. Deploy Che of a previous version
2. Update Che to a newer version
3. Check that backup object is created
[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-te …
> fix: Create backup on every Che update

- controllers/che/checluster_controller_test.go
- pkg/deploy/defaults.go
- pkg/deploy/kubernetes_image_puller.go
Image: `quay.io/dkwon17/che-operator:cr_delete`
Deleting the CheCluster CR when `spec.imagePuller.enable` is set to `true`, caused the CR to not be deleted, due to the Kubernetes Image Puller finalizer not being removed from the CR. This PR removes the finalizer and also removes the Kubernetes Image Puller Operator.
Deleting the CheCluster CR when `spec.imagePuller.enable` is set to `true`, works properly.
The Kubernetes Image Puller Operator is also deleted.
https://issues.redhat.com/browse/CRW-2256
Tested on CRC.
1. Run the following to deploy Che:
```bash
chectl server:deploy -n eclipse-che --olm-channel=stable -p openshift --che-operator-image=quay.io/dkwon17/che-operator:cr_delete
```
2. After installation, set `spec.imagePuller.enable` …
> fix: delete KIP finalizer and KIP operator on CheCluster CR delete

- controllers/checlusterrestore/backup_data_restorer.go
- controllers/checlusterrestore/checlusterrestore_controller.go
- pkg/util/util.go
Narrows list for a resource kind query to search only in current namespace
N/A
https://github.com/eclipse/che/issues/20563
Try to create a backup when several Che instances are present on a single cluster
> fix: Limit list k8s objects queries to current namespace for backup and restore

- controllers/che/checluster_controller_test.go
- pkg/deploy/pluginregistry/pluginregistry.go
- pkg/deploy/pluginregistry/pluginregistry_configmap.go
- pkg/deploy/pluginregistry/pluginregistry_test.go
Add `CHE_PLUGIN_REGISTRY_URL` environment variable into plugin registry container and configmap
N/A
https://github.com/eclipse/che/issues/20547
1. Deploy Eclipse Che
2. Check plugin registry environment, it should contain `CHE_PLUGIN_REGISTRY_URL`
> Propagate plugin registry URL to plugin registry configmap

- bundle/next-all-namespaces/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- bundle/next/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
- bundle/next/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- controllers/che/checluster_controller.go
- controllers/checlusterbackup/checlusterbackup_controller.go
- controllers/checlusterrestore/checlusterrestore_controller.go
Configure runtime controller with namespace event filter to limit cache.
N/A
https://issues.redhat.com/browse/CRW-2383
1. Create namespaces `for i in {1..500}; do oc create namespace test$i; done`
2. Deploy Eclipse Che
```bash
--platform openshift \
--che-operator-image abazko/operator:crw-2383
```
When operator deployment is created then patch it increase limits
`oc patch deployment/che-operator -p '[{"op": "replace", "path": "/spec/template/spec/containers/0/resources/limits/memory", "value":"512Mi"}]' --type=json -n eclipse-che`
Reviewers, …
> fix: configure runtime controller with namespace event filter

- controllers/checlusterbackup/backup_context.go
- controllers/checlusterbackup/backup_data_collector.go
- controllers/checlusterbackup/checlusterbackup_controller.go
- controllers/checlusterbackup/internal_backup_server.go
- controllers/checlusterrestore/backup_data_restorer.go
- controllers/checlusterrestore/checlusterrestore_controller.go
- controllers/checlusterrestore/restore_context.go
- main.go
Uses two k8s clients in backup and restore controllers: caching client and non-caching client.
N/A
A step towards https://github.com/eclipse/che/issues/20647
1. Run `chectl server:deploy --installer=operator --platform=openshift`
2. Run `chectl server:backup`
3. Run `chectl server:restore --snapshot-id=latest`
4. Check Che is ready and works
> fix: Use cached and non-cached clients in backup/restore controllers

- .vscode/tasks.json
- Makefile
- config/manager/kustomization.yaml
Fix OLM dev commands.
None. Fix dev flow.
```bash
EOF
```
> fix: Fix OLM dev commands.

- .github/bin/common.sh
Adds scripts that collects all pods logs in Che namespaces as well as most common objects yamls for integration tests.
N/A
https://github.com/eclipse/che/issues/20504
Look at attached artifacts in GH actions for integration tests.
> chore: Add logs and cluster objects collecting for tests

- controllers/che/workspace_namespace_permission.go
Signed-off-by: Igor Vinokur <ivinokur@redhat.com>
Add patch, list, update verbs to the configmap role. From the discussion [here](https://github.com/eclipse/che/issues/20749#issuecomment-970627296) it was decided to use a configmap to store theia preferences. We need to have these verbs so that che-server can create the `workspace-preferences-configamap` on namespace creation.
https://github.com/eclipse/che/issues/20622
```bash
EOF
```
[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its …
> fix: Add patch, list, update verbs to the configmap role

- controllers/che/cheobj_verifier.go
- controllers/checlusterrestore/backup_data_restorer.go
Fix for https://github.com/eclipse-che/che-operator/pull/1166 not to require `app.kubernetes.io/instance:che` label for k8s objects to trigger a reconcile
N/A
https://github.com/eclipse/che/issues/20841
1. Deploy Eclipse Che
```
--platform minikube \
--che-operator-image abazko/operator:20841
```
2. Create config map
```
kubectl create configmap ca-certs -n eclipse-che
kubectl label configmap/ca-certs  app.kubernetes.io/part-of=che.eclipse.org app.kubernetes.io/component=ca-bundle -n eclipse-che 
```
3. Check that configamp is included into ca-certs-merged
```
kubectl get configmap ca-certs-merged -n eclipse-che -o jsonpath="{.metadata.annotations}"
```     
[As the author of this Pull Request …
> fix: don't require `app.kubernetes.io/instance:che` label on k8s object to trigger a reconcile

- helmcharts/stable/README.md
- pkg/deploy/server/server.go
Fix printing url when Eclipse Che is available.
N/A
https://github.com/eclipse/che/issues/20552
N/A
> fix: printing url when Eclipse Che is available

- bundle/next-all-namespaces/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- bundle/next/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
- bundle/next/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- config/rbac/cluster_role.yaml
- controllers/che/checluster_controller_test.go
- controllers/che/workspace_namespace_permission.go
- helmcharts/next/templates/cluster_role.yaml
- pkg/deploy/role.go
Delegate 'edit' cluster role to 'che' service account
N/A
https://github.com/eclipse/che/issues/20681
N/A
> fix: delegate permissions to `get, list, watch` `pods/log` resources

- controllers/checlusterrestore/backup_data_restorer.go
- controllers/checlusterrestore/checlusterrestore_controller.go
- pkg/deploy/migration/on-reconcile-one-time-migration.go
Drop databases before restore in order to be able to deploy clean Che in case of incompatible Postgres data formats.
Do not migrate objects related to backup.
N/A
https://github.com/eclipse/che/issues/20812
> Drop databases before restore

- bundle/next-all-namespaces/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- bundle/next-all-namespaces/eclipse-che-preview-openshift/manifests/org.eclipse.che_chebackupserverconfigurations.yaml
- bundle/next-all-namespaces/eclipse-che-preview-openshift/manifests/org.eclipse.che_checlusterbackups.yaml
- bundle/next-all-namespaces/eclipse-che-preview-openshift/manifests/org.eclipse.che_checlusterrestores.yaml
- bundle/next-all-namespaces/eclipse-che-preview-openshift/manifests/org_v1_che_crd.yaml
- bundle/next/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- bundle/next/eclipse-che-preview-openshift/manifests/org.eclipse.che_chebackupserverconfigurations.yaml
- bundle/next/eclipse-che-preview-openshift/manifests/org.eclipse.che_checlusterbackups.yaml
- bundle/next/eclipse-che-preview-openshift/manifests/org.eclipse.che_checlusterrestores.yaml
- bundle/next/eclipse-che-preview-openshift/manifests/org_v1_che_crd.yaml
- config/crd/kustomization.yaml
- config/crd/patches/extralabels_in_chebackupserverconfigurations.yaml
- config/crd/patches/extralabels_in_checlusterbackups.yaml
- config/crd/patches/extralabels_in_checlusterrestores.yaml
- config/crd/patches/extralabels_in_checlusters.yaml
feat: Add extra labels to CRDS files.
Fill missed part.
```bash
EOF
```
> feat: Add extra labels to CRDS files.

- pkg/deploy/devfileregistry/devfileregistry_deployment.go
Add env variable for internal devfile registry URL
https://github.com/eclipse/che/issues/20904
Deploy che like with chectl, connect to the devfile-registry container of devfile-registry pod
check environment variable is there
```
/usr/local/apache2 $ env | grep URL
CHE_DEVFILE_IMAGES_REGISTRY_URL=
CHE_DEVFILE_REGISTRY_INTERNAL_URL=http://devfile-registry.eclipse-che.svc:8080
CHE_DEVFILE_REGISTRY_URL=https://che-eclipse-che.apps.cluster-9189.9189.sandbox549.opentlc.com/devfile-registry
/usr/local/apache2 $ 
```
Change-Id: I573fc1ce95b00e281e541526933825456add39bd …
> feat: Add devfile registry internal URL as environment variable

- pkg/deploy/rbac/workspace_permissions.go
Add `watch` permission for the user to watch devworkspaces in his namespace. Needed for websocket connection, see the issue.
https://github.com/eclipse/che/issues/20898
test image: `quay.io/mvala/che-operator:gh20898-websocket`
```
--platform minikube \
--che-operator-image quay.io/mvala/che-operator:gh20898-websocket \
--workspace-engine=dev-workspace
```
deploy on minikube. After login to dashboard, there must be no websocket connection errors and you should see messages in network communication.
Reviewers, please comment how you tested the PR …
> fix: add permission to watch devworkspaces

- controllers/checlusterbackup/backup_data_collector.go
- controllers/checlusterrestore/backup_data_restorer.go
- controllers/checlusterrestore/restore_context.go
Makes backup and restore flows work in devworkspace mode.
This does not back up / restore users' workspaces, only Che installation.
N/A
https://github.com/eclipse/che/issues/20671
https://github.com/eclipse/che-docs/pull/2121 (backup / restore part)
1. Deploy Che with devworkspace enabled
2. Create a workspace
3. Create a backup using chectl `chectl server:backup`
4. Delete the workspace or do other harm (or even delete checluster object)
5. Restore Che using `chectl server:restore --snaphot-id=latest --batch`
6. Check everything (the workspace, for example) is in place
Reviewers, please …
> Make backup / restore of Che installation work with devworkspace mode

- pkg/deploy/migration/on-reconcile-one-time-migration.go
Applys `app.kubernetes.io/part-of=che.eclipse.org` label to objects that have `app=che` legacy label to handle migration of old versions of Che
N/A
https://github.com/eclipse/che/issues/20972
1. Create a secret with `app=che` label
2. Deploy Che in the namespace
3. Ensure the secret has `app.kubernetes.io/part-of=che.eclipse.org` label
> Migrate old objects with app=che label

- pkg/deploy/postgres/postgres_deployment.go
- pkg/deploy/postgres/postgres_test.go
`RELATED_IMAGE_postgres_13_3`  env variable can actually contains PostgreSQL 13.x version (CRW case).
PR allows to use PostreSQL images for 13.x version
N/A
https://issues.redhat.com/browse/CRW-2610
N/A
> fix: Allow to use Postgre 13.x images

- .ci/cico_updates_openshift.sh
- .ci/oci-nightly-update.sh
- .github/bin/common.sh
- olm/testCatalog.sh
- olm/testUpdate.sh
Deploy stable version of Dev Workspace operator when Eclipse Che is deployed with `testCatalog.sh` or `testUpdate.sh`
N/A
https://github.com/eclipse/che/issues/20908
N/A
> Deploy stable version of Dev Workspace operator when Eclipse Che is deployed with testCatalog.sh or testUpdate.sh

- bundle/next/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- config/platforms/openshift/che-operator.clusterserviceversion-description-patch.yaml
Update che-operator description
```md
A collaborative Kubernetes-native development solution that delivers OpenShift workspaces and in-browser IDE for rapid cloud application development.
This operator installs PostgreSQL, Plugin and Devfile registries, Dashboard, Gateway and the Eclipse Che server, as well as configures all these services.
OpenShift OAuth is used directly for authentication. TLS mode is on.
Press the **Install** button, choose the channel and the upgrade strategy, and wait for the **Installed** Operator status.
When the operator is installed, create a new Custom Resource (CR) of Kind CheCluster (click the **Create New** button).
The CR spec contains all defaults. You can start using Eclipse Che when the CR status is set …
```
> chore: Update che-operator description

- DEPENDENCIES.md
- Dockerfile
- Makefile
- api/v2alpha1/zz_generated.deepcopy.go
- bundle/next/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- go.mod
- go.sum
- helmcharts/next/templates/manager.yaml
- vendor/github.com/devfile/devworkspace-operator/apis/controller/v1alpha1/zz_generated.deepcopy.go
- vendor/github.com/devfile/devworkspace-operator/pkg/config/sync.go
- vendor/github.com/devfile/devworkspace-operator/pkg/provision/sync/sync.go
- vendor/modules.txt
Updates the DevWorkspace Operator dependency to v0.12.3 in order to pick up changes from commit https://github.com/devfile/devworkspace-operator/commit/69be85cdf34d1cb7d4aafc85cdd9c8a809e27a09
This resolves an issue where the DevWorkspaceRouting reconciler, as used by the Che Operator, can panic due to the internal config structure used by DWO not being set up.
N/A
No issue created (yet)
Changes from this PR are built into quay.io/amisevsk/che-operator:dwo-0.12.3
- [N/A] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [N/A] [Relevant user documentation …
> chore: Update DevWorkspace Operator dependency to v0.12.3

- bundle/next/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- controllers/devworkspace/solver/che_routing.go
- controllers/devworkspace/solver/che_routing_test.go
Modify how traefik routers are generated for the `/healthz` endpoint in the main gateway config. Rather than using routers `[workspaceID, <port>-healthz]` for each workspace, use `[workspaceID, workspaceID-<port>-healthz]`
This resolves an issue where multiple DevWorkspaces attempt to contribute e.g. a router named `3100-healthz`, causing the gateway to ignore all but the first on it encounters:
```log
time="2022-02-02T19:21:44Z" level=warning msg="HTTP router already configured, skipping" providerName=file filename=workspaced3a8bb14a78849fc.yml routerName=3100-healthz
```
The result of the warning above is that `/healthz` checks from DWO hit authorization, and the issue resolved by https://github.com/eclipse-che/che-operator/pull/1119 is back.
N/A
Closes …
> fix: Use different traefik router names for each healthz router

- pkg/deploy/server/server_configmap.go
Disable HTTP2 protocol
N/A
https://issues.redhat.com/browse/CRW-2677
1. Create `eclipse-che` namespace
2. Create 2 configmaps with the following lables:
```yaml
labels:
app.kubernetes.io/component: ca-bundle
app.kubernetes.io/instance: codeready
app.kubernetes.io/part-of: che.eclipse.org
config.openshift.io/inject-trusted-cabundle: 'true'
```
3. Deploy Eclipse Che with che-server engine
4. Create a workspace
> fix: Disable HTTP2 protocol

- pkg/deploy/gateway/gateway.go
- pkg/deploy/gateway/gateway_test.go
- pkg/deploy/gateway/oauth_proxy.go
Propagate proxy config into oauth-proxy sidecar container
N/A
https://github.com/eclipse/che/issues/21088
1. launch openshift cluster behind proxy
2. deploy Eclipse Che
```bash
--platform openshift \
--che-operator-image abazko/operator:21088
```
> fix: Propagate proxy config into oauth-proxy sidecar container

- .ci/oci-devworkspace-happy-path.sh
- .ci/oci-nightly-update.sh
- .ci/oci-proxy.sh
- .github/bin/common.sh
- .github/bin/minikube/test-operator.sh
- .github/bin/minikube/test-upgrade-from-stable-to-next.sh
- .github/bin/minikube/test-upgrade-from-stable-to-stable.sh
> fix: test scripts

- pkg/deploy/tls/tls_utils.go
Add timeout for http client
N/A
https://github.com/eclipse/che/issues/21087
N/A
> fix: Add timeout for http client

- pkg/deploy/server/server_configmap.go
fix:  Disable HTTP2 protocol
N/A
https://issues.redhat.com/browse/CRW-2677
1. Create `eclipse-che` namespace
2. Create 2 configmaps with the following lables:
```yaml
labels:
app.kubernetes.io/component: ca-bundle
app.kubernetes.io/instance: codeready
app.kubernetes.io/part-of: che.eclipse.org
config.openshift.io/inject-trusted-cabundle: 'true'
```
3. Deploy Eclipse Che with che-server engine
4. Create a workspac
> fix:  Disable HTTP2 protocol

- pkg/deploy/dashboard/dashboard.go
- pkg/deploy/dashboard/dashboard_test.go
Syncs dashboard cluster role and cluster role binding on OpenShift clusters
Related to https://github.com/eclipse/che/issues/21035
1. Deploy on CRC with this command:
```bash
--platform crc \
--che-operator-image quay.io/dkwon17/che-operator:dashboardsa
```
2. Verify that the dashboard cluster role and cluster role binding exists:
```
oc get clusterrole | grep dashboard
oc get clusterrolebinding | grep dashboard
```
> fix: bind dashboard cluster role to dashboard SA for OpenShift clusters

- DEPENDENCIES.md
- bundle/next/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- go.mod
- go.sum
- helmcharts/next/templates/manager.yaml
- vendor/github.com/devfile/devworkspace-operator/apis/controller/v1alpha1/devworkspaceoperatorconfig_types.go
- vendor/github.com/devfile/devworkspace-operator/apis/controller/v1alpha1/zz_generated.deepcopy.go
- vendor/github.com/devfile/devworkspace-operator/pkg/constants/constants.go
- vendor/github.com/devfile/devworkspace-operator/pkg/constants/metadata.go
- vendor/modules.txt
Bump the DevWorkspace Operator dependency to the latest release (`v0.13.0`). Since v0.12.3, no changes are made in the library that impact the Che Operator.
N/A
regular chore
```bash
EOF
```
> chore: Bump DevWorkspace Operator dependency to v0.13.0

- pkg/deploy/dashboard/dashboard.go
- pkg/deploy/gateway/gateway.go
- pkg/deploy/gateway/gateway_test.go
- pkg/deploy/gateway/oauth_proxy.go
Allow loading preload page without authorization.
fixes https://github.com/eclipse/che/issues/20463
Can be tested by following these steps: https://github.com/eclipse-che/che-operator#deploy-che-operator-with-chectl-using---installer-operator-flag
It could be tested with platform minikube and this che-operator image: **docker.io/olexii4dockerid/che-operator:next**.
1. Deploy Che.
Example:
```bash
--installer=operator \
--platform=minikube \
--che-operator-cr-patch-yaml=./custom-che-server.yaml \
--che-operator-image=docker.io/olexii4dockerid/che-operator:next
```
File **custom-che-server.yaml**
```
spec:
server:
dashboardImage: quay.io/eclipse/che-dashboard:pr-501
```
2. Try to accept factory with URL without being logged in, like …
> Allow loading preload page without authorization

- controllers/usernamespace/controller.go
- controllers/usernamespace/namespacecache.go
- controllers/usernamespace/namespacecache_test.go
Use the app.kubernetes.io/part-of=che.eclipse.org and app.kubernetes.io/component=workspaces-namespace labels to mark a namespace as workspace namespace.
This should bring the operator and che-server in line with how they are marking the managed namespaces.
N/A
eclipse/che#21327
1. 
```bash
--che-operator-image quay.io/lkrejci/che-operator:issue-21327
```
1. Create a workspace
1. Check that the workspace namespace has the following labels:
```
app.kubernetes.io/component: workspaces-namespace
app.kubernetes.io/part-of: che.eclipse.org
```
1. check that the namespace has been provisioned. Depending on the configuration you can see 1 or more configmaps `eclipse-che-eclipse-che-git-tls-creds`, …
> fix: Use the labels used by the che-server to recognize workspace namespaces

- controllers/usernamespace/controller.go
- controllers/usernamespace/controller_test.go
- controllers/usernamespace/namespacecache.go
- controllers/usernamespace/namespacecache_test.go
Given the fact that we only support a single `CheCluster` CR in the whole Kubernetes cluster, there is no need for complicated name-prefixing during the namespace provisioning.
This PR just shortens the name prefix of all objects created to just `che-`.
N/A
eclipse/che#21327
1. Install Che to OpenShift into the `openshift-operators` namespace.
2. Start a workspace
3. The workspace should start without errors.
> Namespace provisioning short name prefix

- controllers/usernamespace/controller.go
- controllers/usernamespace/controller_test.go
This makes sure that the git certificate is also mounted to the workspace so that the generated gitconfig points to a file that exists.
eclipse/che#21327
https://issues.redhat.com/browse/CRW-2882
1. Deploy Che and use quay.io/lkrejci/che-operator:issue-21327 as the operator image
2. Update Che installation with some git certificate
```
$ kubectl create configmap che-git-self-signed-cert --from-file=<SOME_CA.CRT_FILE> --from-literal=githost=https://over.the.rainbow -n eclipse-che
$ kubectl label configmap che-git-self-signed-cert app.kubernetes.io/part-of=che.eclipse.org -n eclipse-che
$ kubectl patch checluster devspaces --type=json -p '[{"op": "replace", "path": "/spec/server/gitSelfSignedCert", "value": true}]' -n eclipse-che
```
3. Start a workspace
4. Open a terminal in the workspace …
> The git certificate needs to be labeled as mounted to workspace.

- pkg/deploy/gateway/oauth_proxy.go
Signed-off-by: Oleksii Orel <oorel@redhat.com>
Fix OpenShift OAuth Proxy config.
We already have several [openshift/oauth-proxy](https://github.com/openshift/oauth-proxy) issues with redirection:
- [The page isn’t redirecting properly](https://github.com/openshift/oauth-proxy/issues/232) with open [PR](https://github.com/openshift/oauth-proxy/pull/234)
- [skip-provider-button seems to force final redirection url to be /](https://github.com/bitly/oauth2_proxy/issues/327) with open [PR](https://github.com/bitly/oauth2_proxy/pull/395)
These issues depend on setting ```skip-provider-button=true```. It could always redirect to ```oauth/start```. 
I suggest using ```skip-provider-button=false``` as a quick fix until oauth-proxy PRs are waiting to be merged.
fixes …
> Fix OpenShift OAuth Proxy config

- controllers/devworkspace/solver/che_routing.go
- controllers/devworkspace/solver/che_routing_test.go
Support internal endpoints
Devfile: https://gist.githubusercontent.com/l0rd/baa74d544f38c7fd358d1711dd46a071/raw/exposures-devfile.yaml
Exposed endpoints: 
https://github.com/eclipse/che/issues/21387
https://github.com/eclipse-che/che-operator/pull/1384#issuecomment-1137823573
> fix: Support internal endpoints

- controllers/devworkspace/solver/che_routing.go
- controllers/devworkspace/solver/che_routing_test.go
- pkg/deploy/gateway/traefik_config.go
- pkg/deploy/gateway/traefik_config_util.go
- pkg/deploy/gateway/traefik_config_util_test.go
Alternative PR to https://github.com/eclipse-che/che-operator/pull/1386. The main difference is that this PR uses the Errors Traefik middleware.
In this gif we see that:
1. Workspace is stopped
2. IDE page is refreshed
3. Instead of a 504 error, the user is redirected to the dashboard after 4 seconds
Part of https://github.com/eclipse/che/issues/20599. In another PR, maybe we can redirect the user to some error page provided by the dashboard.
Tested on CRC with the following:
1. Deploy
```bash
--platform crc\
--che-operator-image quay.io/dkwon17/che-operator:useerrorsmiddleware
```
2. Open the dashboard with the URL provided by the output from chectl.
3. Start a workspace, and wait until the editor opens.
4. Stop the …
> Use errors middleware to redirect on idled workspace after 4 seconds

- Makefile
- api/v2/checluster_types.go
- bundle/next/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- bundle/next/eclipse-che-preview-openshift/manifests/org.eclipse.che_checlusters.yaml
- config/crd/bases/org.eclipse.che_checlusters.yaml
- config/samples/org_v2_checluster.yaml
- controllers/che/checluster_validator.go
- deploy/deployment/kubernetes/combined.yaml
- deploy/deployment/kubernetes/objects/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
- deploy/deployment/kubernetes/org_v2_checluster.yaml
- deploy/deployment/openshift/combined.yaml
- deploy/deployment/openshift/objects/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
- deploy/deployment/openshift/org_v2_checluster.yaml
- helmcharts/next/crds/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
- helmcharts/next/templates/org_v2_checluster.yaml
- pkg/common/k8s-helper/k8s_helper.go
Set CheCluster defaults
N/A
https://github.com/eclipse/che/issues/20804
```
oc create namespace eclipse-che
oc apply -f config/crd/bases/org.eclipse.che_checlusters.yaml
oc apply -f config/samples/org_v2_checluster.yaml -n eclipse-che 
oc get checluster/eclipse-che -o yaml -n eclipse-che
```
Check defaults values are set:
```
spec:
components:
cheServer:
debug: false
logLevel: INFO
database:
credentialsSecretName: postgres-credentials
externalDb: false
postgresDb: dbche
postgresHostName: postgres
postgresPort: "5432"
pvc:
claimSize: 1Gi
metrics:
enable: true
containerRegistry: {}
devEnvironments:
defaultNamespace:
template: <username>-che
storage:
pvcStrategy: common
networking:
auth:
gateway:
configLabels:
app: che
component: …
```
> feat: CheCluster defaults

- bundle/next/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- config/rbac/cluster_role.yaml
- deploy/deployment/kubernetes/combined.yaml
- deploy/deployment/kubernetes/objects/che-operator.ClusterRole.yaml
- deploy/deployment/openshift/combined.yaml
- deploy/deployment/openshift/objects/che-operator.ClusterRole.yaml
- helmcharts/next/templates/che-operator.ClusterRole.yaml
- pkg/deploy/rbac/workspace_permissions.go
Signed-off-by: Oleksii Orel <oorel@redhat.com>
This PR added the verb "get" to the "pods/exec" section 
```
rules:
- verbs:
- create
- get
apiGroups:
- ''
resources:
- pods/exec
```
since the [client](https://github.com/eclipse-che/che-dashboard/blob/main/packages/dashboard-backend/src/devworkspace-client/services/api/kubeConfigApi.ts#L211-L223) in the [che-dashboard](https://github.com/eclipse-che/che-dashboard)  
```
...
const url = `${k8sServer}/api/v1/namespaces/${namespace}/pods/${pod}/exec?${queryStr}`;
const client = new WebSocket(url, PROTOCOLS, opts);
...
```
needs to send an HTTP GET to negotiate a WebSocket. 
```bash
EOF
--che-operator-image …
```
> fix: workspaces policies

- olm/prepare-community-operators-update.sh
fix: prepare-community-operators-update.sh
> fix: prepare-community-operators-update.sh

- make-release.sh
> fix: make-release.sh (exclude deploy folder from PR)

- make-release.sh
fix: Update RELATED_IMAGE in deployment files on release
> fix: Update RELATED_IMAGE in deployment files on release

- api/v1/checluster_types.go
- bundle/next/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- bundle/next/eclipse-che-preview-openshift/manifests/org.eclipse.che_checlusters.yaml
- config/crd/bases/org.eclipse.che_checlusters.yaml
- deploy/deployment/kubernetes/combined.yaml
- deploy/deployment/kubernetes/objects/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
- deploy/deployment/openshift/combined.yaml
- deploy/deployment/openshift/objects/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
- helmcharts/next/crds/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
Deprecate CheCluster API v1
```bash
kubectl apply -f config/samples/org_v1_checluster.yaml                                                                                                    
Warning: org.eclipse.che/v1 CheCluster is deprecated and will be removed in future releases
```
https://github.com/eclipse/che/issues/21579
N/A
> chore: Deprecate CheCluster API v1

- api/v1/checluster_types.go
- bundle/next/eclipse-che-preview-openshift/manifests/org.eclipse.che_checlusters.yaml
- bundle/stable/eclipse-che-preview-openshift/manifests/org.eclipse.che_checlusters.yaml
- config/crd/bases/org.eclipse.che_checlusters.yaml
- deploy/deployment/kubernetes/combined.yaml
- deploy/deployment/kubernetes/objects/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
- deploy/deployment/openshift/combined.yaml
- deploy/deployment/openshift/objects/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
- helmcharts/next/crds/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
- helmcharts/stable/crds/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
- pkg/common/constants/constants.go
When OpenVSX will be included in the plug-in registry
It'll require more memory to start.
With 256Mi, container is killed with OOM error
https://github.com/eclipse/che/issues/20549
Deploy che and check more memory is assigned for plug-in registry container
Change-Id: I2ae148f858550f92d64c41d6fa81af826624b377
Signed-off-by: Florent Benoit <fbenoit@redhat.com>
> feat: Increase default memory limit for plug-in registry

- Dockerfile
- Makefile
- api/v2/zz_generated.deepcopy.go
- bundle/next/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- config/kubernetes/kustomization.yaml
- config/kubernetes/patches/manager_pod_security_context.yaml
- config/manager/manager.yaml
- deploy/deployment/kubernetes/combined.yaml
- deploy/deployment/kubernetes/objects/che-operator.Deployment.yaml
- deploy/deployment/openshift/combined.yaml
- deploy/deployment/openshift/objects/che-operator.Deployment.yaml
- helmcharts/next/templates/che-operator.Deployment.yaml
- pkg/common/test/utils.go
- pkg/deploy/dashboard/deployment_dashboard.go
- pkg/deploy/deployment.go
- pkg/deploy/deployment_test.go
- pkg/deploy/dev-workspace/dev_workspace_syncer.go
- pkg/deploy/devfileregistry/devfileregistry_deployment.go
- pkg/deploy/gateway/gateway.go
- pkg/deploy/pluginregistry/pluginregistry_deployment.go
- pkg/deploy/postgres/postgres_deployment.go
- pkg/deploy/registry/registry_deployment.go
- pkg/deploy/server/server_deployment.go
Declare securityContext explicitly for all pods managed by che-operator
```yaml
securityContext:
capabilities:
drop:
- ALL
allowPrivilegeEscalation: false
runAsNonRoot: true
```
N/A
https://github.com/eclipse/che/issues/21559
N/A
> chore: declare pod securityContext explicitly

- api/checluster_conversion_from_test.go
- api/checluster_conversion_to_test.go
- api/v1/checluster_conversion_from.go
- api/v1/checluster_conversion_to.go
- api/v1/checluster_types.go
- api/v2/checluster_types.go
- bundle/next/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- bundle/next/eclipse-che-preview-openshift/manifests/org.eclipse.che_checlusters.yaml
- config/crd/bases/org.eclipse.che_checlusters.yaml
- deploy/deployment/kubernetes/combined.yaml
- deploy/deployment/kubernetes/objects/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
- deploy/deployment/openshift/combined.yaml
- deploy/deployment/openshift/objects/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
- helmcharts/next/crds/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
feat: Configure Open VSX registry URL
N/A
https://github.com/eclipse/che/issues/21598
N/A
> feat: Configure Open VSX registry URL

- controllers/usernamespace/controller.go
- controllers/usernamespace/controller_test.go
Use namespace API instead of project API to set `nodeSelector` and `podTolerations` annotations
N/A
https://issues.redhat.com/browse/CRW-3224
1. Deploy on OpenShift
2. Update `nodeSelector` field in CheCluster CR
3. Log in
4. Check user's namespace for `controller.devfile.io/node-selector` annotation
> fix: Use namespace API instead of project API to set nodeSelector and podTolerations annotations

- bundle/next/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- deploy/deployment/kubernetes/combined.yaml
- deploy/deployment/kubernetes/objects/che-operator.Deployment.yaml
- deploy/deployment/openshift/combined.yaml
- deploy/deployment/openshift/objects/che-operator.Deployment.yaml
- helmcharts/next/templates/che-operator.Deployment.yaml
`Remove explicitly declared runAsNonRoot: true` since it causes issues with starting che operator in OpenShift namespace labeled with `openshift.io/run-level=1` because of  https://docs.openshift.com/container-platform/4.10/authentication/managing-security-context-constraints.html
N/A
https://github.com/eclipse/che/issues/21622
N/A
> chore: Remove explicitly declared runAsNonRoot: true

- pkg/common/test/utils.go
- pkg/deploy/deployment.go
Don't set runAsNonRoot=true for Eclipse Che operands
see details https://github.com/eclipse-che/che-operator/pull/1475
N/A
https://github.com/eclipse/che/issues/21622
N/A
> fix: Don't set runAsNonRoot=true for Eclipse Che operands

- .github/workflows/build-catalog-and-bundle-images.yaml
fix: update path to buildCatalog.sh script
https://github.com/eclipse-che/che-operator/runs/7867269103?check_suite_focus=true
> fix: update path to buildCatalog.sh script

- api/v1/checluster_types.go
- api/v2/checluster_types.go
- bundle/next/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- bundle/next/eclipse-che-preview-openshift/manifests/org.eclipse.che_checlusters.yaml
- config/crd/bases/org.eclipse.che_checlusters.yaml
- deploy/deployment/kubernetes/combined.yaml
- deploy/deployment/kubernetes/objects/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
- deploy/deployment/openshift/combined.yaml
- deploy/deployment/openshift/objects/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
- helmcharts/next/crds/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
set default components container image and default editor
N/A
https://github.com/eclipse/che/issues/21554
N/A
> feat: set default components container image and default editor

- build/scripts/minikube-tests/minikube-checluster-patch.yaml
- build/scripts/minikube-tests/test-helm.sh
- build/scripts/minikube-tests/test-operator.sh
- build/scripts/minikube-tests/test-upgrade-from-stable-to-next.sh
- build/scripts/minikube-tests/test-upgrade-from-stable-to-stable.sh
- pkg/deploy/pluginregistry/pluginregistry_deployment.go
fix: Limit che resources to run minikube tests
https://github.com/eclipse/che/issues/21663
> fix: Limit che resources to run minikube tests

- build/scripts/oc-tests/oc-test-operator.sh
fix: typo in oc-test-operator.sh
> fix: typo in oc-test-operator.sh

- pkg/deploy/server/server_configmap.go
- pkg/deploy/server/server_configmap_test.go
https://github.com/eclipse/che/issues/21681
N/A
Update `CHE_WORKSPACE_PLUGIN__REGISTRY__URL` based on `externalPluginRegistry` field
N/A
> fix: Update `CHE_WORKSPACE_PLUGIN__REGISTRY__URL` based on `externalPluginRegistry` field

- bundle/next/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- controllers/che/checluster_controller.go
- pkg/common/constants/constants.go
- pkg/common/test/utils.go
- pkg/deploy/dev-workspace-config/dev_workspace_config.go
- pkg/deploy/dev-workspace-config/dev_workspace_config_test.go
- pkg/deploy/server/server_configmap.go
This PR adds a new reconciler which is in charge of creating and updating a DevWorkspace-Operator configuration (DWOC) in the che cluster namespace. 
The intention is to propagate relevant fields from the che cluster custom resource to the DWOC.
Currently, only the following (storage related) fields are propagated from the che cluster custom resource to the DWOC:
- `checluster.spec.devEnvironments.Storage.pvcStrategy`
- `checluster.spec.devEnvironments.Storage.perUserStrategyPvcConfig.ClaimSize`
- `checluster.spec.devEnvironments.Storage.perUserStrategyPvcConfig.StorageClass`
- `checluster.spec.devEnvironments.Storage.perWorkspaceStrategyPvcConfig.ClaimSize`
- `checluster.spec.devEnvironments.Storage.perWorkspaceStrategyPvcConfig.StorageClass`
The DWOC fields which can receive values from …
> feat: configure DWOC from che-operator CR

- build/scripts/release/make-release.sh
fix: path to run prepare-community-operators-update.sh script
> fix: path to run prepare-community-operators-update.sh script

- pkg/deploy/server/server_deployment.go
- pkg/deploy/server/server_deployment_test.go
Signed-off-by: Igor Vinokur <ivinokur@redhat.com>
Check the bitbucket OAuth secret for the `id` data key. Do not mount it if it is not present. The bitbucket OAuth 1 configuration doesn't  use the `id` property, but Che fails to initialise, because it tries to read the file which is not mounted from the secret.
https://issues.redhat.com/browse/CRW-3341
Configure Bitbucket Server OAuth https://www.eclipse.org/che/docs/next/administration-guide/configuring-oauth-1-for-a-bitbucket-server/
```bash
EOF
``` …
> fix: Avoid mounting bitbucket id if OAuth 1 is used

- pkg/deploy/rbac/workspace_permissions.go
chore: Add missed user roles for https://github.com/eclipse-che/che-server/pull/355
N/A
https://github.com/eclipse/che/issues/21695
N/A
> chore: Add missed user roles

- pkg/common/constants/constants.go
Signed-off-by: Valerii Svydenko <vsvydenk@redhat.com>
Since in DevSpaces we use another image to run the Plugin registry and openvsx is initializing at runtime, it's not enough 2Gi to start the pod. To fix the problem i want to increase the default memory limit for embedded openvsx registry to 4Gi.
https://issues.redhat.com/browse/CRW-3295
> chore: increase default memory limit for embedded openvsx registry

- pkg/deploy/container-build/container_build.go
Add 'use' permissions in addition to 'get' and 'update' to be added to the DevWorkspace Operator ServiceAccount when container build functionality is enabled. This is required due to changes in the DevWorkspace Operator in https://github.com/devfile/devworkspace-operator/pull/954
I merged PR https://github.com/devfile/devworkspace-operator/pull/954 forgetting that it would impact Che nightlies -- apologies. Revert PR in DWO here: https://github.com/devfile/devworkspace-operator/pull/972
N/A
N/A, required sync for changes in DWO
Verify that automatic container-build provisioning works as expected (workspaces start and can perform podman builds).
[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-che …
> Add 'use' permission for DWO SA when container build is enabled

- .github/workflows/release-next-catalog.yaml
> fix: release-nex-catalog.yaml

- pkg/deploy/rbac/workspace_permissions.go
This PR adds the `get` verb for the route object in OpenShift to allow less privileged users to `get` the details of their routes. The user can already create/delete/list the routes, but `get` is missing. This impacts some other operations as well, such as `oc apply`
N/A
https://github.com/eclipse/che/issues/21868
Test on OpenShift, ensuring the user can execute `oc get` on the routes in the workspace namespace.
> chore: Adding the 'get' verb to OpenShift route permissions

- controllers/devworkspace/solver/che_routing.go
- controllers/devworkspace/solver/che_routing_test.go
- pkg/deploy/gateway/traefik_config.go
- pkg/deploy/gateway/traefik_config_util.go
- pkg/deploy/gateway/traefik_config_util_test.go
On OpenShift, retries the connection to the workspace service if connection cannot be established. This was done with the [Retry middleware](https://doc.traefik.io/traefik/middlewares/http/retry/#:~:text=The%20Retry%20middleware%20reissues%20requests,to%20enable%20an%20exponential%20backoff.)
Confirming that the workspace not running page still appears:
https://user-images.githubusercontent.com/83611742/207145593-e086f207-ae0c-446e-b198-cfa79d2bf86f.mov
Aims to handle https://github.com/eclipse/che/issues/21796.
Unfortunately, https://github.com/eclipse/che/issues/21796 is quite hard to reproduce.
To test this PR does not break the routing on OpenShift:
1. Deploy using:
```bash
--platform openshift …
```
> Add retry middleware to retry connecting to mainurl if connection failed

- api/v2/checluster_types.go
- bundle/next/eclipse-che/manifests/che-operator.clusterserviceversion.yaml
- bundle/next/eclipse-che/manifests/org.eclipse.che_checlusters.yaml
- config/crd/bases/org.eclipse.che_checlusters.yaml
- deploy/deployment/kubernetes/combined.yaml
- deploy/deployment/kubernetes/objects/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
- deploy/deployment/openshift/combined.yaml
- deploy/deployment/openshift/objects/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
- helmcharts/next/crds/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
- pkg/common/constants/constants.go
- pkg/deploy/dev-workspace-config/dev_workspace_config.go
- pkg/deploy/dev-workspace-config/dev_workspace_config_test.go
feat: Support ephemeral pvc strategy
N/A
https://github.com/eclipse/che/issues/21885
1. `make gen-chectl-tmpl TEMPLATES=/tmp/operator-resources`
2. `chectl server:deploy -p <PLATFORM> --templates /tmp/operator-resources --che-operator-image=quay.io/abazko/operator:2188`
3. Update CheCluster CR to set `ephemeral` pvcStrategy
4. Start a workspace, devfile attributes:
```yaml
attributes:
controller.devfile.io/devworkspace-config:
name: devworkspace-config
namespace: eclipse-che
controller.devfile.io/storage-type: ephemeral
```
Reviewers, please comment how you tested the PR when approving …
> feat: Support ephemeral pvc strategy

- pkg/common/utils/utils.go
- pkg/common/utils/utils_test.go
Fixes `Whitelist` function to not cut off second-level domain
I noticed the `impaktapps.com` was whitelisted as `.com` when I helped with https://github.com/eclipse/che/issues/21886. As a quick workaround I [proposed to use three-level domain](https://github.com/eclipse/che/issues/21886#issuecomment-1356767907). Now it's time to fix the root cause.
> fix(utils): whitelist should not cut off second-level domain

- controllers/devworkspace/solver/che_routing.go
- controllers/devworkspace/solver/che_routing_test.go
fix: Display workspace idle page on k8s
N/A
https://github.com/eclipse/che/issues/21882
See the description of the issue
> fix: Display workspace idle page on k8s

- .github/workflows/codecov.yml
- .github/workflows/minikube-test-helm.yaml
- .github/workflows/minikube-test-operator.yaml
- .github/workflows/minikube-test-upgrade-stable-to-next.yaml
- .github/workflows/minikube-test-upgrade-stable-to-stable.yaml
- .github/workflows/pr-check.yml
- .github/workflows/release-che-docs.yml
- .github/workflows/release-chectl.yml
- .github/workflows/release-community-operator-PRs.yml
- .github/workflows/release-helm-charts.yaml
- .github/workflows/release-next-catalog-and-operator-image.yaml
- .github/workflows/release.yml
- .github/workflows/resources-check-main.yml
- .github/workflows/try-in-web-ide.yaml
Signed-off-by: sdawley <sdawley@redhat.com>
Update GitHub actions to use Node 16 and Ubuntu to latest
https://github.com/eclipse/che/issues/21763
Run the github actions and verify they still work
> Update GitHub actions to use Node 16 and Ubuntu to latest

- Makefile
- bundle/next/eclipse-che/manifests/che-operator.clusterserviceversion.yaml
- pkg/deploy/container-build/container_build.go
- pkg/deploy/labels.go
Set scc priority to null
N/A
https://issues.redhat.com/browse/CRW-3894
N/A
> fix: set scc priority to null

- api/v1/checluster_types.go
- api/v2/checluster_types.go
- bundle/next/eclipse-che/manifests/che-operator.clusterserviceversion.yaml
- bundle/next/eclipse-che/manifests/org.eclipse.che_checlusters.yaml
- config/crd/bases/org.eclipse.che_checlusters.yaml
- deploy/deployment/kubernetes/combined.yaml
- deploy/deployment/kubernetes/objects/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
- deploy/deployment/openshift/combined.yaml
- deploy/deployment/openshift/objects/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
- helmcharts/next/crds/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
Signed-off-by: Valerii Svydenko <vsvydenk@redhat.com>
Sets **che-incubator/che-code/latest** as a default editor
https://issues.redhat.com/browse/CRW-3568
https://issues.redhat.com/browse/CRW-3932
```bash
--che-operator-image <CUSTOM_OPERATOR_IMAGE> 
```
Check the value of **defaultEditor** it should be **che-incubator/che-code/latest**
```
devEnvironments:
defaultEditor: che-incubator/che-code/latest
```
> chore: set che-incubator/che-code/latest as a default editor

- pkg/deploy/server/server_deployment.go
- pkg/deploy/server/server_deployment_test.go
Signed-off-by: Igor Vinokur <ivinokur@redhat.com>
Add an ability to configure bitbucket-server oAuth secret for the factory flow.
https://github.com/eclipse/che/issues/21949
```bash
EOF
```
> Support Bitbucket-server oAuth2 secret config

- pkg/deploy/pluginregistry/pluginregistry_deployment.go
In case when embedded plugin registry is initializing we have to wait for the pod to be ready a bit longer. To increase time when registry pod will be ready, the number of  FailureThreshold was increased from 10 to 90.
Max value for waiting when the pod is ready is calculated:
```
InitialDelaySeconds + TimeoutSeconds + PeriodSeconds * (FailureThreshold - 1) ---> 3 + 3 + 10*(90 - 1) --> 896 seconds
```
https://issues.redhat.com/browse/CRW-4047
Deploy che with the next command:
`chectl server:deploy -p openshift --che-operator-image=vsvydenko/che-operator:fix --che-operator-cr-patch-yaml=/tmp/patch.yaml`
patch.yaml
```yaml
spec:
components:
pluginRegistry:
openVSXURL: ""
``` …
> chore: increase the number of failure threshold for embedded plugin registries

- pkg/deploy/pluginregistry/pluginregistry_deployment.go
Backport https://github.com/eclipse-che/che-operator/pull/1623 into 7.61.x
> chore: increase the number of threshold for plugin reg to 90

- pkg/deploy/pluginregistry/pluginregistry_deployment.go
Increase the number of times that the liveness probe is allowed to fail (failureThreshold) in plugin-registry deployment. It's only if the embedded plugin registry is activated.
The value was changed from 10 to 30.
https://issues.redhat.com/browse/CRW-4047
Deploy che with the next command:
`chectl server:deploy -p openshift --che-operator-image=vsvydenko/che-operator:fix --che-operator-cr-patch-yaml=/tmp/patch.yaml`
patch.yaml
```yaml
spec:
components:
pluginRegistry:
openVSXURL: ""
deployment:
containers:
- image: quay.io/devspaces/pluginregistry-rhel8:3.5
```
Reviewers, please comment …
> chore: increase failureThreshold for a liveness probe in plugin reg deployment

- build/scripts/oc-tests/oc-test-happy-path.sh
According to task  #[22043](https://github.com/eclipse/che/pull/22043) test scripts were updated, necessary changes added to this repository.
PR: [#22052](https://github.com/eclipse/che/pull/22052)
The old npm script "test-empty-workspace-devworkspace-happy-path-code" runs one test spec file - "EmptyWorkspace.spec.ts" from the test [directory](https://github.com/eclipse/che/tree/main/tests/e2e/tests/devfiles/che-code) and uses hard-coded mocha config.
It was replaced with "test-all-devfiles" which uses new dynamic mocha config and will run the same file if variable "USERSTORY=EmptyWorkspace" or all test specs in the test directory if variable not set. 
N/A
Run happy-pass PR check.
[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING …
> Updated oc-test-happy-path.sh according to new test scripts in "Che" project

- api/v1/checluster_types.go
- bundle/next/eclipse-che/manifests/che-operator.clusterserviceversion.yaml
- bundle/next/eclipse-che/manifests/org.eclipse.che_checlusters.yaml
- config/crd/bases/org.eclipse.che_checlusters.yaml
- config/manager/manager.yaml
- deploy/deployment/kubernetes/combined.yaml
- deploy/deployment/kubernetes/objects/che-operator.Deployment.yaml
- deploy/deployment/kubernetes/objects/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
- deploy/deployment/openshift/combined.yaml
- deploy/deployment/openshift/objects/che-operator.Deployment.yaml
- deploy/deployment/openshift/objects/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
- helmcharts/next/crds/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
- helmcharts/next/templates/che-operator.Deployment.yaml
- pkg/deploy/dashboard/dashboard_deployment_test.go
Replaces UDI:ubi8-38da5c2 with UDI:ubi8-latest to have latest changes form the universal developer image (UDI) in the default componen.
Updates **workspaceDefaultComponents** to use `quay.io/devfile/universal-developer-image:ubi8-latest` image
https://github.com/eclipse/che/issues/21979
- go into the branch with current changes
- `make gen-chectl-tmpl TEMPLATES=`/tmp/templates/`
- `chectl server:deploy -p minikube --che-operator-image=vsvydenko/che-operator:udi-latest --templates=/tmp/templates/`
- open dashboard and start empty workspace, it should contain default component with quay.io/devfile/universal-developer-image:ubi8-latest image (as shown in the screenshot)
[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-reque …
> chore:use UDI with ubi8-latest tag in the default component

- api/v2/checluster_types.go
- bundle/next/eclipse-che/manifests/che-operator.clusterserviceversion.yaml
- bundle/next/eclipse-che/manifests/org.eclipse.che_checlusters.yaml
- config/crd/bases/org.eclipse.che_checlusters.yaml
- deploy/deployment/kubernetes/combined.yaml
- deploy/deployment/kubernetes/objects/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
- deploy/deployment/openshift/combined.yaml
- deploy/deployment/openshift/objects/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
- helmcharts/next/crds/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
- pkg/common/constants/constants.go
- pkg/deploy/dev-workspace-config/dev_workspace_config.go
- pkg/deploy/dev-workspace-config/dev_workspace_config_test.go
This PR adds a new `spec.devEnvironments.deploymentStrategy` field to the Che Cluster CR.
Changes to this field are automatically propagated to the Che-owned DWOC, which has an equivalent `config.workspace.deploymentStrategy` field. 
The `spec.devEnvironments.deploymentStrategy` field determines the Kubernetes deployment strategy used for workspace pods. The valid values for this field are `Recreate` (which is the default) and `RollingUpdate`
n/a
https://github.com/eclipse/che/issues/21974
On OpenShift, install using `./build/scripts/olm/test-catalog-from-sources.sh`. Ensure the installed version of DWO is >=0.20.0.
1. Edit the CheCluster CR and modify the `devEnvironments.deploymentStrategy` field to be `RollingUpdate`: `kubectl edit checluster eclipse-che -n eclipse-che`. Optionally, …
> feat: configure workspace deployment strategy with CheCluster CR

- README.md
- bundle/next/eclipse-che/manifests/che-operator.clusterserviceversion.yaml
- controllers/devworkspace/solver/che_routing.go
- controllers/devworkspace/solver/che_routing_test.go
- controllers/devworkspace/solver/endpoint_exposer.go
- controllers/devworkspace/solver/endpoint_strategy.go
Fixes https://github.com/eclipse/che/issues/20598
Depends on https://github.com/eclipse-che/che-server/pull/508
Before this PR, the workspace url would be something like:
```
https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/workspace13c0f27b694b4943/universal-developer-image/3100/
```
After this PR, the workspace URL becomes:
```
https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/<username>/<workspace name>/3100/
```
For public endpoints defined in the devfile ([example](https://github.com/che-incubator/quarkus-api-example/blob/992ad93649a36ef6845592c69a2650199d5a3a5d/devfile.yaml#L18-L22))
Before this PR:
```
http://workspace294df8373ccb4bda-4.apps.che-dev.x6e0.p1.openshiftapps.com/food
```
After this PR:
```
http://<username>.<workspace name>.<endpoint …
```
> Make workspace routes more user-friendly

- controllers/devworkspace/solver/che_routing_test.go
- controllers/devworkspace/solver/endpoint_strategy.go
Fixes the hostname for public endpoints urls so that the `username`, `workspace name`, and `endpoint name` are part of the subdomain.
Before this PR:
```
http://<username>.<workspace name>.<endpoint name>.apps.che-dev.x6e0.p1.openshiftapps.com/food
```
After this PR:
```
http://<username>-<workspace name>-<endpoint name>.apps.che-dev.x6e0.p1.openshiftapps.com/food
```
Related to: https://github.com/eclipse/che/issues/22267
1. Deploy:
```
--platform openshift \
--che-operator-image quay.io/dkwon17/che-operator:friendlypathupdate
```
2. Create and start a workspace with this project: https://github.com/che-incubator/quarkus-api-example
3. Confirm that there is an OpenShift route named `{DW-ID}-tools-8080-list-all-food`, where the `spec.host` is …
> Fix subdomain for public endpoint urls

- pkg/deploy/dev-workspace-config/dev_workspace_config.go
Removing the last field from a CheCluster's `devEnvironments.projectCloneContainer` results in the change not being propagated to the DevWorkspaceOperatorConfig.
Instead, if the CheCluster's field is unset, the DevWorkspaceOperatorConfig's corresponding field should also be unset.
N/A
Closes https://github.com/eclipse/che/issues/22265
1. Modify CheCluster to have 
```yaml
spec:
devEnvironments:
projectCloneContainer:
image: bad-image:does-not-exist
```
2. Verify that DevWorkspace Operator Config (`oc get dwoc devworkspace-config -n eclipse-che`) has the bad image above configured
3. Remove `.spec.devEnvironments.projectCloneContainer` field from CheCluster
4. Check that `devworkspace-config` DWOC still has image field configured …
> [fix] Remove project clone config from DevWorkspace when unset

- controllers/devworkspace/solver/che_routing.go
- controllers/devworkspace/solver/che_routing_test.go
Cherry pick https://github.com/eclipse-che/che-operator/pull/1709 to 7.67.x
> [Backport] fix: higher routing path match priority for longer pathnames

- build/scripts/minikube-tests/test-upgrade-from-stable-to-next.sh
- build/scripts/minikube-tests/test-upgrade-from-stable-to-stable.sh
This PR reworks `test-upgrade-from-stalbe-to-next.sh` and `test-upgrade-from-stalbe-to-stable.sh` tests to avoid bumping into `System.IO.IOException: No space left on device` error, see details at https://github.com/eclipse-che/che-operator/actions/runs/5452140462?pr=1716
N/A
N/A
N/A
> chore: Rework `test-upgrade-from-stalbe-to-next.sh` and `test-upgrade-from-stalbe-to-stable.sh` tests scripts

- Dockerfile
Change-Id:...
[CRW-4582](https://issues.redhat.com//browse/CRW-4582) FIPS support
Change-Id: Ibc152062a57cc670fafb17ba2389802906bfc64b
N/A
N/A
> CRW-4582 FIPS support

- api/v2/checluster_types.go
- bundle/next/eclipse-che/manifests/che-operator.clusterserviceversion.yaml
- bundle/next/eclipse-che/manifests/org.eclipse.che_checlusters.yaml
- config/crd/bases/org.eclipse.che_checlusters.yaml
- deploy/deployment/kubernetes/combined.yaml
- deploy/deployment/kubernetes/objects/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
- deploy/deployment/openshift/combined.yaml
- deploy/deployment/openshift/objects/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
- helmcharts/next/crds/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
chore: Configure Dashboard log level
N/A
https://github.com/eclipse/che/issues/22533
N/A
> chore: Configure Dashboard log level

- pkg/common/constants/constants.go
- pkg/deploy/server/server_configmap.go
- pkg/deploy/server/server_deployment.go
- pkg/deploy/server/server_deployment_test.go
- pkg/deploy/server/server_util.go
Allow to configure 2 github providers simultaneously
https://issues.redhat.com/browse/CRW-4840
N/A
> feat: Allow to configure 2 github providers simultaneously

- build/scripts/release/prepare-community-operators-update.sh
Operator community PR creation failed:
```
...
To https://github.com/che-incubator/community-operators-prod.git
* [new branch]          update-eclipse-che-operator-7.77.0 -> update-eclipse-che-operator-7.77.0
- Use /usr/bin/gh to generate PR from template: https://raw.githubusercontent.com/redhat-openshift-ecosystem/community-operators-prod/main/docs/pull_request_template.md
must provide `--title` and `--body` (or `--fill` or `fill-first`) when not running interactively
Usage:  gh pr create [flags]
...
```
gh command requires explicit `-f / --fill` flag, when things like title are not provided with `create` command
follow up to https://github.com/eclipse/che/issues/22646
```bash
EOF
--platform …
```
> fix: che-22646 fix community operator PR creation

- pkg/common/constants/constants.go
Removing '-Dcom.redhat.fips=false' from the default JAVA_OPTS 
In the latest Dev Spaces release the latest 6.8.1 version of k8s client is used which is FIPS compatible - https://github.com/fabric8io/kubernetes-client/issues/3582 and there is no need to disable fips via `-Dcom.redhat.fips=false` on the che-server end.
https://issues.redhat.com/browse/CRW-4592
- Provision cluster with FIPS enabled (the easiest way to do it is via clusterbot `launch 4.13 azure,fips`)
- Check that the FIPS mode is enabled on the cluster via `oc get cm cluster-config-v1 -n kube-system -o json | jq -r '.data' | grep -i "fips"` command
- Install the latest version of Dev Spaces 3.9.0 / 3.9.1 and create a CR with updated JAVA_OPTS without `-Dcom.redhat.fips=false`
```
spec:
components:
cheServer:
extraProperties: …
```
> fix: Removing '-Dcom.redhat.fips=false' from the default JAVA_OPTS

- bundle/next/eclipse-che/manifests/che-operator.clusterserviceversion.yaml
- controllers/che/proxy.go
- controllers/usernamespace/controller_test.go
- pkg/deploy/proxy.go
- pkg/deploy/server/server_configmap.go
Add Kubernetes host to the no proxy list
https://issues.redhat.com/browse/CRW-5421
```bash
spec: {}
EOF
```
```bash
```
```bash
```
3. Start a workspace
4. Open a terminal and run `env | grep NO_PROXY`
See: `172.30.0.1` is included to the no proxy env variable.
Reviewers, please comment how you tested the PR when approving …
> Add Kubernetes host to the no proxy list

- controllers/devworkspace/solver/che_routing_test.go
- controllers/devworkspace/solver/endpoint_strategy.go
Update the hostname format used for endpoints whose hostnames are too long from
```
<workspace-id>-<order>.<base-domain>
```
to
```
<workspace-id>-<endpoint-name>.<base-domain>
```
This is necessary as the iteration order through endpoints is random (iterating through Go maps is random), resulting in inconsistent numbers used for `<order>`.
Using a combination of workspace ID and endpoint name should always be valid:
* Workspace IDs are 25 characters long ([ref](https://github.com/devfile/devworkspace-operator/blob/21aaf77d61f8801fbfad940b607f2e9e420b49dd/controllers/workspace/devworkspace_controller.go#L646-L668))
* Endpoint names are restricted to max 15 characters by the Devfile API ([ref](https://devfile.io/docs/2.2.0/devfile-schema#components-container-endpoints-name))
* Endpoint …
> Update how too-long endpoint hostnames are handled

- pkg/deploy/deployment.go
- pkg/deploy/gateway/gateway.go
- pkg/deploy/gateway/gateway_test.go
- pkg/deploy/job.go
- pkg/deploy/registry/registry_deployment.go
- pkg/deploy/server/server_deployment.go
- pkg/deploy/server/server_reconciler.go
* Don't reset the number of replicas on deployment update
N/A
https://github.com/eclipse/che/issues/22067
```bash
./build/scripts/minikube-tests/test-operator-from-sources.sh
```
> feat: Don't reset the number of replicas on deployment update

- build/scripts/minikube-tests/minikube-checluster-patch.yaml
Add storage size to devfile to make tests passed
N/A
N/A
```bash
spec: {}
EOF
```
```bash
```
```bash
```
> chore: add storage size

- bundle/next/eclipse-che/manifests/che-operator.clusterserviceversion.yaml
- bundle/stable/eclipse-che/manifests/che-operator.clusterserviceversion.yaml
- config/manifests/bases/che-operator.clusterserviceversion.yaml
There are newly implemented requirements (tests became mandatory last week) that requires a change in operator annotations:
https://docs.openshift.com/container-platform/4.15/operators/operator_sdk/osdk-generating-csvs.html#osdk-csv-annotations-infra_osdk-generating-csvs (see table 3)
So I’ve replaced   
```
operators.openshift.io/infrastructure-features: '["disconnected", "proxy-aware",
"fips"]'
```
with
```
features.operators.openshift.io/disconnected: “true”
features.operators.openshift.io/fips-compliant: “true”
features.operators.openshift.io/proxy-aware: “true”
features.operators.openshift.io/tls-profiles: “true”
features.operators.openshift.io/token-auth-aws: “false” 
features.operators.openshift.io/token-auth-azure: “false” 
features.operators.openshift.io/token-auth-gcp: “false” …
```
> CRW-4824 Updating annotations for operators to meet new OpenShift requirements

- bundle/next/eclipse-che/manifests/che-operator.clusterserviceversion.yaml
- pkg/deploy/image-puller/imagepuller.go
- pkg/deploy/image-puller/imagepuller_test.go
1. Operator automatically fetches images from both devfile and plugin registries and creates KIP custom resource with those images.
2. Once operands are updated, the KIP resource will be updated as well.
N/A
https://issues.redhat.com/browse/CRW-5723
1. Install Kubernetes Image Puller operator
2. Prepare a patch file:
```bash
spec:
components:
devfileRegistry:
disableInternalRegistry: false
externalDevfileRegistries: []
imagePuller:
enable: true
spec: {}
EOF
```
3. Deploy the operator:
```bash
```
4. Check KIP custom resource
```bash
$ oc get -n eclipse-che KubernetesImagePuller eclipse-che-image-puller -o …
```
> feat: Automation of the expected images to be used by ImagePuller

- .github/workflows/release.yml
- build/scripts/release/make-release.sh
ci: Support --dry-run flag for make-release.sh
> ci: Support --dry-run flag for make-release.sh

- pkg/deploy/editors-definitions/editors_definitions.go
- pkg/deploy/editors-definitions/editors_definitions_test.go
fix: RELATED_IMAGE environment name for editor definition
N/A
https://github.com/eclipse-che/che/issues/22978
```bash
spec: {}
EOF
```
```bash
```
```bash
```
> fix: RELATED_IMAGE environment name for editor definition

- .ci/openshift-ci/Dockerfile
fix: stop using mirror.centos.org repo in e2e tests
> fix: stop using mirror.centos.org repo in e2e tests

- pkg/deploy/dashboard/dashboard_deployment_test.go
- pkg/deploy/devfileregistry/devfileregistry_test.go
fix: operator tests for DS
N/A
N/A
```bash
spec: {}
EOF
```
```bash
```
```bash
```
> fix: operator tests for DS

- pkg/deploy/dashboard/dashboard_deployment_test.go
- pkg/deploy/dashboard/deployment_dashboard.go
Mount RELATED_IMAGES_sample env vars into dashboard container
N/A
https://issues.redhat.com/browse/CRW-6918
```bash
spec: {}
EOF
```
```bash
```
```bash
```
> fix: Mount RELATED_IMAGES_sample env vars into dashboard container

- api/v2/checluster_types.go
- api/v2/zz_generated.deepcopy.go
- bundle/next/eclipse-che/manifests/che-operator.clusterserviceversion.yaml
- bundle/next/eclipse-che/manifests/org.eclipse.che_checlusters.yaml
- config/crd/bases/org.eclipse.che_checlusters.yaml
- deploy/deployment/kubernetes/combined.yaml
- deploy/deployment/kubernetes/objects/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
- deploy/deployment/openshift/combined.yaml
- deploy/deployment/openshift/objects/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
- helmcharts/next/crds/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
feat: Introduce new CheCluster CR field `MaxNumberOfRunningWorkspacesPerCluster`
N/A
https://github.com/eclipse-che/che/issues/23081
```bash
spec: {}
EOF
```
```bash
```
```bash
```
> feat: Introduce new CheCluster CR field `MaxNumberOfRunningWorkspacesPerCluster`

- api/v2/zz_generated.deepcopy.go
- bundle/next/eclipse-che/manifests/che-operator.clusterserviceversion.yaml
- pkg/deploy/pluginregistry/pluginregistry_deployment.go
Since plugin registry pod provides only openvsx server, the readiness probe should check id openvsx server is available.
For that `/openvsx/api/version` is requested by readiness probe
Depends on https://github.com/redhat-developer/devspaces/pull/1099
Related to https://github.com/eclipse-che/che/issues/23074
```bash
spec:
components:
pluginRegistry:
openVSXURL: ''
deployment:
containers:
- image: quay.io/vsvydenk/pluginregistry-rhel8:46
EOF
```
```bash
```
```bash
```
2. …
> chore: change path for plugin reg readiness probe

- api/v2/checluster_types.go
- bundle/next/eclipse-che/manifests/che-operator.clusterserviceversion.yaml
- bundle/next/eclipse-che/manifests/org.eclipse.che_checlusters.yaml
- config/crd/bases/org.eclipse.che_checlusters.yaml
- deploy/deployment/kubernetes/combined.yaml
- deploy/deployment/kubernetes/objects/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
- deploy/deployment/openshift/combined.yaml
- deploy/deployment/openshift/objects/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
- helmcharts/next/crds/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
Add FailedScheduling event by default to the list of ignored unrecoverable events.
Original DWO PR (to be closed): https://github.com/devfile/devworkspace-operator/pull/1310
Related issue: https://github.com/devfile/devworkspace-operator/issues/1280
Related docs issue: https://github.com/eclipse-che/che-docs/pull/2789
```bash
spec: {}
EOF
```
2. Deploy the operator: 
```bash
```
```bash
```
1. With operator deployed and Che server started, open Che dashboard and create a workspace with exceeding …
> feat: set default ignoredUnrecoverableEvents

- controllers/devworkspace/solver/che_routing.go
- controllers/devworkspace/solver/che_routing_test.go
- controllers/devworkspace/solver/endpoint_exposer.go
- devfile.yaml
- Adds the DWR endpoint annotations as annotations for the route (on OpenShift) or ingresse (on Kubernetes) created by the Che Router for a given endpoint
There are a few additional changes made in this PR that are not meant to be merged, though they may be desirable:
- Using per-workspace storage as well as the UDI in the Che-Operator devfile. This was helpful for developing this patch in Che.
n/a
Fix eclipse-che/che#23064
1. Install DWO built from this [PR](https://github.com/devfile/devworkspace-operator/pull/1297), as well as Che-Operator built from the current PR onto your cluster. 
- On OpenShift, this can easily be done by running `./build/scripts/olm/test-catalog-from-sources.sh ` from the root of this repo.
- On minikube/kubernetes, you'll have to:
1. Build DWO: From the root of …
> Support Devfile endpoint annotations in Che Router

- README.md
Reverts https://github.com/eclipse-che/che-operator/pull/1905 which was not intended to be merged 
n/a
n/a
n/a
> Revert "Do not merge: no-op commit to test prow CI"

- api/v2/checluster_types.go
- pkg/deploy/dashboard/dashboard_deployment_test.go
- pkg/deploy/dashboard/deployment_dashboard.go
- pkg/deploy/gateway/gateway_test.go
- pkg/deploy/gateway/oauth_proxy.go
- pkg/deploy/pluginregistry/pluginregistry.go
- pkg/deploy/pluginregistry/pluginregistry_test.go
- pkg/deploy/server/server_configmap.go
- pkg/deploy/server/server_configmap_test.go
fix: Remove plugin registry pod if openVSX configured
N/A
https://issues.redhat.com/browse/CRW-7473
```bash
spec: {}
EOF
```
```bash
```
```bash
```
> fix: Remove plugin registry pod if openVSX configured

- api/v2/checluster_types.go
- pkg/deploy/dashboard/dashboard_deployment_test.go
- pkg/deploy/dashboard/deployment_dashboard.go
- pkg/deploy/gateway/gateway_test.go
- pkg/deploy/gateway/oauth_proxy.go
- pkg/deploy/pluginregistry/pluginregistry.go
- pkg/deploy/pluginregistry/pluginregistry_test.go
- pkg/deploy/server/server_configmap.go
- pkg/deploy/server/server_configmap_test.go
* fix: Remove plugin registry pod if openVSX configured
Remove plugin registry pod if openVSX configured
N/A
https://issues.redhat.com/browse/CRW-7473
```bash
spec: {}
EOF
```
```bash
```
```bash
```
> fix: Remove plugin registry pod if openVSX configured (#1913)

- controllers/devworkspace/solver/che_routing.go
- controllers/devworkspace/solver/che_routing_test.go
When using the `discoverable` attribute on a devfile endpoint, a service is created for that specific endpoint that's associated with the route/ingress. However, the current behaviour of the Che Router always associates an endpoint with the workspace's common service, rather than any endpoint-specific service. 
This PR fixes this behaviour, by ensuring the correct service is provided for each endpoint's route/ingress.
n/a
Fixes https://github.com/eclipse-che/che/issues/23061
1. Install Che using the changes from this PR by running:
- On OpenShift: `./build/scripts/olm/test-catalog-from-sources.sh `
- On Minikube: `./build/scripts/minikube-tests/test-operator-from-sources.sh`
- Alternatively, I've built a Che-Operator image from this PR and pushed it to …
> Use endpoint-specific service for discoverable endpoints

- bundle/next/eclipse-che/manifests/che-operator.clusterserviceversion.yaml
- pkg/deploy/container-build/container_build.go
- pkg/deploy/dev-workspace-config/dev_workspace_config.go
- pkg/deploy/reconcile_manager.go
* Add logger to track reconcilers invocation
* Force reconcile when devworkspaceoperatorconfig is updated
N/A
https://github.com/eclipse-che/che/issues/23167
```bash
spec: {}
EOF
```
```bash
```
```bash
```
> chore: Add logger to track reconcilers invocation

- api/v2/checluster_types.go
- bundle/next/eclipse-che/manifests/che-operator.clusterserviceversion.yaml
- bundle/next/eclipse-che/manifests/org.eclipse.che_checlusters.yaml
- config/crd/bases/org.eclipse.che_checlusters.yaml
- deploy/deployment/kubernetes/combined.yaml
- deploy/deployment/kubernetes/objects/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
- deploy/deployment/openshift/combined.yaml
- deploy/deployment/openshift/objects/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
- helmcharts/next/crds/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
Updates documentation in the CheCluster CR for `nonProxyHosts`
https://issues.redhat.com/browse/CRW-7266
1. Deploy the operator:
```bash
./build/scripts/olm/test-catalog-from-sources.sh
```
```bash
./build/scripts/minikube-tests/test-operator-from-sources.sh
```
2. Check documentation and verify that the new documentation appears:
```
$ oc explain checlusters.org.eclipse.che.spec.components.cheServer.proxy.nonProxyHosts
```
> chore: update nonProxyHosts documentation

- .github/CODEOWNERS
chore: add mkuznyetsov as codeowner
> chore: add mkuznyetsov as codeowner

- editors-definitions/che-rubymine-server-latest.yaml
- editors-definitions/che-rubymine-server-next.yaml
Adds JetBrains RubyMine IDE as an editor option to the Dashboard.
```bash
spec: {}
EOF
```
```bash
```
```bash
```
> Add RubyMine IDE

- api/v2/checluster_types.go
- bundle/next/eclipse-che/manifests/org.eclipse.che_checlusters.yaml
- config/crd/bases/org.eclipse.che_checlusters.yaml
- deploy/deployment/kubernetes/combined.yaml
- deploy/deployment/kubernetes/objects/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
- deploy/deployment/openshift/combined.yaml
- deploy/deployment/openshift/objects/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
- helmcharts/next/crds/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
This PR cherry picks the commit from this PR: https://github.com/eclipse-che/che-operator/pull/1915 to the 7.93.x branch.
> Backport update nonProxyHosts documentation

- api/v2/checluster_types.go
- bundle/next/eclipse-che/manifests/org.eclipse.che_checlusters.yaml
- config/crd/bases/org.eclipse.che_checlusters.yaml
- deploy/deployment/kubernetes/combined.yaml
- deploy/deployment/kubernetes/objects/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
- deploy/deployment/openshift/combined.yaml
- deploy/deployment/openshift/objects/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
- helmcharts/next/crds/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
This PR cherry picks the commit from this PR: https://github.com/eclipse-che/che-operator/pull/1915 to the 7.92.x branch.
For https://issues.redhat.com/browse/CRW-7266
> Backport update nonProxyHosts documentation to 7.92.x

- api/v2/checluster_types.go
- bundle/next/eclipse-che/manifests/org.eclipse.che_checlusters.yaml
- config/crd/bases/org.eclipse.che_checlusters.yaml
- deploy/deployment/kubernetes/combined.yaml
- deploy/deployment/kubernetes/objects/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
- deploy/deployment/openshift/combined.yaml
- deploy/deployment/openshift/objects/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
- helmcharts/next/crds/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
This PR cherry picks the commit from this PR: https://github.com/eclipse-che/che-operator/pull/1915 to the 7.90.x branch.
For https://issues.redhat.com/browse/CRW-7266
> Backport update nonProxyHosts documentation to 7.90.x

- pkg/deploy/dashboard/deployment_dashboard.go
Mount proxy env variables to dashboard container
N/A
https://github.com/eclipse-che/che/issues/23114
```bash
spec: {}
EOF
```
```bash
```
```bash
```
> chore: Mount proxy env variables to dashboard container

- .github/workflows/minikube-test-helm.yaml
- .github/workflows/minikube-test-operator.yaml
- .github/workflows/minikube-test-upgrade-stable-to-next.yaml
- .github/workflows/minikube-test-upgrade-stable-to-stable.yaml
- editors-definitions/che-code-server-latest.yaml
- editors-definitions/che-code-server-next.yaml
Adds new che-code-server editor that injects Visual Studio Code Command Line Interface (CLI) to the workspace, performs authentication and then creates a tunnel.
- Login
- Create tunnel to access the workspace
- Open Visual Studio Code desktop
https://github.com/eclipse-che/che/issues/23312
- create a workspace using the editor definition https://raw.githubusercontent.com/vitaliy-guliy/che-operator/refs/heads/che-code-server-editor/editors-definitions/che-code-server-next.yaml
> feat: add che-code-server editor

- api/v2/zz_generated.deepcopy.go
- controllers/usernamespace/usernamespace_controller.go
- controllers/usernamespace/usernamespace_controller_test.go
- pkg/common/constants/constants.go
- pkg/common/test/utils.go
- pkg/common/utils/utils.go
- pkg/deploy/configmap.go
- pkg/deploy/configmap_test.go
- pkg/deploy/gateway/gateway.go
- pkg/deploy/labels.go
- pkg/deploy/sync.go
- pkg/deploy/tls/certificates.go
- pkg/deploy/tls/certificates_test.go
1. Removing the `che-trusted-ca-certs` ConfigMap from user namespaces. These ConfigMaps were used to mount certificates into the /public-certs directory.
2.  The `ca-certs-merged` ConfigMap is created in the user namespace and is merged either into the `/public-certs` directory or `/etc/pki/ca-trust/extracted/pem`, depending on the value of `spec.devEnvironments.trustedCerts.disableWorkspaceCaBundleMount`
N/A
https://issues.redhat.com/browse/CRW-8316
1. Deploy a next Eclipse Che version 
```sh
chectl update next
chectl server:deploy -p openshift 
```
2. Login Eclipse Che (open dashboard)
3. Observe a size of two ConfigMaps in a user namespace (pretty big)
```sh
~ oc get configmaps -n <..> ca-certs-merged -o json | jq '.data."tls-ca-bundle.pem" | length'
238783
~ oc get configmaps -n <..> …
```
> chore: Improve mounting certs into users containers

- controllers/usernamespace/usernamespace_controller.go
- controllers/usernamespace/usernamespace_controller_test.go
- pkg/common/constants/constants.go
- pkg/common/test/utils.go
- pkg/common/utils/utils.go
- pkg/deploy/configmap.go
- pkg/deploy/configmap_test.go
- pkg/deploy/gateway/gateway.go
- pkg/deploy/labels.go
- pkg/deploy/sync.go
- pkg/deploy/tls/certificates.go
- pkg/deploy/tls/certificates_test.go
* chore: Improve mounting certs into users containers
chore: Improve mounting certs into users containers (#1980)
N/A
1. Deploy the operator:
```sh
chectl update stable
chectl server:deploy --che-operator-image=quay.io/abazko/operator:CRW-8316-7.100
```
> chore: Improve mounting certs into users containers (#1980)

- build/scripts/docker-run.sh
- bundle/next/eclipse-che/manifests/che-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- deploy/deployment/kubernetes/combined.yaml
- deploy/deployment/kubernetes/objects/che-operator.Deployment.yaml
- deploy/deployment/openshift/combined.yaml
- deploy/deployment/openshift/objects/che-operator.Deployment.yaml
- helmcharts/next/templates/che-operator.Deployment.yaml
This PR updates the default universal developer image used by Eclipse Che to ubi9-latest, replacing the deprecated ubi8-latest. It also includes improvements and  compatibility fixes `docker-run` script 
https://github.com/eclipse-che/che/issues/23321
1. Go into the branch with current changes.
2. `minikube start --disk-size=50000mb --memory=8192 --cpus=4`
3. `make gen-chectl-tmpl TEMPLATES=/tmp/templates`
4. `chectl server:deploy   -p minikube   --che-operator-image=quay.io/rh-ee-mszuc/che-operator:ubi9-update   --templates=/tmp/templates`
5. Open the Che dashboard, create an empty workspace, and verify that it is using the ubi9 image …
> chore: use udi9 as the default development image instead of udi8

- pkg/common/constants/constants.go
- pkg/deploy/container-build/container_build.go
- pkg/deploy/container-build/container_build_test.go
snc dev-workspace-container-build CRB on every reconcile loop
N/A
https://github.com/eclipse-che/che/issues/23400
```bash
spec: {}
EOF
```
```bash
```
```bash
```
> chore: sync dev-workspace-container-build CRB on every reconcile loop

- Dockerfile
Run container as non-root user 1001
N/A
https://issues.redhat.com/browse/CRW-8251
```bash
spec: {}
EOF
```
```bash
```
```bash
```
> chore: Run container as non-root user 1001

- Makefile
Fixing running debug on kubernetes/openshift
N/A
N/A
```bash
spec: {}
EOF
```
```bash
```
```bash
```
> chore: fix debug operator

- controllers/usernamespace/usernamespace_controller.go
- controllers/usernamespace/usernamespace_controller_test.go
https://github.com/eclipse-che/che/issues/23542
N/A
Reduce number of CMs created in a user namespace. A single CM `che-user-settings` will be created instead of 3.
```bash
spec: {}
EOF
```
```bash
```
```bash
```
> chore: Reduce number of CMs created in a user namespace

- README.md
Updated README to reflect the correct name of the operator.
```bash
spec: {}
EOF
```
```bash
```
```bash
```
> docs: Remove downstream naming from the usptream project
