- Dockerfile
- pkg/controller/che/che_controller.go
- pkg/controller/che/create.go
- pkg/controller/che/k8s_helpers.go
- pkg/controller/che/update.go
- pkg/util/util.go
1. A few logrus errors fixed
2. Updated Dockerfile to be using golang 1.11
3. Removed unnecessary envs from non builder image
> Fix small errors. Update Dockerfile

- .gitignore
- e2e/run-okd-tests.sh
Use double quotes to make sure car gets resolved. Add tmp to gitignore
> Fix var resolution

- pkg/deploy/defaults.go
Update default plugin registry URL since old value is no longer compatible with new wsmaster
> Update default plugin registry URL

- pkg/controller/che/k8s_helpers.go
Get test route before extracting its host.
> Improve crt retrieval

- deploy/operator.yaml
Switching to a newer quay.io/eclipse-che/che-operator image
> Update operator image in yaml

- pkg/controller/che/finalizer.go
This PR is the fix for the issue https://github.com/eclipse/che/issues/13783.
It has been tested on OpenShift 4.1 with the Che operator.
> Gracefully ignore the error when trying to delete an unexisting OAuthClient

- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1563883405/eclipse-che-preview-kubernetes.crd.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1563883405/eclipse-che-preview-kubernetes.v9.9.9-nightly.1563883405.clusterserviceversion.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/eclipse-che-preview-kubernetes.package.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1563883406/eclipse-che-preview-openshift.crd.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1563883406/eclipse-che-preview-openshift.v9.9.9-nightly.1563883406.clusterserviceversion.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/eclipse-che-preview-openshift.package.yaml
> Fix a typo in the CR of the nightly openshift CSV

- olm/README.md
- olm/docker-run.sh
> docs(olm): information for generating nightlies

- pkg/controller/che/che_controller.go
- pkg/controller/che/get.go
- pkg/controller/che/update.go
- pkg/deploy/oauthclient.go
This PR fixes a number of weirds behaviors / hard bugs happening when the `CheCluster` Custom Resource is updated.
It fixes issue https://github.com/eclipse/che/issues/14111
> Fix Custom Resource update bugs and external registry URLs not taken in account

- README.md
- cico_build_nightly.sh
- cico_functions.sh
https://github.com/eclipse/che/issues/13951
https://github.com/redhat-developer/rh-che/issues/1499
> che #13951 Adding scripts for setting up nightly CI for che-operator

- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/7.0.0/eclipse-che-preview-kubernetes.crd.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/7.0.0/eclipse-che-preview-kubernetes.v7.0.0.clusterserviceversion.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/eclipse-che-preview-kubernetes.package.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/7.0.0/eclipse-che-preview-openshift.crd.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/7.0.0/eclipse-che-preview-openshift.v7.0.0.clusterserviceversion.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/eclipse-che-preview-openshift.package.yaml
- olm/prepare-community-operators-update.sh
- pkg/deploy/defaults.go
Release 7.0.0.
Changes done during the release should be merged to `master` because they contain new OLM files and new default GO values that will be used as the new basis for future master changes.
> Release 7.0.0

- pkg/controller/che/che_controller.go
This PR fixes issue https://github.com/eclipse/che/issues/14305: Chectl starts Che components in the wrong order.
So it changes the logic of the Che operator main function to install the components in the following order, which is consistent with the way it is installed in chectl:
- Postgres DB
- Keycloak server
- Devfile Registry
- Plugin Registry
- Che server
> Reorder the steps to be consistent with chectl

- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/7.1.0/eclipse-che-preview-kubernetes.crd.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/7.1.0/eclipse-che-preview-kubernetes.v7.1.0.clusterserviceversion.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/7.1.0/eclipse-che-preview-kubernetes.v7.1.0.clusterserviceversion.yaml.diff
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/eclipse-che-preview-kubernetes.package.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/7.1.0/eclipse-che-preview-openshift.crd.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/7.1.0/eclipse-che-preview-openshift.v7.1.0.clusterserviceversion.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/7.1.0/eclipse-che-preview-openshift.v7.1.0.clusterserviceversion.yaml.diff
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/eclipse-che-preview-openshift.package.yaml
- olm/release-olm-files.sh
- pkg/deploy/defaults.go
- release-operator-code.sh
Release 7.1.0.
Changes done during the release should be merged to `master` because they contain new OLM files and new default GO values that will be used as the new basis for future master changes.
Additionally, minor fixes have been done to script files, in order to fix problems encountered during release process.
> Release 7.1.0

- deploy/keycloak_provision
- pkg/controller/che/che_controller.go
- pkg/controller/che/finalizer.go
- pkg/util/util.go
This PR fixes some remaining issues in the 1.x that had been fixed on the master branch.
Especially this one: https://issues.jboss.org/browse/CRW-365
> Fix JIRA-365

- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/7.2.0/eclipse-che-preview-kubernetes.crd.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/7.2.0/eclipse-che-preview-kubernetes.v7.2.0.clusterserviceversion.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/7.2.0/eclipse-che-preview-kubernetes.v7.2.0.clusterserviceversion.yaml.diff
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/eclipse-che-preview-kubernetes.package.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/7.2.0/eclipse-che-preview-openshift.crd.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/7.2.0/eclipse-che-preview-openshift.v7.2.0.clusterserviceversion.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/7.2.0/eclipse-che-preview-openshift.v7.2.0.clusterserviceversion.yaml.diff
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/eclipse-che-preview-openshift.package.yaml
- pkg/deploy/defaults.go
- release-operator-code.sh
Release 7.2.0.
Additionally, a minor fix has been done to a script file, in order to fix a minor issue encountered during release process.
> Release 7.2.0

- pkg/deploy/defaults.go
Change-Id:...
upgrade to SSO 7.3.4 (CRW-202)
Change-Id: Ib8ea5638ca2b1cf8c4c344950637082b5e4c639b
> upgrade to SSO 7.3.4 (CRW-202)

- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/7.3.0/eclipse-che-preview-kubernetes.crd.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/7.3.0/eclipse-che-preview-kubernetes.v7.3.0.clusterserviceversion.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/7.3.0/eclipse-che-preview-kubernetes.v7.3.0.clusterserviceversion.yaml.diff
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/eclipse-che-preview-kubernetes.package.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/7.3.0/eclipse-che-preview-openshift.crd.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/7.3.0/eclipse-che-preview-openshift.v7.3.0.clusterserviceversion.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/7.3.0/eclipse-che-preview-openshift.v7.3.0.clusterserviceversion.yaml.diff
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/eclipse-che-preview-openshift.package.yaml
- pkg/deploy/defaults.go
- pkg/deploy/defaults_test.go
- pkg/deploy/extra_images.go
> Release 7.3.0

- pkg/deploy/che_configmap.go
- pkg/deploy/defaults.go
Signed-off-by: Tom George <tg82490@gmail.com>
This fixes https://github.com/eclipse/che/issues/14985
> Patch the PVC job image when in airgap

- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1572295030/eclipse-che-preview-kubernetes.crd.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1572295030/eclipse-che-preview-kubernetes.v9.9.9-nightly.1572295030.clusterserviceversion.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1572295030/eclipse-che-preview-kubernetes.v9.9.9-nightly.1572295030.clusterserviceversion.yaml.diff
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/eclipse-che-preview-kubernetes.package.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1572295030/eclipse-che-preview-openshift.crd.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1572295030/eclipse-che-preview-openshift.v9.9.9-nightly.1572295030.clusterserviceversion.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1572295030/eclipse-che-preview-openshift.v9.9.9-nightly.1572295030.clusterserviceversion.yaml.diff
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/eclipse-che-preview-openshift.package.yaml
> Fix typo in example CR (`chePostgresHostName`)

- pkg/deploy/defaults_test.go
Signed-off-by: Tom George <tg82490@gmail.com>
The previous version of these tests depended on the already-existing image names and tags in `defaults.go`, but these can change with releases.
They have been changed to figure out what the expected images should be based on the variables in `defaults.go`
> Change tests so that they do not depend on hard coded image names

- pkg/deploy/defaults.go
Result of running `./release-operator-code.sh 7.3.1`
https://github.com/eclipse/che/issues/14947
> che #14947 changing defaults for 7.3.1 release

- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/7.3.1/eclipse-che-preview-kubernetes.crd.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/7.3.1/eclipse-che-preview-kubernetes.v7.3.1.clusterserviceversion.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/7.3.1/eclipse-che-preview-kubernetes.v7.3.1.clusterserviceversion.yaml.diff
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/eclipse-che-preview-kubernetes.package.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/7.3.1/eclipse-che-preview-openshift.crd.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/7.3.1/eclipse-che-preview-openshift.v7.3.1.clusterserviceversion.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/7.3.1/eclipse-che-preview-openshift.v7.3.1.clusterserviceversion.yaml.diff
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/eclipse-che-preview-openshift.package.yaml
- olm/prepare-community-operators-update.sh
- pkg/deploy/defaults.go
> Release 7.3.1

- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/7.4.0/eclipse-che-preview-kubernetes.crd.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/7.4.0/eclipse-che-preview-kubernetes.v7.4.0.clusterserviceversion.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/7.4.0/eclipse-che-preview-kubernetes.v7.4.0.clusterserviceversion.yaml.diff
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/eclipse-che-preview-kubernetes.package.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/7.4.0/eclipse-che-preview-openshift.crd.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/7.4.0/eclipse-che-preview-openshift.v7.4.0.clusterserviceversion.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/7.4.0/eclipse-che-preview-openshift.v7.4.0.clusterserviceversion.yaml.diff
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/eclipse-che-preview-openshift.package.yaml
- pkg/deploy/defaults.go
- pkg/deploy/extra_images.go
> Release 7.4.0

- pkg/deploy/defaults.go
- pkg/deploy/extra_images.go
> Integrate release 7.3.2 changes to `crw-2.0` branch

- pkg/util/util.go
There is fixup of downstream issue CRW-514 which has been reproduced in upstream Che.
> Order the map when converting it to a string

- deploy/cluster_role_binding.yaml
- deploy/role.yaml
- pkg/controller/che/finalizer.go
- pkg/deploy/che_service.go
- pkg/deploy/che_service_test.go
- pkg/deploy/defaults_test.go
- pkg/deploy/registry_configmap.go
> add missing license headers

- deploy/crds/org_v1_che_crd.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1578737756/eclipse-che-preview-kubernetes.crd.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1578737756/eclipse-che-preview-kubernetes.crd.yaml.diff
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1578737756/eclipse-che-preview-kubernetes.v9.9.9-nightly.1578737756.clusterserviceversion.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1578737756/eclipse-che-preview-kubernetes.v9.9.9-nightly.1578737756.clusterserviceversion.yaml.diff
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/eclipse-che-preview-kubernetes.package.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1578737756/eclipse-che-preview-openshift.crd.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1578737756/eclipse-che-preview-openshift.crd.yaml.diff
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1578737756/eclipse-che-preview-openshift.v9.9.9-nightly.1578737756.clusterserviceversion.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1578737756/eclipse-che-preview-openshift.v9.9.9-nightly.1578737756.clusterserviceversion.yaml.diff
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/eclipse-che-preview-openshift.package.yaml
- pkg/apis/org/v1/che_types.go
- pkg/apis/org/v1/zz_generated.openapi.go
Fix inconsistencies in the CRD yaml and OLM files after some changes have been done into the API without correctly synchronizing them with the yaml and OLM files.
> Fix crd inconsistencies

- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/7.7.0/eclipse-che-preview-kubernetes.crd.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/7.7.0/eclipse-che-preview-kubernetes.v7.7.0.clusterserviceversion.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/7.7.0/eclipse-che-preview-kubernetes.v7.7.0.clusterserviceversion.yaml.diff
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/eclipse-che-preview-kubernetes.package.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/7.7.0/eclipse-che-preview-openshift.crd.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/7.7.0/eclipse-che-preview-openshift.v7.7.0.clusterserviceversion.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/7.7.0/eclipse-che-preview-openshift.v7.7.0.clusterserviceversion.yaml.diff
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/eclipse-che-preview-openshift.package.yaml
- pkg/deploy/defaults.go
> Release 7.7.0

- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/7.7.1/eclipse-che-preview-kubernetes.crd.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/7.7.1/eclipse-che-preview-kubernetes.v7.7.1.clusterserviceversion.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/7.7.1/eclipse-che-preview-kubernetes.v7.7.1.clusterserviceversion.yaml.diff
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/eclipse-che-preview-kubernetes.package.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/7.7.1/eclipse-che-preview-openshift.crd.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/7.7.1/eclipse-che-preview-openshift.v7.7.1.clusterserviceversion.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/7.7.1/eclipse-che-preview-openshift.v7.7.1.clusterserviceversion.yaml.diff
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/eclipse-che-preview-openshift.package.yaml
- pkg/deploy/defaults.go
> Release 7.7.1

- e2e/run-okd-tests.sh
- e2e/tests.go
Updated the `run-okd-tests.sh` script. This script will be a part of PR check.
> Created minishift e2e tests with minishift.

- deploy/crds/org_v1_che_cr.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1580283700/eclipse-che-preview-kubernetes.crd.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1580283700/eclipse-che-preview-kubernetes.v9.9.9-nightly.1580283700.clusterserviceversion.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1580283700/eclipse-che-preview-kubernetes.v9.9.9-nightly.1580283700.clusterserviceversion.yaml.diff
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/eclipse-che-preview-kubernetes.package.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1580283700/eclipse-che-preview-openshift.crd.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1580283700/eclipse-che-preview-openshift.v9.9.9-nightly.1580283700.clusterserviceversion.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1580283700/eclipse-che-preview-openshift.v9.9.9-nightly.1580283700.clusterserviceversion.yaml.diff
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/eclipse-che-preview-openshift.package.yaml
Fix CR to use quay.io/eclipse/che-keycloak:nightly
> Fix CR to use quay.io/eclipse/che-keycloak:nightly

- .ci/cico_operator_prcheck.sh
- .ci/util/ci_common.sh
- e2e/cico_common.sh
- e2e/run-okd-tests.sh
- e2e/run_tests.sh
Created new script to install dependencies like KVM docker machine to start minishift on centos clean machine
> Create new script to install dependencies like KVM driver for minishift

- Dockerfile
- pkg/deploy/defaults.go
Change-Id:...
fix crw defaults in master
Change-Id: I4d25360545e8ff84db784d425e661b6b1b171861
> fix crw defaults in master

- olm/README.md
- olm/olm.sh
- olm/push-olm-files-to-quay.sh
- olm/testCSV.sh
- olm/testUpdate.sh
- olm/update-nightly-olm-files.sh
Improve test scripts to test che-operator installed via OLM locally
> Improve test scripts to test che-operator installed via OLM locally

- .ci/util/ci_common.sh
> Minor: Fix little typo.

- olm/update-nightly-olm-files.sh
> Fix accidentally broken script

- deploy/operator-local.yaml
Add docker images env to operator-local.yaml.
Reference issue
https://github.com/eclipse/che/issues/15874
> Add docker images env to operator-local.yaml

- deploy/operator-local.yaml
- deploy/operator.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1581975496/eclipse-che-preview-kubernetes.crd.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1581975496/eclipse-che-preview-kubernetes.v9.9.9-nightly.1581975496.clusterserviceversion.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1581975496/eclipse-che-preview-kubernetes.v9.9.9-nightly.1581975496.clusterserviceversion.yaml.diff
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/eclipse-che-preview-kubernetes.package.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1581975497/eclipse-che-preview-openshift.crd.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1581975497/eclipse-che-preview-openshift.v9.9.9-nightly.1581975497.clusterserviceversion.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1581975497/eclipse-che-preview-openshift.v9.9.9-nightly.1581975497.clusterserviceversion.yaml.diff
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/eclipse-che-preview-openshift.package.yaml
This PR:
- Fixes the wrong docker images for jwt-proxy and brokers (the CRW docker image refs were wrongly copy/pasted added instead of the upstream ones)
- Update the OLM packages according to the changes done in the `operator.yaml` file.
This PR is required to be merged into the `CHE-15974` branch, before merging `CHE-15974` to `master`.
> Che 15874 - fix wrong docker images and update olm files

- LICENSE
Issue - https://github.com/eclipse/che/issues/16104
> Adding EPL 2.0 LICENSE file

- RELEASE.md
- deploy/operator.yaml
- make-release.sh
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/7.9.0/eclipse-che-preview-kubernetes.crd.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/7.9.0/eclipse-che-preview-kubernetes.v7.9.0.clusterserviceversion.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/7.9.0/eclipse-che-preview-kubernetes.v7.9.0.clusterserviceversion.yaml.diff
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1582546871/eclipse-che-preview-kubernetes.crd.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1582546871/eclipse-che-preview-kubernetes.v9.9.9-nightly.1582546871.clusterserviceversion.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1582546871/eclipse-che-preview-kubernetes.v9.9.9-nightly.1582546871.clusterserviceversion.yaml.diff
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/eclipse-che-preview-kubernetes.package.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/7.9.0/eclipse-che-preview-openshift.crd.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/7.9.0/eclipse-che-preview-openshift.v7.9.0.clusterserviceversion.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/7.9.0/eclipse-che-preview-openshift.v7.9.0.clusterserviceversion.yaml.diff
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1582546871/eclipse-che-preview-openshift.crd.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1582546871/eclipse-che-preview-openshift.v9.9.9-nightly.1582546871.clusterserviceversion.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1582546871/eclipse-che-preview-openshift.v9.9.9-nightly.1582546871.clusterserviceversion.yaml.diff
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/eclipse-che-preview-openshift.package.yaml
> Release 7.9.0

- olm/update-cr-crd-files.sh
https://github.com/eclipse/che/issues/14782
> Add script to update cr/crd files

- .vscode/launch.json
- cmd/manager/main.go
- local-debug.sh
- pkg/controller/che/che_controller.go
- pkg/controller/che/create.go
- pkg/controller/che/get.go
- pkg/deploy/defaults.go
- pkg/util/util.go
Enable to debug operator locally
> Enable to debug operator locally

- .ci/cico_olm_prcheck.sh
- .ci/cico_operator_prcheck.sh
- .ci/util/ci_common.sh
- olm/README.md
- olm/eclipse-che-preview-kubernetes/Dockerfile
- olm/eclipse-che-preview-openshift/Dockerfile
- olm/olm.sh
- olm/testCatalogSource.sh
- olm/testUpdate.sh
This PR implement the necesary setup scrips to automate the test of OLM files and especially OLM operator:
1. Build the docker images of dedicated catalog for Openshift and Kubernetes and then run locally to test.
2. Deploy localy the operator using previous docker images created.
Reference issue
https://github.com/eclipse/che/issues/15803
> Implement OLM operator tests on PRs

- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1583510367/eclipse-che-preview-kubernetes.crd.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1583510367/eclipse-che-preview-kubernetes.v9.9.9-nightly.1583510367.clusterserviceversion.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1583510367/eclipse-che-preview-kubernetes.v9.9.9-nightly.1583510367.clusterserviceversion.yaml.diff
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/eclipse-che-preview-kubernetes.package.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1583510367/eclipse-che-preview-openshift.crd.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1583510367/eclipse-che-preview-openshift.v9.9.9-nightly.1583510367.clusterserviceversion.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1583510367/eclipse-che-preview-openshift.v9.9.9-nightly.1583510367.clusterserviceversion.yaml.diff
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/eclipse-che-preview-openshift.package.yaml
> Update nightly olm files

- deploy/crds/org_v1_che_cr.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1583509666/eclipse-che-preview-kubernetes.crd.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1583509666/eclipse-che-preview-kubernetes.v9.9.9-nightly.1583509666.clusterserviceversion.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1583509666/eclipse-che-preview-kubernetes.v9.9.9-nightly.1583509666.clusterserviceversion.yaml.diff
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/eclipse-che-preview-kubernetes.package.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1583509667/eclipse-che-preview-openshift.crd.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1583509667/eclipse-che-preview-openshift.v9.9.9-nightly.1583509667.clusterserviceversion.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1583509667/eclipse-che-preview-openshift.v9.9.9-nightly.1583509667.clusterserviceversion.yaml.diff
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/eclipse-che-preview-openshift.package.yaml
Sets `tlsSupport` field of Che CR to `true`:
```yaml
spec:
server:
tlsSupport: true
```
To set TLS support back to `false` (which is not recommended),  one need to run `chectl` with `--che-operator-cr-patch-yaml=patch.yaml` flag (create the patch file from the snippet above, but change the value to `false`).
> Set tlsSupport to true by default

- pkg/controller/che/che_controller.go
- pkg/controller/che/che_controller_test.go
Always add the devfile registry public URL env var
This fixes the [CRW-710](https://issues.redhat.com/browse/CRW-710) blocker JIRA  bug (blocking CRW 2.1 release)
> Fix CRW-710 blocker bug 

- .ci/cico_operator_prcheck.sh
- pkg/controller/che/create.go
- pkg/controller/che/k8s_helpers.go
- pkg/deploy/che_configmap.go
- pkg/deploy/deployment_keycloak.go
Correctly propagate proxy settings in the operator and Keycloak
This fixes issue https://issues.redhat.com/browse/CRW-709
> Correctly propagate proxy settings in the operator and Keycloak  (CRW-709)

- .ci/cico_operator_prcheck.sh
- pkg/controller/che/che_controller.go
- pkg/controller/che/che_controller_test.go
- pkg/controller/che/create.go
- pkg/controller/che/k8s_helpers.go
- pkg/deploy/che_configmap.go
- pkg/deploy/deployment_keycloak.go
The changes are related to CRW-709, CRW-710 issues
1.  https://github.com/eclipse/che-operator/commit/c72890d96ea63584396125412c5c689d31b03b68
2.  https://github.com/eclipse/che-operator/commit/48e367d163789d563ddec49dde7e3a437174fe4b
> Port changes from 7.9.x to master

- deploy/operator-local.yaml
- deploy/operator.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/7.9.2/eclipse-che-preview-kubernetes.crd.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/7.9.2/eclipse-che-preview-kubernetes.v7.9.2.clusterserviceversion.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/7.9.2/eclipse-che-preview-kubernetes.v7.9.2.clusterserviceversion.yaml.diff
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1584872938/eclipse-che-preview-kubernetes.crd.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1584872938/eclipse-che-preview-kubernetes.v9.9.9-nightly.1584872938.clusterserviceversion.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1584872938/eclipse-che-preview-kubernetes.v9.9.9-nightly.1584872938.clusterserviceversion.yaml.diff
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/eclipse-che-preview-kubernetes.package.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/7.9.2/eclipse-che-preview-openshift.crd.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/7.9.2/eclipse-che-preview-openshift.v7.9.2.clusterserviceversion.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/7.9.2/eclipse-che-preview-openshift.v7.9.2.clusterserviceversion.yaml.diff
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1584872938/eclipse-che-preview-openshift.crd.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1584872938/eclipse-che-preview-openshift.v9.9.9-nightly.1584872938.clusterserviceversion.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1584872938/eclipse-che-preview-openshift.v9.9.9-nightly.1584872938.clusterserviceversion.yaml.diff
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/eclipse-che-preview-openshift.package.yaml
- pkg/deploy/defaults_test.go
> Release 7.9.2

- Dockerfile
> Added support for s390x

- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1584615281/eclipse-che-preview-openshift.v9.9.9-nightly.1584615281.clusterserviceversion.yaml
https://github.com/eclipse/che/issues/16097
> Fix secret creation in the latest csv

- pkg/deploy/che_configmap.go
This fixes issue https://github.com/eclipse/che/issues/16574
> Take `WorkspaceNamespaceDefault` into account even when OpenShift OAuth is enabled

- devfile.yaml
> Add devfile.

- make-release.sh
Fix the validation of git changes
> Fix release script

- make-release.sh
Removes some unnecessary  validations.
> Update release script

- make-release.sh
> Make release script less interactive

- make-release.sh
> Fix release scrit

- deploy/operator-local.yaml
- deploy/operator.yaml
- make-release.sh
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/7.12.1/eclipse-che-preview-kubernetes.crd.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/7.12.1/eclipse-che-preview-kubernetes.v7.12.1.clusterserviceversion.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/7.12.1/eclipse-che-preview-kubernetes.v7.12.1.clusterserviceversion.yaml.diff
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1588319295/eclipse-che-preview-kubernetes.crd.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1588319295/eclipse-che-preview-kubernetes.v9.9.9-nightly.1588319295.clusterserviceversion.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1588319295/eclipse-che-preview-kubernetes.v9.9.9-nightly.1588319295.clusterserviceversion.yaml.diff
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/eclipse-che-preview-kubernetes.package.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/7.12.1/eclipse-che-preview-openshift.crd.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/7.12.1/eclipse-che-preview-openshift.v7.12.1.clusterserviceversion.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/7.12.1/eclipse-che-preview-openshift.v7.12.1.clusterserviceversion.yaml.diff
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1588319295/eclipse-che-preview-openshift.crd.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1588319295/eclipse-che-preview-openshift.v9.9.9-nightly.1588319295.clusterserviceversion.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1588319295/eclipse-che-preview-openshift.v9.9.9-nightly.1588319295.clusterserviceversion.yaml.diff
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/eclipse-che-preview-openshift.package.yaml
- pkg/deploy/defaults_test.go
> Port 7.12.1 csv to master

- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/7.12.2/eclipse-che-preview-kubernetes.crd.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/7.12.2/eclipse-che-preview-kubernetes.v7.12.2.clusterserviceversion.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/7.12.2/eclipse-che-preview-kubernetes.v7.12.2.clusterserviceversion.yaml.diff
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1588832683/eclipse-che-preview-kubernetes.crd.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1588832683/eclipse-che-preview-kubernetes.v9.9.9-nightly.1588832683.clusterserviceversion.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1588832683/eclipse-che-preview-kubernetes.v9.9.9-nightly.1588832683.clusterserviceversion.yaml.diff
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/eclipse-che-preview-kubernetes.package.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/7.12.2/eclipse-che-preview-openshift.crd.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/7.12.2/eclipse-che-preview-openshift.v7.12.2.clusterserviceversion.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/7.12.2/eclipse-che-preview-openshift.v7.12.2.clusterserviceversion.yaml.diff
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1588832683/eclipse-che-preview-openshift.crd.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1588832683/eclipse-che-preview-openshift.v9.9.9-nightly.1588832683.clusterserviceversion.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1588832683/eclipse-che-preview-openshift.v9.9.9-nightly.1588832683.clusterserviceversion.yaml.diff
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/eclipse-che-preview-openshift.package.yaml
> Copy csv files from 7.12.2 to master

- .ci/start-minikube.sh
I create this PR to change version of k8s and minikube because new olm version(0.14.1) is not compatible with old versions.
> Change k8s version and minikube

- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1588832683/eclipse-che-preview-kubernetes.v9.9.9-nightly.1588832683.clusterserviceversion.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1588832683/eclipse-che-preview-kubernetes.v9.9.9-nightly.1588832683.clusterserviceversion.yaml.diff
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1588832683/eclipse-che-preview-openshift.v9.9.9-nightly.1588832683.clusterserviceversion.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1588832683/eclipse-che-preview-openshift.v9.9.9-nightly.1588832683.clusterserviceversion.yaml.diff
> Use nightly tag for che-operator image in nightly channel

- olm/testCatalogSource.sh
This PR add the ability to collect logs from pods(che and olm pods)
> Collect logs from pods

- .ci/operator_code_check.sh
Fix CI script adding origin/master instead master for problems in Centos CI,
> Fix ci job and adding debug

- RELEASE.md
- make-release.sh
- olm/release-olm-files.sh
- olm/update-nightly-olm-files.sh
> Update release files

- RELEASE.md
- make-release.sh
> Allows not to release olm files

- .dockerignore
- Gopkg.lock
- deploy/cluster_role.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1589795199/eclipse-che-preview-kubernetes.crd.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1589795199/eclipse-che-preview-kubernetes.v9.9.9-nightly.1589795199.clusterserviceversion.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1589795199/eclipse-che-preview-kubernetes.v9.9.9-nightly.1589795199.clusterserviceversion.yaml.diff
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/eclipse-che-preview-kubernetes.package.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1589795200/eclipse-che-preview-openshift.crd.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1589795200/eclipse-che-preview-openshift.v9.9.9-nightly.1589795200.clusterserviceversion.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1589795200/eclipse-che-preview-openshift.v9.9.9-nightly.1589795200.clusterserviceversion.yaml.diff
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/eclipse-che-preview-openshift.package.yaml
- pkg/controller/che/che_controller.go
https://github.com/eclipse/che/issues/16837#issuecomment-629960961
> Back off openshift oauth, when oauth can't be used

- Dockerfile
Change-Id:...
replace case with simple if-then
Change-Id: I4663437944ec274b116a332e063b77b86b41ff95
> replace case with simple if-then

- .ci/operator_code_check.sh
[CI-SCRIPT] Fix regular expression for checking if exist modifications in `deploy` folder. Old regular expression match as well `pkg/deploy/*` folder...
Ref Job fail: https://github.com/eclipse/che-operator/pull/273
> Fix regular expression for deploy folder

- go.mod
- pkg/controller/che/che_controller.go
- pkg/controller/che/create.go
- pkg/controller/che/exec.go
- pkg/controller/che/update.go
- pkg/deploy/exec_commands.go
- templates/keycloak_provision
https://issues.redhat.com/browse/CRW-765
set sslRequired=none by updating keycloak db
> Update keycloak db to turn sslRequired to none

- pkg/controller/che/che_controller.go
- pkg/controller/che/create.go
- pkg/controller/che/exec.go
- pkg/controller/che/update.go
- pkg/deploy/exec_commands.go
- templates/keycloak_provision
This reverts commit 1a274ab172656f6334f9f0e62b6cf9df0a1af983, reversing
changes made to a0f108dcacfe1f3c93ceb1b3423a87bb59463889.
> Revert "Merge pull request #273 from eclipse/sslrequired"

- .ci/cico_updates_minikube.sh
- .ci/start-minikube.sh
- olm/olm.sh
Sometimes in centos ci we have some network issue and is necessary to increase the time to wait for eclipse che images to download or OLM as well.
> Increase time to wait for OLM and Eclipse installation

- Dockerfile
Change-Id: I91c3c6ad19000b23ce4c82200898978a2a2538f9
[base] Update from devtools/go-toolset-rhel7:1.12.12-4 to devtools/go-toolset-rhel7:1.13.4-18
Change-Id: I91c3c6ad19000b23ce4c82200898978a2a2538f9
> [base] Update from devtools/go-toolset-rhel7:1.12.12-4 to devtools/go-toolset-rhel7:1.13.4-18

- README.md
Adds instructions how to test Che operator under development in Openshift cluster using OLM installer.
> Add instructions how to test Che operator using olm installer

- pkg/deploy/defaults.go
- pkg/util/util.go
https://issues.redhat.com/browse/CRW-939
> Do not read env var specific to k8s infra

- pkg/util/util.go
- pkg/util/util_test.go
Make protocol removing correct for Java proxy opts.
> Fix protocol removing for Java proxy opts

- .ci/cico_olm_prcheck.sh
- .ci/cico_updates_minikube.sh
- .ci/cico_updates_minishift.sh
- .ci/util/ci_common.sh
- .ci/util/cr-test.yaml
This PR introduce a new script to test updates in minishift using chectl tool.
Ref: https://github.com/eclipse/che/issues/17073
> Add CI script to support updates testing in minishift

- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1594294265/eclipse-che-preview-kubernetes.crd.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1594294265/eclipse-che-preview-kubernetes.v9.9.9-nightly.1594294265.clusterserviceversion.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1594294265/eclipse-che-preview-kubernetes.v9.9.9-nightly.1594294265.clusterserviceversion.yaml.diff
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/eclipse-che-preview-kubernetes.package.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1594294265/eclipse-che-preview-openshift.crd.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1594294265/eclipse-che-preview-openshift.v9.9.9-nightly.1594294265.clusterserviceversion.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1594294265/eclipse-che-preview-openshift.v9.9.9-nightly.1594294265.clusterserviceversion.yaml.diff
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/eclipse-che-preview-openshift.package.yaml
Adding 'eclipse-che' as the suggested namespace.
- UX when "eclipse-che" namespace does not exist on the cluster: 
- UX when "eclipse-che" namespace exists on the cluster: 
This is the initial step for https://github.com/eclipse/che/issues/17187
> Adding 'eclipse-che' as the suggested namespace

- olm/buildDigestMap.sh
Reset digest before retrieving new value.
> fix: Reset digest before retrieving new value.

- olm/buildDigestMap.sh
- olm/digestExcludeList
> Exclude next images.

- pkg/deploy/devfile_registry.go
- pkg/deploy/ingress.go
- pkg/deploy/plugin_registry.go
https://coub.com/view/2gi96a
Use the default ingress strategy if there is no value in CR
> Use the default ingress strategy if there is no value in CR

- README.md
> Update doc how to test operator via OLM.

- make-release.sh
Do not update nightly OLM files during 7.16.x releases
> Do not update nightly OLM files during 7.16.x release

- olm/release-olm-files.sh
> Ensure release diffs include digests

- olm/release-olm-files.sh
> Fix diff regeneration with digests

- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1595010734/eclipse-che-preview-kubernetes.v9.9.9-nightly.1595010734.clusterserviceversion.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1595010735/eclipse-che-preview-openshift.v9.9.9-nightly.1595010735.clusterserviceversion.yaml
remove tls and self-signed certs params from cvs template
Change-Id: I7c90faaab8387fc89a459ed8673abe5be2365365
Fix for:
https://issues.redhat.com/browse/CRW-445
> CRW-445 remove tls and self-signed certs params from csv

- pkg/controller/che/che_controller.go
- pkg/controller/che/get.go
- pkg/deploy/deployment_keycloak.go
- pkg/deploy/exec_commands.go
- templates/keycloak_provision
* Allow to use external PostgreSQL
https://github.com/eclipse/che/issues/17274
> Allow to use external PostgreSQL (#371)

- Dockerfile
Adding ARM support .
Signed-off-by: Amit Ghatwal ghatwala@us.ibm.com
> Adding ARM support

- pkg/deploy/secret.go
https://github.com/eclipse/che/issues/17435
Remove secrets when checluster is removed
> Remove secrets when checluster is removed

- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1596626683/eclipse-che-preview-kubernetes.crd.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1596626683/eclipse-che-preview-kubernetes.v9.9.9-nightly.1596626683.clusterserviceversion.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1596626683/eclipse-che-preview-kubernetes.v9.9.9-nightly.1596626683.clusterserviceversion.yaml.diff
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/eclipse-che-preview-kubernetes.package.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1596626684/eclipse-che-preview-openshift.crd.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1596626684/eclipse-che-preview-openshift.v9.9.9-nightly.1596626684.clusterserviceversion.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1596626684/eclipse-che-preview-openshift.v9.9.9-nightly.1596626684.clusterserviceversion.yaml.diff
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/eclipse-che-preview-openshift.package.yaml
Remove cluster-monitoring annotation, that was removed in 7.16.2 release
> Remove cluster-monitoring annotation from nightly OLM files

- olm/addDigests.sh
https://github.com/eclipse/che/issues/17480
> Fix breaking yaml new lines in the strings.

- olm/release-olm-files.sh
Run diff generation after adding digests for each platform
> Fix diff generation during release

- olm/digestExcludeList
> Add quay.io/eclipse/che-machine-exec:nightly to digestExcludeList

- olm/olm.sh
Fix testing changes using olm on minikube
> Fix testing changes using olm on minikube

- pkg/deploy/deployment_che.go
https://github.com/eclipse/che/issues/17581
> don't set probes when debug=true

- RELEASE.md
- make-release.sh
> Add separate parameter for updating nightly OLM files during release

- deploy/operator-local.yaml
- deploy/operator.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1597916268/eclipse-che-preview-kubernetes.crd.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1597916268/eclipse-che-preview-kubernetes.v9.9.9-nightly.1597916268.clusterserviceversion.yaml
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/9.9.9-nightly.1597916268/eclipse-che-preview-kubernetes.v9.9.9-nightly.1597916268.clusterserviceversion.yaml.diff
- olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/eclipse-che-preview-kubernetes.package.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1597916268/eclipse-che-preview-openshift.crd.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1597916268/eclipse-che-preview-openshift.v9.9.9-nightly.1597916268.clusterserviceversion.yaml
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/9.9.9-nightly.1597916268/eclipse-che-preview-openshift.v9.9.9-nightly.1597916268.clusterserviceversion.yaml.diff
- olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/eclipse-che-preview-openshift.package.yaml
Updates nightly OLM files to apply new plugin broker v3.3.0
> Update nightly OLM files to use plugin broker v3.3.0

- pkg/controller/che/che_controller.go
https://issues.redhat.com/browse/CRW-1015
> Update link to point to latest doc

- make-release.sh
- replace-images-tags.sh
https://github.com/eclipse/che/issues/17603
> Make operator tag  compliant with tags on other repositories

- .ci/openshift-ci/Dockerfile
> Add httpd-tools for user creation on the openshift ci.

- pkg/deploy/che_configmap.go
https://github.com/eclipse/che/issues/17631
Improve check to put tls certificates into the che config map
> Add more checks to  tls certificates into che configmap

- pkg/deploy/tls.go
Backports https://github.com/eclipse/che-operator/pull/424 into `7.18.x` branch.
> Backport of https://github.com/eclipse/che-operator/pull/424 into 7.18.x branch

- .github/workflows/pushCatalogImages.yaml
> chore(secrets): fix credentials values

- deploy/olm-catalog/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
- deploy/olm-catalog/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- olm/incrementNightlyBundles.sh
> Fix nightly stable version part.

- .github/action_scripts/build_olm_bundle_images.sh
> Fix push nightly images script.

- deploy/olm-catalog/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
- deploy/olm-catalog/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- deploy/operator-local.yaml
- deploy/operator.yaml
- make-release.sh
- olm/update-nightly-bundle.sh
- replace-images-tags.sh
Moves images updating  to update-nightly-bundle.sh. script
> Moves images updating  to update-nightly-bundle.sh. script

- pkg/deploy/deployment_keycloak.go
Add validation for username field to be dns compatible
https://github.com/eclipse/che/issues/17827
> [CRW] Add validation for username field to be dns compatible

- Dockerfile
Change-Id:...
CVE fix: librepo
Change-Id: I56d18fbd6686a917df9bd5aef0cab8e0adf1db1a
> CVE fix: librepo

- olm/update-nightly-bundle.sh
https://github.com/eclipse/che/issues/17922
> Fix tag argument for update-nightly-bundle.

- deploy/olm-catalog/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
- deploy/olm-catalog/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
> Fix olm samples format in the nightly CSV files

- deploy/olm-catalog/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
- deploy/olm-catalog/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
> Recovery openshift CSV description.

- .ci/cico_olm_openshift.sh
- olm/olm.sh
- olm/testCatalogSource.sh
In the pr was recovered right defaut oauth value: https://github.com/eclipse/che-operator/commit/0a54abd1e19e93b6dbe69d3b9b0c0cc84258512a#diff-accaba0f96f2bc96246cfa30da71ff64R30
But test was not ready for this value.
> Fix broken Openshift e2e test.

- pkg/controller/che/che_controller_test.go
https://issues.redhat.com/browse/CRW-1034
Add tests for defining labels for routes
> Add test for defining labels for routes

- deploy/crds/org_v1_che_crd.yaml
- deploy/olm-catalog/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
- deploy/olm-catalog/eclipse-che-preview-kubernetes/manifests/org_v1_che_crd.yaml
- deploy/olm-catalog/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- deploy/olm-catalog/eclipse-che-preview-openshift/manifests/org_v1_che_crd.yaml
- pkg/apis/org/v1/che_types.go
- pkg/apis/org/v1/zz_generated.openapi.go
https://github.com/eclipse/che/issues/17831
Add some notes about wildcard domains in nonProxyHosts field
> Add some notes about wildcard domains in nonProxyHosts field

- pkg/deploy/deployment_che.go
Signed-off-by: Vitalii Parfonov <vparfono@redhat.com>
> Add keycloak admin username and password to the che deployment

- .github/CODEOWNERS
I am removing myself from CODEOWNERS. I am not required as reviewer for PRs on this repo.
> Remove l0rd from CODEOWNERS

- pkg/controller/che/che_controller_test.go
Fix build image for upstream project.
https://issues.redhat.com/browse/CRW-1297
> Fix tests for upstream project

- .ci/cico_minishift_nightly.sh
- .ci/cico_openshift_shost.sh
- .ci/cico_updates_minishift.sh
- .github/action_scripts/nightly/minikube/single-host-gateway.sh
- .github/action_scripts/nightly/minikube/single-host-native.sh
- README.md
- RELEASE.md
*...
Deprecate server:start command (#486)
* Deprecate server:start command
> Deprecate server:start command (#486)

- .ci/util/ci_common.sh
- .github/action_scripts/nightly/minikube/function-utilities.sh
Fixes failing tests due to introducing login manager in `chectl`.
> Export Che API URL into env variable

- templates/keycloak_provision
https://github.com/eclipse/che/issues/18156
Adds swagger to the list of trusted redirects URLs
> Add swagger to the list of trusted redirects URLs

- .github/CODEOWNERS
Remove myself from CODEOWNERS
﻿
Signed-off-by: Vitalii Parfonov <vparfono@redhat.com>
> Remove @vparfonov from CODEOWNERS

- deploy/olm-catalog/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
- deploy/olm-catalog/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- deploy/olm-catalog/eclipse-che-preview-openshift/manifests/org_v1_che_crd.yaml
- olm/release-olm-files.sh
- olm/update-nightly-bundle.sh
> Set preserveUnknownFields: false for nighlty bundle

- deploy/olm-catalog/eclipse-che-preview-openshift/manifests/org_v1_che_crd.yaml
- olm/release-olm-files.sh
- olm/update-nightly-bundle.sh
Backport
https://github.com/eclipse/che-operator/pull/509
> Set preserveUnknownFields: false for nightly bundle (#509)

- .vscode/launch.json
- local-debug.sh
> Set up watch namespace in one place for debugger.

- local-debug.sh
Fix: add ability to set up namespace using -n argument and CR file using -cr.
> Fix: add ability to set up namespace using -n argument and CR file using -cr.

- .ci/cico_updates_minishift.sh
Fix minishift stable version update tests
> Fix minishift stable version update tests

- olm/olm.sh
https://github.com/eclipse/che/issues/18105
Installation tested with openshfit 4.2, 4.3, 4.4, 4.5, 4.6, 4.7(nightly)
> Update opm tool to make CatalogSource image working with openshift 4.6

- .ci/cico_minishift_nightly.sh
Runs minishift nightly tests with new templates
> Update minishift nightly tests

- olm/update-crd-files.sh
fix operator-sdk wrong version message
> fix operator-sdk version message

- local-debug.sh
> Fix local debug script

- pkg/controller/add_che.go
- pkg/controller/controller.go
Minor: Recovery licence headers for some files.
> fix: Recovery licence headers for some files.

- .github/workflows/release.yml
- make-release.sh
Miscellanious fixes to the release.yaml workflow
Change make-release.sh script to use https url
> Fix GH actions release workflow

- local-debug.sh
Looks like for operator-sdk debugger 0.17.* was broken SIGINT handler. Use workaround to fix it.
Launch debugger:
```bash
./local-debug.sh
```
Cancel it using Ctrl+C. Debugger process should exit
> fix: Looks like for operator-sdk debugger 0.17.* was broken SIGINT handler. Use workaround to fix it.

- cico_functions.sh
Change-Id:...
18292 add docker login
fix for https://github.com/eclipse/che/issues/18292
Change-Id: Ia9d579c915ef270d3998d370fdab3799223ff443
> 18292 add docker login

- .github/workflows/release.yml
- make-release.sh
> Remove odd exit from release script

- make-release.sh
> Remove test exit 0.

- olm/prepare-community-operators-update.sh
generate ci.yaml file with replace-mode; add -f flag to support re-pushing to the same branch; tweak console messages
partial fix for https://github.com/eclipse/che/issues/18502 so we can proceed to release Che 7.22 community operators
Change-Id: I86390475222325e2901a145ed107a6fc2e83c297
> generate ci.yaml file with replace-mode (#18502)

- deploy/crds/org_v1_che_cr.yaml
- deploy/olm-catalog/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
- deploy/olm-catalog/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
> remove default cheClusterRole that failed olm deployment

- .github/workflows/release-community-operator-PRs.yml
- .github/workflows/release.yml
new GH action to generate community PRs;
seems default ubuntu runner already has hub installed, so don't need to explicitly install it
Change-Id: I928ff2c9e3d3010926077841af43ecac40ce3f07
> new GH action to generate community operator PRs

- .github/workflows/release-community-operator-PRs.yml
Change-Id:...
add missing operator-sdk
Change-Id: I635dca7f32ad72a2db48ac92a616b6b9aab5c308
N/A
N/A (or see commit messasge above for issue number)
N/A
> add missing operator-sdk

- .github/bin/common.sh
- .github/bin/minikube/test-latest-olm.sh
- .github/bin/minikube/test-latest-operator-singlehost-gateway.sh
- .github/bin/minikube/test-latest-operator-singlehost-native.sh
- .github/bin/minikube/test-update-olm.sh
- .github/bin/minishift/test-latest-operator.sh
- .github/bin/minishift/test-update-operator.sh
> Fix minishift OPERATOR_REPO environment for github actions tests

- .github/bin/common.sh
- .github/bin/minikube/test-latest-olm.sh
- .github/bin/minikube/test-latest-operator-singlehost-gateway.sh
- .github/bin/minikube/test-latest-operator-singlehost-native.sh
- .github/bin/minikube/test-update-olm.sh
- .github/bin/minishift/test-latest-operator.sh
- .github/bin/minishift/test-update-operator.sh
> Fix minishift tests by adding GITHUB_WORKSPACE environment

- pkg/apis/org/v1/che_types.go
https://github.com/eclipse/che/issues/18682
> CHE-18682: fix failing Che operator on the k8s platforms.

- .github/bin/common.sh
- .github/bin/minikube/test-latest-olm.sh
- olm/README.md
- olm/testCatalogSource.sh
- pkg/controller/che/che_controller.go
> Use test operator image in the CSV.

- .vscode/tasks.json
> Improve build che-operator image dev command.

- deploy/crds/org_v1_che_crd.yaml
- deploy/olm-catalog/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
- deploy/olm-catalog/eclipse-che-preview-kubernetes/manifests/org_v1_che_crd.yaml
- deploy/olm-catalog/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- deploy/olm-catalog/eclipse-che-preview-openshift/manifests/org_v1_che_crd.yaml
- pkg/apis/org/v1/che_types.go
Improves `tlsSecretName` description
https://github.com/eclipse/che-docs/pull/1771/
> Improve tlsSecretName description

- .github/bin/common.sh
> Turn off telemetry in tests

- devfile.yaml
> Fix devfile.

- pkg/controller/che/che_controller_test.go
https://github.com/eclipse/che/issues/18766
> Fix test failing for CRW

- .github/workflows/codecov.yml
- README.md
Execute che operator tests and submit coverage results to codecov.
https://github.com/eclipse/che/issues/18626
> feat: Add code coverage artifacts for che operator

- .github/workflows/check-nightly-olm-bundle.yaml
There is no sense to run nightly olm checks in all branches. Nightly olm should be created only on master commits.
Reff issue: https://github.com/eclipse/che/issues/18644
> Run nightly olm bundle checks only in master branches

- deploy/olm-catalog/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
- deploy/olm-catalog/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- deploy/operator.yaml
- pkg/deploy/identity-provider/deployment_keycloak.go
- pkg/deploy/postgres/deployment_postgres.go
- pkg/deploy/registry/registry.go
- pkg/deploy/server/deployment_che.go
https://github.com/eclipse/che/issues/18359
For best security practices containers must implement the principle of least privilege to minimize security risks by explicitly dropping ALL capabilities and only adding ones they need.
> Drop all capabilities

- .github/workflows/minishift-e2e.yaml
- .github/workflows/minishift-operator-update.yaml
- .github/workflows/minishift-operator.yaml
- .github/workflows/minishift-stable-operator-update.yaml
- .github/workflows/release.yml
- make-release.sh
Add docker buildx to support multi-platform builds for release process
https://github.com/eclipse/che/issues/18809
> Add docker buildx to support multi-platform builds for release process

- .github/bin/check-nightly-olm-bundle.sh
Right now we are checking only if CSV change but we should check also the CRD.
Reff issue: https://github.com/eclipse/che/issues/18644
> Fix nightly bundle check

- pkg/controller/che/init_test.go
- pkg/controller/che/proxy.go
- pkg/controller/che/proxy_test.go
- pkg/deploy/defaults.go
- pkg/deploy/init_test.go
- pkg/deploy/proxy.go
- pkg/deploy/proxy_test.go
- pkg/util/util.go
1. NoProxy hosts configured in checluster and in clusterwide proxy should be merged
2. Add '.svc` to nonProxy for OpenShift 3.x and k8s
https://issues.redhat.com/browse/CRW-1520
1. Deploy Eclipse Che in a OpenShift cluster with cluster wide proxy configured.
2. Set proxy configuration in checluster as well.
3. Che server started
> Fix proxy and internal hostname case

- pkg/controller/che/che_controller_test.go
- pkg/deploy/server/che_configmap.go
Back-port to 7.24.x: Fix external identity provider, external plugin and devfile registry with enabled internal network in CR.
CRW-1532
> 7.24.x: Fix external identity provider, external plugin and devfile registry with enabled internal network in CR.

- pkg/controller/che/che_controller_test.go
- pkg/deploy/server/che_configmap.go
Fix external identity provider, external plugin and devfile registry with enabled internal network in CR.
CRW-1532
> Fix external identity provider, external plugin and devfile registry with enabled internal network in CR.

- pkg/controller/che/proxy.go
- pkg/controller/che/proxy_test.go
Add `.svc` to no proxy list
https://issues.redhat.com/browse/CRW-1565
1. Deploy Eclipse Che on OpenShift 4.x cluster with without cluster proxy configuration
2. Configure proxy directly in the cutome resource
> Add .svc to no proxy

- .github/workflows/release-community-operator-PRs.yml
Do not generate the new nightly bundle when releasing community operator update PRs.
Also, configure the use of proper che-incubator token.
> Fix community operator update action

- deploy/crds/org_v1_che_crd.yaml
- deploy/olm-catalog/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
- deploy/olm-catalog/eclipse-che-preview-kubernetes/manifests/org_v1_che_crd.yaml
- deploy/olm-catalog/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- deploy/olm-catalog/eclipse-che-preview-openshift/manifests/org_v1_che_crd.yaml
- pkg/apis/org/v1/che_types.go
Fix typos, improve docs
https://issues.redhat.com/browse/RHDEVDOCS-2216
> Fix typos, improve docs

- pkg/deploy/server/che_configmap.go
- pkg/deploy/server/che_configmap_test.go
- pkg/util/test_util.go
Fix to deploy Eclipse Che with default k8s secret
https://github.com/eclipse/che/issues/19052
1. Set `tlsSecretName: ''`
2. Deploy Eclipse Che on minikube
> Allows to deploy with default k8s secret

- .github/workflows/build.yml
- .github/workflows/nightly-image-build.yaml
- .github/workflows/release.yml
> Unblock che operator build by removing temporary linux s390x platform

- README.md
- deploy/crds/org_v1_che_crd.yaml
- deploy/olm-catalog/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
- deploy/olm-catalog/eclipse-che-preview-kubernetes/manifests/org_v1_che_crd.yaml
- deploy/olm-catalog/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- deploy/olm-catalog/eclipse-che-preview-openshift/manifests/org_v1_che_crd.yaml
- olm/README.md
- pkg/apis/org/v1/che_types.go
> Fix some crd  typos.

- .github/workflows/release-chectl.yml
- make-release.sh
Temporarily disable s390x platform build
Fix che docs release trigger workflow and add one for chectl
> Apply fixes to release workflows

- .github/workflows/release-che-docs.yml
- RELEASE.md
Fix typo in one of the release workflows
Also, update release documentation with the latest information about release process
> Update release documentation

- Dockerfile
Change-Id:...
update to latest base images
Change-Id: I341ca6fa5c6ae34e0c3d4e18704f6c8c65f92de7
N/A
N/A
> update to latest base images

- .github/bin/check-nightly-olm-bundle.sh
- .github/workflows/check-nightly-olm-bundle.yaml
Fix broke bundle check...
None. Support dev flow.
OLM bundle check should be green.
> Fix bundle check

- olm/prepare-community-operators-update.sh
Fix opm bundle path for community operators update script.
https://github.com/eclipse/che/issues/16928
> Fix opm bundle path for community operators update script.

- .github/workflows/release-che-docs.yml
- .github/workflows/release-chectl.yml
Add missing yq tool to che-docs and chectl release jobs
> Add yq to post-operator release jobs

- pkg/deploy/ingres_test.go
- pkg/deploy/route_test.go
Make tests to be independent of cheFlavor
https://issues.redhat.com/browse/CRW-1655
> Make tests to be independent of cheFlavor

- deploy/olm-catalog/nightly/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
- deploy/olm-catalog/nightly/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- pkg/deploy/dev-workspace/dev_workspace.go
Update nightly bundle
https://github.com/eclipse/che/issues/19283
> Update nightly bundle

- .github/bin/common.sh
- README.md
- olm/olm.sh
- pkg/deploy/dev-workspace/dev_workspace.go
> Fix chectl tests and fix devworkspace CRD name

- .github/bin/common.sh
We have artifacts directory declared like a constant. Openshift CI define a env variable with artifacts directory to upload to jobs views.
https://docs.ci.openshift.org/docs/architecture/step-registry/#available-environment-variables
> Fix artifacts name in openshfit ci

- olm/olm.sh
> Fix e2e: Wait for catalog source to be ready

- .ci/openshift-ci/Dockerfile
Reff issue in slack : https://coreos.slack.com/archives/CFUGK0K9R/p1616593049017300
> Replace openshift ci registry image in our container build for test purpose

- .github/bin/common.sh
- .github/workflows/minikube-stable-olm-update.yaml
> [Backport]Fix che operator updates tests

- .github/bin/common.sh
- .github/workflows/minikube-stable-olm-update.yaml
REff issue: https://github.com/eclipse-che/che-operator/pull/737
> Minor fix. Che operator update tests still curl to `eclipse` org

- .github/bin/common.sh
- .github/workflows/minikube-stable-olm-update.yaml
> Fix che operator update tests by adding correctly the github token

- .github/bin/common.sh
- .github/bin/minikube/test-olm.sh
- .github/bin/minikube/test-operator-singlehost-gateway.sh
- .github/bin/minikube/test-operator-singlehost-native.sh
- .github/bin/minikube/test-operator-update.sh
- .github/workflows/minikube-olm.yaml
- .github/workflows/minikube-operator-singlehost.yaml
- .github/workflows/minikube-operator-update.yaml
- .github/workflows/minikube-stable-olm-update.yaml
> Install olm 0.17 version instead off minikube olm addon

- Dockerfile
[CRW-1655](https://issues.redhat.com/browse/CRW-1655) unpack zips to generic folders as we can't do COPY with wildcard folders
also fix broken rpm update
Change-Id: Ifd3d0a6d3167af760bae5ea72ffde79ba7354664
N/A
Built successfully in https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=1532862
Once merged, can merge this followup:
https://gitlab.cee.redhat.com/codeready-workspaces/crw-jenkins/-/merge_requests/411
Build it locally, verify contents are as expected in final container. 
Equivalent dockerfile worked in Brew, so confident it should work upstream, assuming I didn't mess up the expected directory structure in the resulting container. …
> CRW-1655 unpack zips to generic folders as we can't do COPY with wildcard folders

- Dockerfile
While the dockerfile run locally works, in Brew we get this:
```
error: No available modular metadata for modular package 'httpd-tools-2.4.37-30.module+el8.3.0+7001+0766b9e7.x86_64'; cannot be installed on the system
```
Turns out the problem here is that once you install dnf, module support is needed... and we didn't have the correct content sets being enabled to pull from pulp repos (brew repos don't have module metadata because reasons).
So I've fixed the content set issue in 
https://github.com/redhat-developer/codeready-workspaces-images/commit/c41cd8979257bab9dda9db213c05ceaaafa6feec
And this change will make the container smaller (no need for full yum/dnf when microdnf works fine).
Change-Id: Ia1bd0f6aff78751c3570a23cf12b4d953850531b …
> bug(fix) don't install dnf as we don't need it (microdnf can do cve updates too)

- olm/update-crd-files.sh
- olm/update-nightly-bundle.sh
none. Improve dev flow.
Add GOROOT check for dev scripts.
Execute update crd or update nightly bundle scripts. If GOROOT is an empty scripts should fail.
> Minor: Add GOROOT check for dev scripts.

- deploy/crds/org_v1_che_cr.yaml
- deploy/olm-catalog/nightly/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
- deploy/olm-catalog/nightly/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- pkg/controller/che/che_controller.go
- pkg/controller/che/create.go
- pkg/deploy/defaults.go
- pkg/deploy/pvc.go
https://github.com/eclipse/che/issues/19314
> Change default pvc to 10G.

- deploy/cluster_role_binding.yaml
- deploy/namespaces_cluster_role_binding.yaml
- pkg/controller/che/che_controller.go
- pkg/deploy/clusterrolebinding.go
- pkg/deploy/clusterrolebinding_test.go
- pkg/deploy/finalizer.go
- pkg/deploy/finalizer_test.go
* fix problem when finalizer can be longer than 63 characters
* fix problem when crb is continuously deleted and recreated
https://github.com/eclipse/che/issues/19506
1. deploy Eclipse Che
2. create clusterrole https://raw.githubusercontent.com/eclipse-che/che-operator/master/deploy/namespaces_cluster_role.yaml
3. update `spec.server.cheClusterRoles: che-namespace-editor`
4. check operator log, `che-namespace-editor` clusterrolebinding is created
5. delete namespace `eclipse-che`
6. namespace is supposed to be deleted
> Improve reconciling crb finalizers

- .github/workflows/nightly-image-build.yaml
> Fix GitHub workflow

- pkg/controller/che/che_controller.go
- pkg/deploy/expose/expose.go
- pkg/deploy/gateway/gateway.go
- pkg/deploy/ingress.go
- pkg/deploy/server/che_configmap.go
- pkg/deploy/server/che_configmap_test.go
We should take into account that in case of kubernetes the exposure strategy might be set in `spec.k8s.ingressStrategy` field.
https://github.com/eclipse/che/issues/19218
> Fix getting exposure strategy in case of k8s

- deploy/olm-catalog/nightly/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
- deploy/olm-catalog/nightly/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- deploy/operator.yaml
This PR update traefik image to use quay.io and use version 2.3.2.
Ref issue: https://github.com/eclipse/che/issues/19431
> Update to traefik 2.3.2 using new quay.io image

- pkg/controller/che/che_controller.go
Fix creating che ingress with correct host
> Fix creating che ingress with correct host

- .github/workflows/release-che-docs.yml
- .github/workflows/release-chectl.yml
- .github/workflows/release.yml
Fixes for Che release workflows (typos & missing parameters)
> Fixes to Che Operator release workflows

- .github/workflows/release.yml
- olm/update-crd-files.sh
- olm/update-nightly-bundle.sh
Fix a bug discovered during release, when it didn't fail with missing GOROOT variable
> Fix GOROOT env variable not being set during release

- .github/workflows/minikube-olm.yaml
- .github/workflows/minikube-operator-singlehost.yaml
- .github/workflows/minikube-operator-update.yaml
- .github/workflows/minikube-stable-olm-update.yaml
- olm/olm.sh
> Install minikube 1.18.1 instead of latest one

- deploy/crds/org_v1_che_crd.yaml
- deploy/olm-catalog/nightly/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
- deploy/olm-catalog/nightly/eclipse-che-preview-kubernetes/manifests/org_v1_che_crd.yaml
- deploy/olm-catalog/nightly/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- deploy/olm-catalog/nightly/eclipse-che-preview-openshift/manifests/org_v1_che_crd.yaml
- pkg/apis/org/v1/che_types.go
- pkg/controller/che/che_controller.go
- pkg/controller/che/oauth_initial_htpasswd_provider.go
- pkg/controller/che/oauth_initial_htpasswd_provider_test.go
- pkg/deploy/sync.go
- pkg/util/util.go
- create `openshift-oauth-user-credentials` secret in `openshift-config` namespace instead of `eclipse-che`
- removes initial user when Eclipse Che is removed
- fix printing object types in `sync.go`
https://github.com/eclipse/che/issues/19380
> Remove OpenShift OAuth user when Eclipse Che is removed

- .github/workflows/codecov.yml
Removes CODECOV_TOKEN from GitHub action.
It isn't needed [1] and it is compromised [2]
[1] https://docs.codecov.io/docs/about-the-codecov-bash-uploader#upload-token
[2] https://about.codecov.io/security-update/
> Remove `CODECOV_TOKEN` from GitHub action

- replace-images-tags.sh
Restore replace-images-tag.sh file needed to release 7.29.x
N/A
N/A
N/A
> Restore replace-images-tag.sh file needed to release 7.29.x

- pkg/deploy/server/che_configmap.go
- pkg/deploy/server/che_configmap_test.go
Add `/auth` path to external identity providers url to correctly propagate into `che`  configmap for 
- `CHE_KEYCLOAK_AUTH__INTERNAL__SERVER__URL`
- `CHE_KEYCLOAK_AUTH__SERVER__URL`
https://github.com/eclipse/che/issues/19648
1. Deploys Eclipse Che with external identity provider
2. Check `che` config map, make sure that `CHE_KEYCLOAK_AUTH__INTERNAL__SERVER__URL`, `CHE_KEYCLOAK_AUTH__SERVER__URL` end with `/auth`
> Add `/auth` path to external identity providers url

- olm/ci.yaml
add che incubator bot to olm/ci.yaml (support downstream PR approval automation)
Change-Id: Ia09dcff089e3f0df0889a8c0fb0942b70259e725
N/A
N/A
> fix: add che incubator bot to olm/ci.yaml (support downstream PR approval automation)

- .github/bin/check-bundle-version.sh
Fix bundle version check
N/A
https://github.com/eclipse/che/issues/19515
N/A
> Fix bundle version check

- .github/workflows/release-che-docs.yml
- .github/workflows/release-chectl.yml
Minor fixes to chectl and che-docs job triggers
> Fix operator post-release job triggers

- deploy/olm-catalog/nightly/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
- deploy/olm-catalog/nightly/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- deploy/operator.yaml
- make-release.sh
- pkg/deploy/defaults.go
- pkg/deploy/dev-workspace/dev_workspace.go
Expose DWO and DWCO images in CSV as RELATED_IMAGE_* env vars
N/A
https://github.com/eclipse/che/issues/19667
N/A
> Expose DWO and DWCO images in CSV as RELATED_IMAGE_* env vars

- olm/release-olm-files.sh
Correctly update dashboard image tag
N/A
Release process
N/A
> Correctly update dashboard image tag

- olm/prepare-community-operators-update.sh
Fix the wrong path for ci.yaml
> Minor fix in prepare-community-operators-update.sh

- .ci/oci-disconnected.sh
- .github/bin/common.sh
- .github/bin/resources/slack-message-template.json
- .github/bin/slack.sh
This PR add necessary scripts to deploy Eclipse Che in Openshift Disconnected environment.
Ref issue:https://github.com/eclipse/che/issues/19534
N/A
N/A
> Add script to deploy eclipse che in disconnected environment

- .ci/oci-devworkspace-happy-path.sh
Add `devworkspace-che` logs to test report.
> [Selenium] Add devworkspace-che logs to test report

- .ci/oci-multi-host.sh
- .ci/oci-single-host.sh
- .github/bin/common.sh
N/A
Remove devWorkspace tests from multi-host deployment to single hosts deployment.
N/A
N/A
N/A
> Add devworkspace tests in single-host mode

- pkg/controller/che/che_controller.go
- pkg/deploy/dashboard/dashboard.go
- pkg/deploy/dashboard/dashboard_test.go
- pkg/deploy/dashboard/deployment_dashboard.go
N/A
This PR backport the PR from https://github.com/eclipse-che/che-operator/pull/839
N/A
Ref issue: https://issues.redhat.com/browse/CRW-1829
N/A
> BackPort : Fix dashboard component names depending on che flavor 

- pkg/controller/che/che_controller.go
- pkg/deploy/dashboard/dashboard.go
- pkg/deploy/dashboard/dashboard_test.go
- pkg/deploy/dashboard/deployment_dashboard.go
- pkg/deploy/defaults.go
This PR change the name of dashboard component depending on Che Flavor
https://issues.redhat.com/browse/CRW-1829
N/A
> Fix dashboard component names depending on che flavor

- make-release.sh
- olm/update-resources.sh
Fix update resources and release script after moving some part of the che repository to che-server.
none
Resource check should be green. 
> Fix che.properties file links.

- .ci/oci-disconnected.sh
N/A
Add sleep of 2 hours in disconnected cluster to do manual tests.
N/A
N/A
N/A
> Add 2h of sleep to do some manual tests

- Dockerfile
- go.mod
- olm/update-resources.sh
- vendor/modules.txt
* use ubi8-minimal:8.4 base image
* install go-toolset from RPM (using RHEL 8.4 appstream repo)
* switches to go 1.14
N/A
https://github.com/eclipse/che/issues/19764
N/A
> chore(Dockerfile): Switch to go 1.15

- deploy/crds/org_v1_che_crd-v1beta1.yaml
- deploy/crds/org_v1_che_crd.yaml
- deploy/olm-catalog/nightly/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
- deploy/olm-catalog/nightly/eclipse-che-preview-kubernetes/manifests/org_v1_che_crd.yaml
- deploy/olm-catalog/nightly/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- deploy/olm-catalog/nightly/eclipse-che-preview-openshift/manifests/org_v1_che_crd.yaml
- pkg/apis/org/v1/che_types.go
Update che_types.go, fix descriptions
N/A
N/A
N/A
> fix: Update che_types.go, fix descriptions

- .github/workflows/release-chectl.yml
- make-release.sh
Change release pull request names to be compatible with "semantic PR naming" 
also fix the wrong token in chectl release job
> ci: Use semantic PRs name in release workflows

- olm/addDigests.sh
Remove duplicates in related images
N/A
https://github.com/eclipse/che/issues/19770
1. `olm/addDigests.sh -w . -s deploy/olm-catalog/stable/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml -t 7.31.0`
2. check that there are no duplicates in csv file
> fix: Remove duplicates in related images

- .ci/oci-disconnected.sh
This PR removes nonProxyHosts from CR. This value is set only on authenticated proxy.
N/A
N/A
N/A
> fix: Remove NON_PROXY from custom resource in disconnected tests

- .ci/oci-devworkspace-happy-path.sh
Use `happy-path test` pod yaml file from `che` repo.
This PR is also a part of https://github.com/eclipse/che/issues/19905 issue.
> [Selenium] Use 'happy-path' test pod yaml file from che repo

- .ci/openshift-ci/Dockerfile
- .github/workflows/pr-main-check.yml
- .github/workflows/release.yml
- olm/docker-run.sh
- olm/update-resources.sh
* Switch to go 1.15 in GitHub Actions
* Removes leftovers after operator-sdk after CRD generation
N/A
N/A
N/A
> fix: Switch to go 1.15 in GitHub Actions

- Dockerfile
Downloads license file for restic binary
https://github.com/eclipse/che/issues/20028
Run built image and navigate to `/usr/local/bin`
> Build restic binary from source

- .ci/oci-proxy.sh
- .github/bin/common.sh
- .github/workflows/minikube-backup-restore.yaml
- .github/workflows/minikube-olm.yaml
- .github/workflows/minikube-operator-singlehost.yaml
- .github/workflows/minikube-operator-update.yaml
- .github/workflows/minikube-stable-olm-update.yaml
Fix minikube tests by increasing minikube version to latest and add latest templates to che-proxy job
N/A
Ref PR: https://github.com/eclipse-che/che-operator/pull/861
N/A
> fix: Some tests in minikube in version 1.18.1 is failing.

- RELEASE.md
- make-release.sh
Updates documentation since `--push-olm-files` is no longer used.
> fix: Update --push-olm-bundles documentation

- make-release.sh
fix: typo - odd pipe in yq series of commands
N / A
> fix: typo - redundant pipe in yq series of commands

- olm/release-olm-files.sh
> fix: retrieving CRD on release

- olm/release-olm-files.sh
Fix coping backup/restore CRDs into a stable olm bundle
N/A
N/A
N/A
> fix: copy backup/restore CRDs into a stable olm bundle

- make-release.sh
Fix wrong DWO / DWCO versions used in release scripts
> fix: use proper DWO and DWCO versions in release scripts

- make-release.sh
- olm/release-olm-files.sh
> ci: Release script fixes

- make-release.sh
- olm/release-olm-files.sh
some more fixes to DWCO version change during the release
> fix: more DWCO version fixes in release scripts

- make-release.sh
fix wrong variable name (for dwco version) that caused release failure
> fix: fix wrong variable name in the release script

- olm/buildDigestMap.sh
- olm/images.sh
Fix setting image digests on release
N/A
N/A
N/A
> fix: Fix setting image digests on release

- make-release.sh
- olm/release-olm-files.sh
fix wrong CSV that gets generated during release
> fix: fix CSV generation during release

- olm/buildDigestMap.sh
fix: adding image digests
N/A
N/A
N/A
> fix: adding image digests

- pkg/deploy/dev-workspace/dev_workspace.go
fix: make che operator take into account DWO Service
Fixes https://github.com/eclipse/che/issues/20119
Deploy Che with devWorkspace enabled and make sure DWO is run.
> fix: make che operator take into account DWO Service

- deploy/crds/org_v1_che_crd-v1beta1.yaml
- deploy/crds/org_v1_che_crd.yaml
- deploy/olm-catalog/nightly/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
- deploy/olm-catalog/nightly/eclipse-che-preview-kubernetes/manifests/org_v1_che_crd.yaml
- deploy/olm-catalog/nightly/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- deploy/olm-catalog/nightly/eclipse-che-preview-openshift/manifests/org_v1_che_crd.yaml
- pkg/apis/org/v1/che_types.go
Updating default value of pvcClaimSize field according to @rhopp 's notification
Changing default value for pvcClaimSize from 1GB to 10GB.
https://github.com/eclipse/che-docs/pull/2057
> chore(che_types.go): Fix `pvcClaimSize` description

- olm/olm.sh
- pkg/controller/che/che_controller_test.go
Backport fixes found during che-operator 7.33.0 release
N/A
N/A
N/A
> fix: Backport fixes found during che-operator 7.33.0 release

- bundle/nightly/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
- bundle/nightly/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
chore: update to latest che--traefik:v2.5.0-rc2-df90799aaca1ad6fb9e06d311140035d2a0c2295a4f8f508f6b55ee056bb677e (#20147)
Change-Id: Iee6810fe58e636195bc5b880cfbda7443113f0c8
N/A
https://github.com/eclipse/che/issues/20147
N/A
> build: update to latest traefik image

- bundle/nightly/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
- bundle/nightly/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- olm/release-olm-files.sh
Change Devworkspace Che operator image from ci to next 
https://github.com/eclipse/che/issues/19291
> chore: Change Devworkspace Che Operator image

- bundle/nightly/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
- bundle/nightly/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
Revert traefik image from RC to a stable one.
N/A
N/A
N/A
> chore(manager.yaml): revert traefik image from RC to a stable one

- Makefile
I don't debug Che Operator often but each time I run it against minikube I hit this issue that Che Cluster CR is not correct, so, I came to these changes.
N/A
N/A
N/A
> feat: ask confirmation if ingress domain does not correspond the current cluster

- olm/buildAndPushBundleImages.sh
- olm/olm.sh
* Fix regression: fix tear down OLM channels. 
* Improve force bundle images rebuild logic.
N/A
N/A
N/A
> fix: Fix tear down olm channels

- Makefile
- config/crd/bases/org.eclipse.che_checlusterrestores_crd-v1beta1.yaml
Make CRD file compatible with OpenShift 3.11
N/A
https://github.com/eclipse/che/issues/20162
1. Apply CRD v1beta1 on OCP 3.11
> fix: Make CRD file compatible with OpenShift 3.11

- .ci/cico_updates_openshift.sh
- .ci/oci-multi-host.sh
- .ci/oci-single-host.sh
- .github/bin/check-resources.sh
- .github/bin/common.sh
- .github/bin/minikube/test-olm.sh
- .github/bin/minikube/test-operator-singlehost-gateway.sh
- .github/bin/minikube/test-operator-singlehost-native.sh
- Makefile
- bundle/nightly/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
- bundle/nightly/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- config/rbac/cluster_role.yaml
- pkg/deploy/defaults.go
- pkg/deploy/dev-workspace/dev_workspace.go
- pkg/util/util.go
Support of devworkspaces on k8s and continuation of https://github.com/eclipse-che/che-operator/pull/867
https://github.com/eclipse/che/issues/19944
1. Use minikube or other Kubernetes cluster. 
2. Build and deploy che-operator
3. Enable devworkspaces 
``` 
kubectl patch checluster/eclipse-che -n eclipse-che --type=json -p \
'[{"op": "replace", "path": "/spec/devWorkspace/enable", "value": true}]'
```
4. Enable k8s API on che-server 
```
kubectl patch checluster/eclipse-che --patch "{\"spec\":{\"server\":{\"customCheProperties\": {\"CHE_INFRA_KUBERNETES_ENABLE__UNSUPPORTED__K8S\": \"true\"}}}}" --type=merge -n eclipse-che
````
5. create k8s namespace ```username-che```
6. Start a workspace from devfile 2.0 …
> feat: Devworkspaces on K8s

- bundle/nightly/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
- bundle/nightly/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- config/rbac/cluster_role.yaml
- controllers/che/workspace_namespace_permission.go
In case if Roles or RoleBindings were changed (updated/removed/added), existing workspace ServiceAccount doesn't apply such updates. To be able to update them, we need appropriate permission.
https://github.com/eclipse/che/issues/19697
> fix: Allow roles update for che workspace cluster role

- Makefile
- config/crd/bases/org.eclipse.che_chebackupserverconfigurations_crd-v1beta1.yaml
- config/crd/bases/org.eclipse.che_checlusterbackups_crd-v1beta1.yaml
- config/crd/bases/org_v1_che_crd-v1beta1.yaml
Make CRDs compatible with OpenShift 3.11
N/A
https://github.com/eclipse/che/issues/20162
N/A
> fix: Make CRDs compatible with OpenShift 3.11

- bundle/stable/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
- bundle/stable/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml.diff
- bundle/stable/eclipse-che-preview-kubernetes/manifests/org.eclipse.che_chebackupserverconfigurations_crd.yaml
- bundle/stable/eclipse-che-preview-kubernetes/manifests/org.eclipse.che_chebackupserverconfigurations_crd.yaml.diff
- bundle/stable/eclipse-che-preview-kubernetes/manifests/org.eclipse.che_checlusterbackups_crd.yaml
- bundle/stable/eclipse-che-preview-kubernetes/manifests/org.eclipse.che_checlusterbackups_crd.yaml.diff
- bundle/stable/eclipse-che-preview-kubernetes/manifests/org.eclipse.che_checlusterrestores_crd.yaml
- bundle/stable/eclipse-che-preview-kubernetes/manifests/org.eclipse.che_checlusterrestores_crd.yaml.diff
- bundle/stable/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- bundle/stable/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml.diff
- bundle/stable/eclipse-che-preview-openshift/manifests/org.eclipse.che_chebackupserverconfigurations_crd.yaml
- bundle/stable/eclipse-che-preview-openshift/manifests/org.eclipse.che_chebackupserverconfigurations_crd.yaml.diff
- bundle/stable/eclipse-che-preview-openshift/manifests/org.eclipse.che_checlusterbackups_crd.yaml
- bundle/stable/eclipse-che-preview-openshift/manifests/org.eclipse.che_checlusterbackups_crd.yaml.diff
- bundle/stable/eclipse-che-preview-openshift/manifests/org.eclipse.che_checlusterrestores_crd.yaml
- bundle/stable/eclipse-che-preview-openshift/manifests/org.eclipse.che_checlusterrestores_crd.yaml.diff
- version/version.go
> ci: Copy 7.33.2 to main

- .github/workflows/release.yml
chore: bump to action-mattermost-notify@1.1.0 (1.0.2 is broken)
Change-Id: I61875ee0eb4760fb7a12491ad1853f9153ae4249
N/A
N/A
> chore: bump to action-mattermost-notify@1.1.0 (1.0.2 is broken)

- Makefile
- bundle/nightly/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
- bundle/nightly/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- config/manifests/bases/che-operator.clusterserviceversion.yaml
Add infrastructure features labels
N/A
https://issues.redhat.com/browse/CRW-1126
N/A
> feat: Add infrastructure features labels

- .github/bin/common.sh
- olm/buildAndPushBundleImages.sh
- olm/olm.sh
> fix: Fix stable update test. Fix release scripts.

- .ci/openshift-ci/Dockerfile
- .github/workflows/minikube-stable-olm-update.yaml
- .github/workflows/minishift-stable-operator-update.yaml
Install `pip` dependencies for che-operator tests
N/A
N/A
N/A
> fix: Install `pip` dependencies for che-operator tests

- bundle/nightly/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
- bundle/nightly/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
Add missing resources to operator deployment (accidentally removed after refactoring)
N/A
N/A
N/A
> fix: add missing resources to operator deployment

- .vscode/tasks.json
- Makefile
Fix tests developement commands.
Use `run che-operator tests` vscode task, or `make test -s` 
> fix: commands to run unit tests

- .github/workflows/release-che-docs.yml
- .github/workflows/release-chectl.yml
- olm/prepare-community-operators-update.sh
Fix community-operator, chectl and che-docs release job triggers
> fix: Fixes for Che-Operator post release workflows

- .ci/oci-devworkspace-happy-path.sh
- .ci/oci-disconnected.sh
- .ci/oci-nightly-update.sh
- .github/bin/common.sh
- .github/bin/minikube/test-olm.sh
- .github/bin/minikube/test-operator-singlehost-gateway.sh
- .github/bin/minikube/test-operator-singlehost-native.sh
- .github/bin/minishift/test-stable-operator-update.sh
1. Fix minishift update test
2. Add `--batch` to chectl commands (https://github.com/eclipse/che/issues/20144)
3. Remove workspace creation for devworkspace che operator due to cpu limitation
N/A
N/A
N/A
> chore: fix e2e tests

- bundle/next/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
- bundle/next/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- config/manifests/bases/che-operator.clusterserviceversion.yaml
Eclipse Che/Codeready workspace have been tested on OpenShift Platform with FIPS enabled (deployed, workspace started, terminal works)
Adds 'fips' feature label for OpenShift platform
N/A
https://issues.redhat.com/browse/CRW-1598
N/A
> chore: add 'fips' feature label

- .github/workflows/release-chectl.yml
- .github/workflows/release-community-operator-PRs.yml
- olm/prepare-community-operators-update.sh
- Set fixed version of DWO for chectl trigger job
> fix: Small fixes to operator post-release workflow triggers

- bundle/next/eclipse-che-preview-openshift/bundle.Dockerfile
- bundle/next/eclipse-che-preview-openshift/metadata/annotations.yaml
- olm/release-olm-files.sh
Setting specific OpenShift version in annotations for stable-all-namespaces bundle in addition to label (https://github.com/eclipse-che/che-operator/pull/997)
N/A
https://github.com/eclipse/che/issues/20234
N/A
> chore: setting specific OpenShift version in annotations for stable-all-namespaces bundle

- Dockerfile
- Makefile
- pkg/deploy/dev-workspace/dev_workspace.go
[CRW-1730](https://issues.redhat.com/browse/CRW-1730) now that DWO 0.8 is live, remove deployment templates from Che operator (7.34.x)
Change-Id: Ic2d661089f8166f87c65c17c7e430c94155f9d17
N/A
N/A
> chore: CRW-1730 now that DWO 0.8 is live, remove deployment templates from Che operator (7.34.x)

- bundle/next/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
- bundle/next/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- config/rbac/cluster_role.yaml
Update cluster permissions
N/A
N/A
N/A
> chore: update permissions

- bundle/next/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
- bundle/next/eclipse-che-preview-openshift/bundle.Dockerfile
- bundle/next/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- bundle/next/eclipse-che-preview-openshift/metadata/annotations.yaml
- bundle/stable/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
- bundle/stable/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- olm/release-olm-files.sh
* Fix accidentally committed merge conflict
* Removes RELATED_IMAGE_devworkspace_che_operator
N/A
N/A
N/A
> fix: remove RELATED_IMAGE_devworkspace_che_operator env var

- .github/workflows/release.yml
Remove an input from release workflow, that is not needed anymore
> Remove DWCO from release workflow inputs

- make-release.sh
Remove an odd pipe that breaks the synthax in make-release.sh script
> fix: remove odd pipe in make-release.sh

- olm/release-olm-files.sh
Deletes debug exit from release script
https://github.com/eclipse/che/issues/20336
Make a release
> Remove debug code that brakes script execution

- .github/bin/check-resources.sh
- .github/workflows/pr-main-check.yml
- pkg/deploy/dashboard/dashboard.go
- pkg/deploy/dashboard/dashboard_test.go
- pkg/deploy/dashboard/deployment_dashboard.go
- pkg/deploy/dashboard/rbac.go
feat: configure dashboard backend:
- propagate Che host and Keycloack host, later it could be moved to configmap, but since they are two properties, for time being they are injected to deployment directly;
- handle RBAC;
In addition it has minor fixes for github workflow which I discovered when they failed.
it's for https://github.com/eclipse-che/che-dashboard/pull/314 but it should be safe to merge it earlier.
Just make sure everything works ;)
> feat: configure dashboard backend

- .github/workflows/pr-main-check.yml
- controllers/che/checluster_controller.go
- pkg/deploy/dashboard/dashboard.go
- pkg/deploy/dashboard/dashboard_test.go
- pkg/deploy/dashboard/rbac.go
as @tolusha suggested, I reworked Dashboard Cluster RBAC to be finalized with custom logic instead of `SyncClusterRoleBindingAndAddFinalizerToCluster` I used before.
Also, again as @tolusha suggested, I use namespace prefix for Cluster RBAC related objects.
it follows up https://github.com/eclipse-che/che-operator/pull/1006
1. Deploy Che on minikube.
2. Remove CheCluster.
3. Make sure Dashboard related RBAC objects (ClusterRole and ClusteRoleBInding) is removed.
4. Make sure CheCluster is removed and no hangs on the cluster due finalizers.
> feat: Make dashboard finalize its cluster rbac

- api/v1/checluster_types.go
- bundle/next/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
- bundle/next/eclipse-che-preview-kubernetes/manifests/org_v1_che_crd.yaml
- bundle/next/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- bundle/next/eclipse-che-preview-openshift/manifests/org_v1_che_crd.yaml
- config/crd/bases/org_v1_che_crd-v1beta1.yaml
- config/crd/bases/org_v1_che_crd.yaml
- config/manifests/bases/che-operator.clusterserviceversion.yaml
Adds `Technology Preview` notice to DevWorkspace section of Che Operator.
Fixes https://github.com/eclipse/che/issues/20377
1. Open web console
2. Go to `Operators` -> `Installed Operators`
3. In Che Operator row, select `Eclipse Che Cluster` in `Provided APIs` column
4. Click `Create CheCluster`
5. Scroll to `Dev Workspace` section
> Add 'Technology Preview' to DevWorkspace Operator section description

- bundle/nightly/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
- bundle/nightly/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- config/rbac/cluster_role.yaml
Update rbac
N/A
https://issues.redhat.com/browse/CRW-2167
N/A
> fix: Update permissions

- bundle/next/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
- bundle/next/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- config/rbac/cluster_role.yaml
- make-release.sh
It turned out that PR checks in released PRs were used a main version of workspace controller.
This PR update Dockerfile during release to use a correct version of  devworkspace controller.
N/A
N/A
N/A
> fix: Update Dockerfile to set devworkspace controller version

- pkg/deploy/gateway/gateway.go
Added defaults for Protocol
To avoid unnecessary reconciliation.
unnecessary reconciliation.
- build pr
- start eclipse che
> fix: Added the default TCP protocol for che-gateway port

- .github/bin/minikube/test-olm.sh
Release PR uses stable channel to test operator
N/A
https://github.com/eclipse/che/issues/20397
N/A
> fix: Release PR should use stable channel to test operator

- olm/release-olm-files.sh
Deprecate DevWorkspace from stable channel.
https://github.com/eclipse/che/issues/20392
> feat: Deprecate devWorkspace from stable channel

- .github/bin/minikube/test-olm.sh
- make-release.sh
* Exclude Dockerfile from copying to main branch on release
* Use stable channel for release PR
N/A
N/A
N/A
> fix: release process

- README.md
- controllers/che/che_cr_validator.go
- controllers/che/create.go
- pkg/deploy/defaults.go
- pkg/deploy/identity-provider/identity_provider.go
- pkg/deploy/postgres/postgres.go
- pkg/deploy/server/server.go
- pkg/deploy/server/server_configmap.go
- pkg/deploy/server/server_deployment.go
- pkg/deploy/server/server_test.go
- pkg/util/util.go
- pkg/util/util_test.go
Drops single-user mode
N/A
https://github.com/eclipse/che/issues/20315
N/A
> Drops single-user mode

- .github/PULL_REQUEST_TEMPLATE.md
Add chectl template command to deploy Eclipse Che
```bash
EOF
```
N/A
N/A
> chore: Add chectl template command to deploy Eclipse Che

- pkg/deploy/kubernetes_image_puller_test.go
Adds more tests for [kubernetes_image_puller_test.go](https://github.com/eclipse-che/che-operator/blob/main/pkg/deploy/kubernetes_image_puller_test.go).
All tests should pass (run `go test -mod=vendor -v ./...`)
> chore: add more kubernetes image puller regex tests

- pkg/deploy/kubernetes_image_puller.go
- pkg/deploy/kubernetes_image_puller_test.go
(cherry picked from commit b4c6244b4f70b102267ee98c20b5fd8e72a27fe3)
Backport for https://github.com/eclipse-che/che-operator/pull/1061
> fix: update regexes for KIP default images

- .vscode/tasks.json
- Makefile
Type in the terminal:
```bash
$ make compile
```
This command should compile che-operator. This command useful for development. Also you can provide "BINARY" arg to set up compilation binary path.
```bash
EOF
```
> feat: Development: add make compile command.

- Makefile
- pkg/deploy/dev-workspace/dev_workspace_test.go
fix: rework devworkspace tests to use assert.
In addition it fixes an ability to debug Che operator with DW enabled.
Just run unit tests
> fix: rework devworkspace tests to use assert

- templates/keycloak-provision.sh
Add `UPDDATE_PASSWORD` action for admin user 
N/A
Regression after update keycloak from 6.0.1 to 15.0.2
Install Che. Login like admin. User dashboard should ask about new password.
> fix: Add UPDDATE_PASSWORD action for admin user

- bundle/next-all-namespaces/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- bundle/next-all-namespaces/eclipse-che-preview-openshift/metadata/annotations.yaml
- bundle/next/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
- bundle/next/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- controllers/usernamespace/controller.go
- controllers/usernamespace/controller_test.go
- controllers/usernamespace/namespacecache.go
This makes sure that the `type` and `immutability` is set on the secret representing the che self signed certificate in the user's namespace.
N/A
https://github.com/eclipse/che/issues/20546
1. Use OpenShift
1. `chectl server:deploy -p openshift -a operator --workspace-engine=dev-workspace`
2. Create a namespace/project and label it with  `che.eclipse.org/workspace-namespace-owner-uid` with value of the UID of some user.
3. Create a self-signed certificate in the namespace where there is the `eclipse-che` custom resource (usually `eclipse-che` namespace)
4. There should be a new secret created in the new namespace with the copy of `ca.crt` of the self-signed-certificate from the eclipse-che namespace. …
> Set the type and immutability of the secret when copying the self-signed-cert to the user's namespace.

- .github/workflows/release-chectl.yml
- .github/workflows/release-community-operator-PRs.yml
- .github/workflows/release.yml
- add notifications for community-operator created PRs to mattermost
- remove DWO version from Chectl release job (linked PR - https://github.com/che-incubator/chectl/pull/1716/files)
- remove DWO version from Che operator release job (it is now "hardcoded" in the sources since https://github.com/eclipse-che/che-operator/pull/1083)
```bash
EOF
```
Reviewers, please …
> fix: Fixes for operator release and post-release jobs

- Dockerfile
Reorganize main Dockerfile to better utilize cache when building the image.
n/a
1. build image
2. make some code changes
3. build image again. It should reuse many image layers from cache.
> build: reorganize dockerfile to better utilize cache

- make-release.sh
Remove DWO updates during release, since it is now a fixed version
```bash
EOF
```
> fix: remove DWO update from release process

- make-release.sh
Fix  the broken docker build command
```bash
EOF
```
> fix: fix release docker build command

- .ci/cico_updates_openshift.sh
- olm/release-olm-files.sh
* don't run devworkspace tests in the stable channel (devworkspace engine is not allowed there)
* don't update devworkspace controller image
* correctly set channel
N/A
N/A
N/A
> ci: fix release

- .github/workflows/release.yml
Update release workflow runner to ubuntu-20.04
https://github.com/eclipse/che/issues/20516
```bash
EOF
```
> chore: update release runner to ubuntu-20.04

- make-release.sh
- don't set dwo controller image
N/A
N/A
N/A
> ci: fix release process

- .github/workflows/minishift-stable-operator-update.yaml
Fix improperly installed  yq in minishift test
```bash
EOF
```
> fix: fix python setup in minishift test

- pkg/deploy/dev-workspace/dev_workspace.go
https://github.com/eclipse-che/che-operator/pull/1085 changed the way operator detects if it should be restored, but it does not work as expected. So, this PR fixes Che operator restart after DevWorkspace enabled on k8s, in a quick way, just return what was before.
https://github.com/eclipse/che/issues/20576
```bash
spec:
k8s:
singleHostExposureType: gateway
server:
customCheProperties:
CHE_INFRA_KUBERNETES_ENABLE__UNSUPPORTED__K8S: "true"
EOF
--platform minikube \
--workspace-engine=dev-workspace
```
[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request …
> fix: fix Che operator restart after DevWorkspace enabled on k8s

- Dockerfile
Change-Id: I45bdda11ae759d3eed9a0d3bee1e158a621c10b3
> chore: Update from ubi8/go-toolset:1.15.14-3 to ubi8/go-toolset:1.15.14-10

- bundle/next-all-namespaces/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- bundle/next/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
- bundle/next/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
fix: [CRW-2383](https://issues.redhat.com/browse/CRW-2383) bump limit to 5g in main branch (7.38)
Change-Id: I7376f2082df159617cebde84d11e62d3ff1537bb
N/A
https://issues.redhat.com/browse/CRW-2383
N/A
> fix: CRW-2383 bump limit to 5g

- pkg/deploy/dashboard/rbac.go
feat: grant dashboard permissions to manage secrets.
It's needed since currently on Kubernetes, dashboard manages user's stuff (like secrets for preferences like container registry credentials) via Dashboard SA.
On OpenShift user's identity is used for any operation. It will be the case for Kubernetes after we have Native Auth for K8s. And it should be reverted then.
This is to make https://github.com/eclipse-che/che-dashboard/pull/382 working on Kubernetes.
```bash
EOF
``` …
> feat: grant dashboard permissions to manage secrets

- bundle/next-all-namespaces/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- bundle/next/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
- bundle/next/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
Make next bundles up to date
N/A
N/A
N/A
> chore: Update next bundles

- Dockerfile
Change-Id: I428f3f3e247380dffb929029ff0dd62437f8f1f2
> chore: Update from ubi8/go-toolset:1.15.14-18 to ubi8/go-toolset:1.16.7-5

- .github/workflows/try-in-web-ide.yaml
https://github.com/eclipse/che/issues/20664
Currently, the workspace startup is failing with 
`Failed to run the workspace: "Unrecoverable event occurred: 'Failed', 'Failed to pull image "quay.io/eclipse/che-golang-1.12:nightly": rpc error: code = Unknown desc = reading manifest nightly in quay.io/eclipse/che-golang-1.12: unknown: Tag nightly was deleted or has expired. To pull, revive via time machine', 'workspaceah3emmrb1cr6s0ti.dev-565dfd8cd7-c4sc9'"`
@tolusha looks like the devfile need to be updated
https://github.com/eclipse/che/issues/20664
> chore: Adding 'try-in-web-ide.yaml' yaml to github flow

- .github/bin/common.sh
- .github/workflows/try-in-web-ide.yaml
Collecting logs produce a lot of output.
This PR is intended to mitigate this.
N/A
N/A
N/A
> fix: remove output on log collecting

- pkg/deploy/openshift-oauth/openshiftoauth_user.go
- pkg/deploy/secret.go
* Remove spam on reconcile
* Improve code
https://github.com/eclipse/che/issues/19284
N/A
> fix: Remove spam on reconcile

- pkg/deploy/tls.go
Fix returning non relevant error
N/A
https://github.com/eclipse/che/issues/20647
N/A
> fix: returning non relevant error

- controllers/devworkspace/controller.go
- controllers/devworkspace/defaults/defaults.go
- controllers/devworkspace/solver/che_routing.go
- controllers/devworkspace/solver/endpoint_exposer.go
- controllers/devworkspace/sync/sync.go
Fixes inability to start a workspace in devworkspace mode
N/A
https://github.com/eclipse/che/issues/20801
Start a devworkspace
> fix: Apply part-of label to devworkspace resources managed by Che Operator

- olm/buildCatalog.sh
Fix checking if bundle exists in a catalog while building a new index and bundle image
N/A
https://github.com/eclipse-che/che-operator/runs/4280288208?check_suite_focus=true
> fix: checking if bundle exists in a catalog

- olm/buildCatalog.sh
Fix building catalog and bundle image
N/A
N/A
> fix: build catalog and bundle image

- olm/buildCatalog.sh
Fix adding bundle from next-all-namespaces channel
N/A
N/A
N/A
> fix: Adding bundle from next-all-namespaces channel

- controllers/che/cheobj_verifier_test.go
Fix building downstream
N/A
https://issues.redhat.com/browse/CRW-2495
1. set env var `CHE_FLAVOR: codeready` in `config/manager/manager.yaml`
2. run `make test`
> fix: build downstream

- bundle/next-all-namespaces/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- bundle/next/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
- bundle/next/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
Update backup REST server image
N/A
N/A
N/A
> chore: Update backup REST server image

- .github/workflows/release-helm-charts.yaml
Fix helm release package action.
Fix release.
```bash
EOF
```
> Fix helm release package action.

- api/v1/checluster_types.go
- bundle/next-all-namespaces/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- bundle/next-all-namespaces/eclipse-che-preview-openshift/manifests/org_v1_che_crd.yaml
- bundle/next/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
- bundle/next/eclipse-che-preview-kubernetes/manifests/org_v1_che_crd.yaml
- bundle/next/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- bundle/next/eclipse-che-preview-openshift/manifests/org_v1_che_crd.yaml
- config/crd/bases/org_v1_che_crd-v1beta1.yaml
- config/crd/bases/org_v1_che_crd.yaml
- helmcharts/next/crds/org_v1_che_crd.yaml
- pkg/deploy/defaults.go
- pkg/deploy/postgres/postgres.go
Configure pvcClaimSize for PostgreSQL
N/A
https://github.com/eclipse/che/issues/20837
> feat: configure pvcClaimSize for PostgreSQL

- .github/workflows/release-helm-charts.yaml
Fix helm package release.
Fix release.
```bash
EOF
```
> Fix helm package release.

- pkg/deploy/dev-workspace/sync.go
Creates DevWorkspace metrics service
N/A
https://github.com/eclipse/che/issues/20762
N/A
> fix: create DevWorkspace metrics service

- bundle/next-all-namespaces/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- bundle/next/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
- bundle/next/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- config/rbac/cluster_role.yaml
- helmcharts/next/templates/cluster_role.yaml
Update `next` bundle
N/A
N/A
N/A
> chore: Update `next` bundle

- pkg/deploy/migration/on-reconcile-one-time-migration.go
Don't include `networkingv1` API in migration process if it is not an OpenShift
N/A
https://github.com/eclipse/che/issues/20647
N/A
> fix: migration for OCP 3.11

- .github/bin/common.sh
- Makefile
Reuse MakeFile chectl-templ function in the CI tests.
None. Improvements.
> fix: Reuse MakeFile chectl-templ function in the CI tests.

- .github/workflows/release-community-operator-PRs.yml
Remove platform option from creation community operators PR
N/A
https://github.com/eclipse/che/issues/20668
N/A
> fix: Remove platform option from creation community operators PR

- controllers/che/checluster_controller.go
- controllers/che/checluster_controller_test.go
- controllers/che/checluster_validator.go
- pkg/deploy/consolelink/consolelink.go
- pkg/deploy/consolelink/consolelink_test.go
- pkg/deploy/dashboard/dashboard.go
- pkg/deploy/dashboard/dashboard_test.go
- pkg/deploy/dev-workspace/dev_workspace.go
- pkg/deploy/devfileregistry/devfileregistry.go
- pkg/deploy/gateway/gateway.go
- pkg/deploy/identity-provider/identity_provider_reconciler.go
- pkg/deploy/image-puller/imagepuller.go
- pkg/deploy/image-puller/imagepuller_test.go
- pkg/deploy/migration/on-reconcile-one-time-migration.go
- pkg/deploy/openshift-oauth/openshiftoauth.go
- pkg/deploy/openshift-oauth/openshiftoauth_user.go
- pkg/deploy/openshift-oauth/openshiftoauth_user_test.go
- pkg/deploy/pluginregistry/pluginregistry.go
- pkg/deploy/postgres/postgres.go
- pkg/deploy/rbac/gateway_permissions.go
- pkg/deploy/rbac/rbac.go
- pkg/deploy/rbac/workspace_permissions.go
- pkg/deploy/reconcile_manager.go
- pkg/deploy/reconcile_manager_test.go
- pkg/deploy/server/chehost_reconciler.go
- pkg/deploy/server/default_values_reconciler.go
- pkg/deploy/server/server_reconciler.go
- pkg/deploy/tls/certificates.go
- pkg/deploy/tls/tls_secret.go
Refactors component's finalizers in order to not to hung Che deletion if an error happen in one of the finalizers. 
New behavior logs all errors in all fnalizers, but do not stop current reconcile loop. If at least one error happened at least in one finalizer, a new reconcile loop is queued.
N/A
N/A
N/A, refactoring
> refactor: Do not reconcile on any error inside finalizers

- .github/bin/common.sh
Update catalog version to deploy on OCP 4.9
N/A
Fix `ci/prow/v9-stable-to-nightly` check
N/A
> fix: catalog version to deploy on OCP 4.9

- bundle/next-all-namespaces/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- bundle/next/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- helmcharts/next/templates/manager.yaml
Update next bundles
Fix broken 7.41.0 release
```bash
EOF
```
> fix: Update next bundles

- bundle/next/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- config/rbac/cluster_role.yaml
- helmcharts/next/templates/cluster_role.yaml
- pkg/deploy/identity-provider/identity_provider_reconciler.go
Requeue reconcile for identity provider provioning
N/A
https://github.com/eclipse/che/issues/20866
> fix: Requeue reconcile for identity provider provioning

- bundle/next/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- config/samples/org.eclipse.che_v1_checluster.yaml
- helmcharts/next/templates/org.eclipse.che_v1_checluster.yaml
Restore tlsSupport field in CheCluster CR sample
N/A
https://github.com/eclipse/che/issues/20866
> fix: Restore tlsSupport field in CheCluster CR sample

- api/v1/checluster_types.go
- bundle/next/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- bundle/next/eclipse-che-preview-openshift/manifests/org_v1_che_crd.yaml
- config/crd/bases/org_v1_che_crd-v1beta1.yaml
- config/crd/bases/org_v1_che_crd.yaml
- helmcharts/next/crds/org_v1_che_crd.yaml
Currently, there is only support for uri plug-in references, and no support for id plug-in references (https://github.com/eclipse/che/issues/20990). This PR updates the documentation to reflect this.
> fix: Update workspacesDefaultPlugins doc

- make-release.sh
Add helmchart files to index before commiting.
N/A
N/A
N/A
> fix: releasing helmcharts

- .ci/cico_updates_openshift.sh
- .github/bin/common.sh
- .github/bin/minikube/test-upgrade-from-stable-to-stable.sh
Fixes test scripts
N/A
N/A
N/A
> fix: test scripts

- olm/release-olm-files.sh
don't remove spec.devWorspace field from CheCluster sample
N/A
https://github.com/eclipse/che/issues/21021
N/A
> fix: don't remove spec.devWorspace field from CheCluster sample

- bundle/next/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- helmcharts/next/templates/manager.yaml
Revert che-operator memory limit from 5 GiB to 256 MiB
N/A
https://issues.redhat.com/browse/CRW-2525
N/A
> chore: Revert che-operator memory limit from 5 GiB to 256 MiB

- .github/workflows/codecov.yml
It fixed Codecov report submitted which has not been updates for 9 months
https://app.codecov.io/gh/eclipse-che/che-operator
N/A
N/A
N/A
> fix: Codecov report

- bundle/next-all-namespaces/eclipse-che-preview-openshift/metadata/dependencies.yaml
- bundle/tech-preview-stable-all-namespaces/eclipse-che-preview-openshift/metadata/dependencies.yaml
Change-Id: I72c1f7f4cc3d3672030e32c02c2bdd08c15185ca
N/A
see https://github.com/eclipse-che/che-operator/commit/9a5a2ef2db94045d80931c1e10eea0fdc54544f9
N/A
> fix: update the required DWO version to v0.11.0

- pkg/deploy/defaults.go
Ignore internal backup server image if it is missed in env
Prerequisite for https://github.com/eclipse-che/che-operator/pull/1300
N/A
https://github.com/eclipse/che/issues/21006
N/A
> chore: Ignore internal backup server image if it is missed in env

- .github/bin/common.sh
Deploy DWO next version from next channel
N/A
N/A
N/A
> fix: Deploy DWO next version from next channel

- api/conversion.go
- api/conversion_test.go
- controllers/devworkspace/state.go
- pkg/deploy/dev-workspace/dev_workspace_utils.go
Remove code depending on `devworkspace.enable` field
https://github.com/eclipse/che/issues/21166
N/A
> fix: Remove code depending on devworkspace.enable field

- controllers/devworkspace/controller.go
- controllers/devworkspace/controller_test.go
- controllers/devworkspace/solver/che_routing_test.go
- controllers/usernamespace/controller_test.go
- controllers/usernamespace/init_test.go
- controllers/usernamespace/namespacecache_test.go
- pkg/deploy/consolelink/consolelink.go
- pkg/deploy/dashboard/dashboard.go
- pkg/deploy/dashboard/dashboard_deployment_test.go
- pkg/deploy/dashboard/deployment_dashboard.go
- pkg/deploy/data_types.go
- pkg/deploy/devfileregistry/devfileregistry_test.go
- pkg/deploy/expose/expose.go
- pkg/deploy/gateway/gateway.go
- pkg/deploy/gateway/gateway_test.go
- pkg/deploy/gateway/oauth_proxy.go
- pkg/deploy/identity-provider/identity_provider_reconciler.go
- pkg/deploy/server/chehost_reconciler.go
- pkg/deploy/server/server_configmap.go
- pkg/deploy/server/server_configmap_test.go
- pkg/deploy/server/server_reconciler.go
- pkg/deploy/test_util.go
- pkg/deploy/tls/tls_utils.go
- pkg/util/util.go
Don't update chehost in CheCluster spec. Use `Status.CheUrl` instead.
N/A
Prerequisite for https://github.com/eclipse/che/issues/20758
N/A
> chore: don't update chehost in CheCluster spec

- api/v1/checluster_types.go
- pkg/deploy/consolelink/consolelink.go
- pkg/deploy/consolelink/consolelink_test.go
- pkg/deploy/dashboard/dashboard.go
- pkg/deploy/dashboard/dashboard_deployment_test.go
- pkg/deploy/dashboard/deployment_dashboard.go
- pkg/deploy/data_types.go
- pkg/deploy/devfileregistry/devfileregistry_test.go
- pkg/deploy/expose/expose.go
- pkg/deploy/gateway/oauth_proxy.go
- pkg/deploy/identity-provider/identity_provider_reconciler.go
- pkg/deploy/server/chehost_reconciler.go
- pkg/deploy/server/chehost_reconciler_test.go
- pkg/deploy/server/server_configmap.go
- pkg/deploy/server/server_configmap_test.go
- pkg/deploy/server/server_reconciler.go
- pkg/deploy/server/server_reconciler_test.go
- pkg/deploy/test_util.go
- pkg/deploy/tls/tls_utils.go
Improve handling CheHost field
N/A
Prerequisite for https://github.com/eclipse/che/issues/20758
N/A
> chore: Improve handling CheHost field

- Makefile
- api/v2alpha1/zz_generated.deepcopy.go
- bundle/next/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- helmcharts/next/templates/manager.yaml
- pkg/deploy/defaults.go
- pkg/deploy/defaults_test.go
- pkg/deploy/image-puller/imagepuller_test.go
Remove jwt-proxy and plugin broker images
N/A
https://issues.redhat.com/browse/CRW-2830
N/A
> chore: Remove jwt-proxy and plugin broker images

- make-release.sh
- pkg/deploy/image-puller/imagepuller.go
Clean up removing plugin brokers images
N/A
N/A
N/A
> fix: Clean up removing plugin brokers images

- pkg/deploy/dashboard/rbac.go
Cherry pick changes from https://github.com/eclipse-che/che-operator/pull/1304 to the 7.42.x branch
This is required for https://github.com/eclipse-che/che-dashboard/pull/478, which depends on the list CheCluster RBAC from #1304
N/A
Required for https://github.com/eclipse-che/che-dashboard/pull/478
> fix: backport #1304 to 7.42.x

- .github/bin/common.sh
- Dockerfile
- bundle/next/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- helmcharts/next/templates/manager.yaml
Update from ubi8-minimal:8.5-240 to ubi8-minimal:8.5-240.1648458092
> chore: Update from ubi8-minimal:8.5-240 to ubi8-minimal:8.5-240.1648458092

- pkg/deploy/deployment.go
- pkg/deploy/gateway/gateway.go
If operator failed to sync (update) deployment, then it tries to delete and create it again.
It make sense when immutable field is updated (for instance `spec.selector`)
N/A
https://issues.redhat.com/browse/CRW-2892
```bash
chectl server:deploy --installer operator --platform minikube
chectl server:update --che-operator-image abazko/operator:test
```
> fix: Allow to sync deployments when selector changed

- bundle/next/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- helmcharts/next/templates/manager.yaml
- pkg/deploy/dev-workspace/dev_workspace.go
- pkg/deploy/dev-workspace/dev_workspace_test.go
- pkg/deploy/dev-workspace/dev_workspace_utils.go
- Use `nonCachingClient` to list DWO CSV in the `operator-namespace` only
N/A
https://issues.redhat.com/browse/CRW-2740
N/A
> fix: Use `nonCachingClient` to list DWO CSV in the `operator-namespace` only

- controllers/usernamespace/controller.go
- controllers/usernamespace/namespacecache.go
- controllers/usernamespace/namespacecache_test.go
Backport of issue https://github.com/eclipse/che/issues/21327 fixed in https://github.com/eclipse-che/che-operator/pull/1359 to 7.46.x. branch.
n/a
https://github.com/eclipse/che/issues/21327
n/a
> Backport che 21327 to 7.46.x

- api/v1/checluster_types.go
Change-Id:...
fix: [RHDEVDOCS-4042](https://issues.redhat.com//browse/RHDEVDOCS-4042) (7.46.x)
Change-Id: I2ab62eb8975507c37255c79386a0ea3a83f91c03
N/A
N/A
> fix: RHDEVDOCS-4042 (7.46.x)

- controllers/usernamespace/controller.go
- controllers/usernamespace/controller_test.go
`$TITLE`
N/A
eclipse/che#21327
#1370
Same as #1370
> Cherry-pick #1370 into 7.46.x branch

- pkg/deploy/route.go
- pkg/deploy/route_test.go
Make Eclipse Che url shorter
N/A
https://github.com/eclipse/che/issues/20998
N/A
> chore: Make Eclipse Che url shorter

- pkg/deploy/route.go
Set Eclipse Che url to eclipse-che.<domain> on OpenShift cluster
N/A
https://github.com/eclipse/che/issues/20998
N/A
> fix: set Eclipse Che url to eclipse-che.<domain> on OpenShift cluster

- Makefile
fix: Downloading opm and operator-sdk tools
N/A
N/A
N/A
> fix: Downloading opm and operator-sdk tools

- pkg/common/operator-defaults/defaults.go
Remove unused codebase
N/A
N/A
```bash
EOF
```
> chore: remove unused codebase

- api/v2/checluster_types.go
- bundle/next/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- bundle/next/eclipse-che-preview-openshift/manifests/org.eclipse.che_checlusters.yaml
- config/crd/bases/org.eclipse.che_checlusters.yaml
- config/manifests/bases/che-operator.clusterserviceversion.yaml
- deploy/deployment/kubernetes/combined.yaml
- deploy/deployment/kubernetes/objects/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
- deploy/deployment/openshift/combined.yaml
- deploy/deployment/openshift/objects/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
- helmcharts/next/crds/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
2nd proofreading of api/v2/checluster_types.go (grammar, interpunction, clarity etc.)
https://issues.redhat.com/browse/RHDEVDOCS-4053
please check edited content
```bash
EOF
```
> 2nd proofreading of api/v2/checluster_types.go (grammar, interpunction, clarity etc.)

- api/v2/checluster_types.go
- bundle/next/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- bundle/next/eclipse-che-preview-openshift/manifests/org.eclipse.che_checlusters.yaml
- config/crd/bases/org.eclipse.che_checlusters.yaml
- deploy/deployment/kubernetes/combined.yaml
- deploy/deployment/kubernetes/objects/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
- deploy/deployment/openshift/combined.yaml
- deploy/deployment/openshift/objects/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
- helmcharts/next/crds/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
fix: deployment.container -> deployment.containers
N/A
N/A
N/A
> fix: deployment.container -> deployment.containers

- .ci/oci-nightly-update.sh
- .ci/openshift-ci/Dockerfile
- .github/workflows/build-catalog-and-bundle-images.yaml
- .github/workflows/release-community-operator-PRs.yml
- .github/workflows/release.yml
- make-release.sh
fix: Operator update on OpenShift test
N/A
N/A
N/A
> fix: Operator update on OpenShift test

- pkg/common/test/utils.go
- pkg/deploy/consolelink/consolelink.go
- pkg/deploy/consolelink/consolelink_test.go
Sync ConsoleLink
N/A
https://github.com/eclipse/che/issues/21489
N/A
> fix: sync ConsoleLink

- helmcharts/stable/Chart.yaml
- helmcharts/stable/README.md
Signed-off-by: Masaki Muranaka <monaka@monami-ya.com>
Fixes typo in Chart.yaml .
It looks CRD version in helmcharts/stable is v1. 
None.
None.
> fix(helmcharts/stable): It should not be `v2` but `v1` the version of CheCluster in the stable chart.

- helmcharts/stable/values.yaml
Signed-off-by: Masaki Muranaka <monaka@monami-ya.com>
Removes unused variables in values.yaml .
None
```
cd helmcharts/stable
helm lint .
==> Linting .
[INFO] Chart.yaml: icon is recommended
1 chart(s) linted, 0 chart(s) failed
```
```bash
$ helm template . > /dev/null
$
```
> chore(helmcharts/stable): Remove unused values in values.yaml.

- olm/release-olm-files.sh
> fix: release script

- pkg/deploy/gateway/oauth_proxy.go
- pkg/deploy/identity-provider/identity_provider_reconciler.go
- pkg/deploy/identity-provider/identity_provider_reconciler_test.go
- pkg/deploy/identity-provider/identity_provider_util.go
fix: Get OAuthClient by its name (if defined) instead of label selector
N/A
https://issues.redhat.com/browse/CRW-2648
N/A
> fix: Get OAuthClient by its name instead of label selector

- Makefile
- bundle/next/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- config/rbac/cluster_role.yaml
- deploy/deployment/kubernetes/combined.yaml
- deploy/deployment/kubernetes/objects/che-operator.ClusterRole.yaml
- deploy/deployment/openshift/combined.yaml
- deploy/deployment/openshift/objects/che-operator.ClusterRole.yaml
- helmcharts/next/templates/che-operator.ClusterRole.yaml
Add permissions to update/create project
N/A
https://github.com/eclipse/che/issues/21391
N/A
> fix: Add permissions to update/create project

- make-release.sh
> fix: make-release.sh

- olm/release-olm-files.sh
fix: release-olm-files.sh script
> fix: release-olm-files.sh script

- make-release.sh
fix: Add changed files before committing
> release: Add changed files before committing

- Dockerfile
Change-Id: I876fb042eb3bbea2a8ee311d6cfdd491a89ddd5a
> chore: Update from ubi8/go-toolset:1.17.10 to ubi8/go-toolset:1.17.10-4

- Dockerfile
Change-Id: I80e76c2906717a634c985d16c200e3cbc9cbc7c3
> chore: Update from ubi8-minimal:8.6 to ubi8-minimal:8.6-854

- pkg/deploy/pluginregistry/pluginregistry_configmap.go
Propagate START_OPENVSX env var to plugin registry
N/A
https://github.com/eclipse/che/issues/21611
N/A
> chore: Propagate START_OPENVSX env var to plugin registry

- Dockerfile
Change-Id: I48538b9cb78f9824fa36f8bc1fa28c8ce1750806
> chore: Update from ubi8/go-toolset:1.17.10-4 to ubi8/go-toolset:1.17.12-3

- Dockerfile
Change-Id: I43b5ab5033c817b5f33176d9ebcdba0770ba9f7a
> chore: Update from ubi8-minimal:8.6-854 to ubi8-minimal:8.6-902

- .ci/oci-upgrade-from-stable-to-next.sh
> fix: OpenShift test script

- .ci/oci-common.sh
- .ci/oci-devworkspace-happy-path.sh
- .ci/oci-operator.sh
- .ci/oci-single-host.sh
- .ci/oci-upgrade-from-stable-to-next.sh
- .github/bin/common.sh
- Makefile
- olm/testCatalog.sh
- olm/testUpdate.sh
> chore: Rework test scripts

- build/scripts/oc-tests/oc-common.sh
- build/scripts/oc-tests/oc-test-operator.sh
- build/scripts/oc-tests/oc-test-upgrade-from-stable-to-next.sh
- pkg/deploy/pluginregistry/pluginregistry_deployment.go
fix: Collect Eclipse Che logs after tests on OpenShift
> fix: Collect Eclipse Che logs after tests on OpenShift

- Makefile
- build/scripts/oc-tests/oc-common.sh
- build/scripts/oc-tests/oc-test-operator.sh
- build/scripts/olm/testCatalog.sh
- build/scripts/olm/testUpdate.sh
chore: Rework oc test scripts to build bundle from sources
> chore: Rework oc test scripts to build bundle from sources

- build/scripts/release/release-olm-files.sh
> fix: release-olm-files.sh

- build/scripts/olm/testCatalogFromSources.sh
fix: testCatalogFromSources.sh, use  if default path does not exist
> fix: testCatalogFromSources.sh, use  if default path does not exist

- build/scripts/olm/testCatalogFromSources.sh
fix: set annotation openshift.io/scc=anyuid for che-registry test pod
> fix: set annotation openshift.io/scc=anyuid for che-registry test pod

- build/scripts/minikube-tests/test-operator.sh
- build/scripts/olm/testUpdate.sh
> fix: test-operator.sh

- build/scripts/olm/testUpdate.sh
> fix: testUpdate.sh

- .github/PULL_REQUEST_TEMPLATE.md
- Makefile
- build/scripts/oc-tests/oc-common.sh
- bundle/next/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
* fix: `make run` and `make debug` commands
* fix: `testUpdate.sh`
* fix: PR template
N/A
N/A
N/A
> fix: debug operator

- bundle/next/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
> chore: Update dev-resources version

- bundle/next/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
> chore: Update dev-resources

- Makefile
- build/scripts/olm/testUpdate.sh
- bundle/next/eclipse-che-preview-openshift/manifests/che-operator-service_v1_service.yaml
- bundle/next/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- config/openshift/olm/kustomization.yaml
- config/openshift/olm/patches/extralabels_in_service.yaml
ReAdd che-operator-service into OLM bundle
N/A
https://github.com/eclipse/che/issues/21649
N/A
> fix: ReAdd che-operator-service into OLM bundle

- bundle/next/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
> chore: Update dev resources

- controllers/usernamespace/controller.go
fix: Don't add empty 'githost' key in 'git-tls-creds' ConfigMap since it leads to failure in project cloning.
N/A
https://github.com/eclipse/che/issues/21754
N/A
> fix: Don't add empty 'githost' key in 'git-tls-creds' ConfigMap

- api/v2/checluster_types.go
- bundle/next/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- bundle/next/eclipse-che-preview-openshift/manifests/org.eclipse.che_checlusters.yaml
- config/crd/bases/org.eclipse.che_checlusters.yaml
- deploy/deployment/kubernetes/combined.yaml
- deploy/deployment/kubernetes/objects/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
- deploy/deployment/openshift/combined.yaml
- deploy/deployment/openshift/objects/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
- helmcharts/next/crds/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
chore: disableContainerBuildCapabilities=true default
N/A
https://github.com/eclipse/che/issues/21752
N/A
> chore: Set `disableContainerBuildCapabilities: true` by default

- bundle/next/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
- config/rbac/cluster_role.yaml
- controllers/usernamespace/controller.go
- controllers/usernamespace/controller_test.go
- controllers/usernamespace/namespacecache.go
- deploy/deployment/kubernetes/combined.yaml
- deploy/deployment/kubernetes/objects/che-operator.ClusterRole.yaml
- deploy/deployment/openshift/combined.yaml
- deploy/deployment/openshift/objects/che-operator.ClusterRole.yaml
- helmcharts/next/templates/che-operator.ClusterRole.yaml
- pkg/common/constants/constants.go
- pkg/deploy/clusterrole.go
- pkg/deploy/clusterrolebinding.go
- pkg/deploy/container-build/container_build.go
- pkg/deploy/container-build/container_build_test.go
- pkg/deploy/rolebinding.go
feat: Automatically add the container build SCC to users if containerBuildCapability is enabled
https://github.com/eclipse/che/issues/21769
N/A
> feat: Automatically add the container build SCC to users if containerBuildCapability is enabled

- controllers/che/checluster_controller.go
Register ContainerBuildReconciler only for OpenShift
N/A
https://github.com/eclipse/che/issues/21768
N/A
> fix: Register ContainerBuildReconciler only for OpenShift

- api/checluster_webhook_test.go
fix: tests for downstream project
N/A
https://github.com/eclipse/che/issues/21779
N/A
> fix: checluster_webhook tests

- README.md
chore: make badges links to the workflow itself (#21790)
Change-Id: I38c7b94ca9d68e277e248ddce1738bc9ed4ceb50
N/A
N/A
> chore: make badges links to the workflow itself (#21790)

- build/scripts/olm/release-catalog.sh
> fix: release-catalog.sh

- build/scripts/minikube-tests/test-helm.sh
- build/scripts/minikube-tests/test-operator.sh
- build/scripts/minikube-tests/test-upgrade-from-stable-to-next.sh
- build/scripts/minikube-tests/test-upgrade-from-stable-to-stable.sh
- bundle/next/eclipse-che/manifests/che-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- deploy/deployment/kubernetes/combined.yaml
- deploy/deployment/kubernetes/objects/che-operator.Deployment.yaml
- deploy/deployment/openshift/combined.yaml
- deploy/deployment/openshift/objects/che-operator.Deployment.yaml
- helmcharts/next/templates/che-operator.Deployment.yaml
Update oauth2-proxy image `quay.io/oauth2-proxy/oauth2-proxy:v7.2.0` -> `quay.io/oauth2-proxy/oauth2-proxy:v7.4.0`
N/A
https://github.com/eclipse/che/issues/21861
https://github.com/eclipse-che/che-operator/#deploy-che-operator
> chore: Update oauth2-proxy image

- .github/workflows/release-che-docs.yml
- .github/workflows/release-chectl.yml
- .github/workflows/release-community-operator-PRs.yml
- .github/workflows/release.yml
Change-Id:...
chore: #21763 - bump to py 3.9
Change-Id: I14b7eba9596a395313f74fa44c9a99e48b85ef51
N/A
N/A
> chore: #21763 - bump to py 3.9

- build/scripts/oc-tests/oc-test-happy-path.sh
fix: Run HappyPath tests
N/A
https://github.com/eclipse/che/issues/21836
N/A
> fix: Run HappyPath tests

- bundle/next/eclipse-che/manifests/che-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- deploy/deployment/kubernetes/combined.yaml
- deploy/deployment/kubernetes/objects/che-operator.Deployment.yaml
- deploy/deployment/openshift/combined.yaml
- deploy/deployment/openshift/objects/che-operator.Deployment.yaml
- helmcharts/next/templates/che-operator.Deployment.yaml
chore: Update Traefik to 2.9.6 version
N/A
https://github.com/eclipse/che/issues/21869
N/A
> chore: Update Traefik to 2.9.6 version

- bundle/next/eclipse-che/manifests/che-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- deploy/deployment/kubernetes/combined.yaml
- deploy/deployment/kubernetes/objects/che-operator.Deployment.yaml
- deploy/deployment/openshift/combined.yaml
- deploy/deployment/openshift/objects/che-operator.Deployment.yaml
- helmcharts/next/templates/che-operator.Deployment.yaml
chore: Update quay.io/brancz/kube-rbac-proxy from 0.11.0 to 0.13.1
N/A
https://github.com/eclipse/che/issues/21877
N/A
> chore: Update quay.io/brancz/kube-rbac-proxy from 0.11.0 to 0.13.1

- .github/workflows/release.yml
Buildx 0.10.0 seems to have broken the dashboard release process so setting it to v0.9.1 across the board for consistency and to avoid the same problem elsewhere.
https://github.com/eclipse/che/issues/21954
```bash
EOF
```
> Set buildx to v0.9.1

- api/checluster_conversion_from_test.go
- api/checluster_conversion_to_test.go
- api/checluster_webhook_test.go
- api/v1/checluster_conversion_from.go
- api/v1/checluster_conversion_to.go
- api/v1/checluster_types.go
- api/v2/checluster_types.go
- api/v2/checluster_webhook.go
- bundle/next/eclipse-che/manifests/che-operator.clusterserviceversion.yaml
- bundle/next/eclipse-che/manifests/org.eclipse.che_checlusters.yaml
- config/crd/bases/org.eclipse.che_checlusters.yaml
- config/manifests/bases/che-operator.clusterserviceversion.yaml
- deploy/deployment/kubernetes/combined.yaml
- deploy/deployment/kubernetes/objects/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
- deploy/deployment/openshift/combined.yaml
- deploy/deployment/openshift/objects/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
- helmcharts/next/crds/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
- pkg/common/constants/constants.go
- pkg/deploy/server/server_deployment.go
- pkg/deploy/server/server_deployment_test.go
* configure disable subdomain isolation via secret
* deprecate `endpoint` in favor of `che.eclipse.org/scm-server-endpoint` annotation
* deprecate `disableSubdomainIsolation` in favor of `che.eclipse.org/scm-github-disable-subdomain-isolation` annotation
N/A
https://github.com/eclipse/che/issues/21986
N/A
> feat: Configure disable subdomain isolation via secret

- .github/workflows/release.yml
Use latest buildx version in release workflow (like the rest of the workflows where buildx is used)
https://github.com/eclipse/che/issues/21954
```bash
EOF
```
> chore: unpin buildx 0.9.1 version

- Makefile
- api/v2/checluster_types.go
- build/scripts/oc-tests/oc-test-happy-path.sh
- build/scripts/oc-tests/oc-test-upgrade-from-stable-to-next.sh
- build/scripts/olm/test-catalog-from-sources.sh
- build/scripts/olm/test-catalog.sh
- bundle/next/eclipse-che/manifests/che-operator.clusterserviceversion.yaml
- bundle/next/eclipse-che/manifests/org.eclipse.che_checlusters.yaml
- config/crd/bases/org.eclipse.che_checlusters.yaml
- deploy/deployment/kubernetes/combined.yaml
- deploy/deployment/kubernetes/objects/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
- deploy/deployment/openshift/combined.yaml
- deploy/deployment/openshift/objects/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
- helmcharts/next/crds/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
feat: Enable build capabilities by defaut
N/A
https://github.com/eclipse/che/issues/22032
N/A
> feat: Enable build capabilities by default

- api/v2/checluster_webhook.go
Disables build capabilities on k8s cluster otherwise it causes workspace startup to fail
N/A
https://github.com/eclipse/che/issues/22032
N/A
> fix: Disable build capabilities on k8s cluster

- bundle/next/eclipse-che/manifests/che-operator.clusterserviceversion.yaml
- pkg/deploy/sync.go
- pkg/deploy/tls/certificates.go
- pkg/deploy/tls/certificates_test.go
It turned out, that sync function rewrite labels and annotations for the object.
Which can cause issue with endless syncing the same object since labels will be different all the times.
Added reproducible tests.
N/A
https://github.com/eclipse/che/issues/22108
N/A
> fix: sync should not update labels and annotations for an object

- pkg/common/operator-defaults/defaults.go
- pkg/common/test/utils.go
- pkg/deploy/dashboard/dashboard_deployment_test.go
- pkg/deploy/defaults_test.go
- pkg/deploy/migration/checluster-defaults-cleaner_test.go
chore: Adapt tests for downstream
N/A
https://issues.redhat.com/browse/CRW-4077
N/A
> chore: Adapt tests for downstream

- .ci/openshift-ci/Dockerfile
fix: Dockerfile for OpenShift CI
> fix: Dockerfile for OpenShift CI

- build/scripts/oc-tests/oc-test-happy-path.sh
Fixed outdated npm script name 
n/a
https://github.com/eclipse/che/issues/22153
/test
> fix: updated HAPPY_PATH_SUITE in oc-test-happy-path.sh

- api/v2/checluster_types.go
- bundle/next/eclipse-che/manifests/che-operator.clusterserviceversion.yaml
- bundle/next/eclipse-che/manifests/org.eclipse.che_checlusters.yaml
- config/crd/bases/org.eclipse.che_checlusters.yaml
- deploy/deployment/kubernetes/combined.yaml
- deploy/deployment/kubernetes/objects/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
- deploy/deployment/openshift/combined.yaml
- deploy/deployment/openshift/objects/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
- helmcharts/next/crds/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
- pkg/deploy/gateway/oauth_proxy.go
- pkg/deploy/ingress.go
- pkg/deploy/ingress_test.go
feat: allow to specify IngressClassName
N/A
https://github.com/eclipse/che/issues/22175
N/A
> feat: allow to specify IngressClassName

- pkg/common/constants/constants.go
PR https://github.com/eclipse-che/che-operator/pull/1639 added configurable fields for the Che Gateway container. However, in translating the previous constants into default values, an error resulted in the default Che Gateway CPU limit/request being much smaller than before, and I missed this change in review.
This PR resets these default values to the previous hard-coded constants.
N/A
Potentially related: https://github.com/eclipse/che/issues/22163
```bash
EOF
```
[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.m …
> Update Che Gateway default resources to match previous values

- pkg/common/constants/constants.go
- pkg/deploy/gateway/oauth_proxy.go
Allow to configure OpenShift OAuth scope
N/A
https://github.com/eclipse/che/issues/22038
N/A
> feat: Allow to configure OpenShift OAuth scope

- pkg/deploy/deployment.go
- pkg/deploy/deployment_test.go
fix: NPE in deploy.OverrideDeployment func
N/A
https://github.com/eclipse/che/issues/22198
N/A
> fix: NPE in deploy.OverrideDeployment func

- pkg/deploy/registry/registry_deployment.go
https://github.com/eclipse/che/issues/22233
N/A
fix: probePath for plugin and devfile registries deployments
N/A
> fix: probePath for plugin and devfile registries deployments

- pkg/deploy/server/rbac.go
Add permissions to user to update and patch deployment/service/pvc
N/A
https://github.com/eclipse/che/issues/22235
N/A
> chore: Add permissions to user to update and patch deployment/service/pvc

- bundle/next/eclipse-che/manifests/che-operator.clusterserviceversion.yaml
- config/rbac/cluster_role.yaml
- deploy/deployment/kubernetes/combined.yaml
- deploy/deployment/kubernetes/objects/che-operator.ClusterRole.yaml
- deploy/deployment/openshift/combined.yaml
- deploy/deployment/openshift/objects/che-operator.ClusterRole.yaml
- helmcharts/next/templates/che-operator.ClusterRole.yaml
fix: Add permissions to update ingress k8s resources
N/A
https://github.com/eclipse/che/issues/22166
N/A
> fix: Add permissions to update `ingress` k8s resources

- bundle/next/eclipse-che/manifests/che-operator.clusterserviceversion.yaml
- config/rbac/cluster_role.yaml
- controllers/devworkspace/solver/che_routing.go
- controllers/devworkspace/solver/che_routing_test.go
- controllers/devworkspace/solver/endpoint_exposer.go
- controllers/devworkspace/solver/endpoint_strategy.go
- deploy/deployment/kubernetes/combined.yaml
- deploy/deployment/kubernetes/objects/che-operator.ClusterRole.yaml
- deploy/deployment/openshift/combined.yaml
- deploy/deployment/openshift/objects/che-operator.ClusterRole.yaml
- helmcharts/next/templates/che-operator.ClusterRole.yaml
Cherry pick of https://github.com/eclipse-che/che-operator/pull/1672
> Cherry-pick PR-1672 to 7.67.x branch

- controllers/devworkspace/solver/che_routing_test.go
- controllers/devworkspace/solver/endpoint_strategy.go
Cherry pick for https://github.com/eclipse-che/che-operator/pull/1699
> Fix subdomain for public endpoint urls

- controllers/devworkspace/solver/che_routing.go
- controllers/devworkspace/solver/che_routing_test.go
- controllers/devworkspace/solver/endpoint_strategy.go
Backport of https://github.com/eclipse-che/che-operator/pull/1702
> [Backport] Use legacy routes if subdomain is too long

- devfile.yaml
chore(devfile.yaml): Simplify devfile.yaml
> chore(devfile.yaml): Simplify devfile.yaml

- api/v2/checluster_types.go
- go.mod
- pkg/deploy/migration/checluster-defaults-cleaner.go
- pkg/deploy/migration/checluster-defaults-cleaner_test.go
- pkg/deploy/migration/checluster-defaults-cleanupfunc.go
fix: Don't clean up `openVSXURL` on installation
N/A
https://github.com/eclipse/che/issues/22322
N/A
> fix: Don't clean up `openVSXURL` on installation

- api/v2/checluster_webhook.go
- pkg/deploy/migration/checluster-defaults-cleaner_test.go
fix: Disable container build capabilities on Kubernetes
Regression causes by https://github.com/eclipse-che/che-operator/pull/1716
N/A
https://github.com/eclipse/che/issues/22322
N/A
`
> fix: Disable container build capabilities on Kubernetes

- .github/workflows/release-next-catalog-and-operator-image.yaml
fix: Build operator image once before building catalog sources
N/A
https://github.com/eclipse/che/issues/21445
N/A
> fix: Build operator image once before building catalog sources

- build/scripts/olm/release-catalog.sh
- bundle/next/eclipse-che/manifests/che-operator.clusterserviceversion.yaml
fix: Reference to a bundle image digest instead of tag
N/A
https://github.com/eclipse/che/issues/21445
N/A
> fix: Reference to a bundle image digest instead of tag

- pkg/deploy/migration/checluster-defaults-cleaner_test.go
> fix: Downstream tests

- Dockerfile
[CRW-4582](https://issues.redhat.com//browse/CRW-4582) FIPS support
Change-Id: I8256c4e773a89202041048f48b456b1022a66d9a
N/A
N/A
> CRW-4582 FIPS support

- build/scripts/olm/release-catalog.sh
feat: Add force flag to build catalog and bundle images
N/A
https://github.com/eclipse/che/issues/21445
N/A
> feat: Add force flag to build catalog and bundle images

- pkg/deploy/dashboard/rbac.go
chore: Allow che-dasbhoard SA to read ConfigMap in eclipse-che namespace
N/A
https://github.com/eclipse/che/issues/22429
N/A
> chore: Allow che-dasbhoard SA to read ConfigMap in eclipse-che namespace

- build/scripts/docker-run.sh
feat: Update `docker-run.sh` script
N/A
N/A
N/A
> feat: Update docker-run.sh script

- build/scripts/oc-tests/oc-test-happy-path.sh
* Switches prcheck test to SmokeTest
[Job logs](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/eclipse-che_che-operator/1763/pull-ci-eclipse-che-che-operator-main-v12-devworkspace-happy-path/1713647867152830464/artifacts/devworkspace-happy-path/devworkspace-happy-path/build-log.txt)
[run video](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/eclipse-che_che-operator/1763/pull-ci-eclipse-che-che-operator-main-v12-devworkspace-happy-path/1713647867152830464/artifacts/devworkspace-happy-path/devworkspace-happy-path/artifacts/e2e/output.webm)
[PROW CI log](https://prow.ci.openshift.org/log?container=test&id=1713647867152830464&job=pull-ci-eclipse-che-che-operator-main-v12-devworkspace-happy-path) …
> Updated PR-Check script to use SmokeTest

- .github/workflows/release.yml
Seems hub is no longer included in Ubuntu,  so installing it manually
https://github.com/eclipse-che/che-operator/actions/runs/6567496891
```bash
EOF
```
> Add hub to release.yml

- .github/workflows/release-chectl.yml
- .github/workflows/release-community-operator-PRs.yml
Change-Id:...
install hub and other deps
Change-Id: Ic7d07cec47251a763f1c10e75dce0c16a2b2e265
N/A
N/A
> install hub and other deps

- Dockerfile
Updates go-toolset used in the Dockerfile to 1.19.13-2
[CRW-4933](https://issues.redhat.com//browse/CRW-4933) (affected by the same CVE)
> Check in go changes for CRW-4933 to main

- Dockerfile
Downside of short sprints is if a release gets delayed I have to change the same thing into 3 branches...
> Check in go changes for CRW-4933 to 7.76

- Dockerfile
Automatically update rpms since some included in ubi8-minimal are out of date.
> Add auto-update for rpms in ubi8-minimal for CRW-4977

- .github/workflows/release-che-docs.yml
- .github/workflows/release-chectl.yml
- .github/workflows/release-community-operator-PRs.yml
- .github/workflows/release.yml
- build/scripts/release/make-release.sh
- build/scripts/release/prepare-community-operators-update.sh
https://github.com/eclipse/che/issues/22646
> Fix: Changing scripts to use gh instead of hub for Che #22646

- bundle/next/eclipse-che/manifests/che-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- deploy/deployment/kubernetes/combined.yaml
- deploy/deployment/kubernetes/objects/che-operator.Deployment.yaml
- deploy/deployment/openshift/combined.yaml
- deploy/deployment/openshift/objects/che-operator.Deployment.yaml
- helmcharts/next/templates/che-operator.Deployment.yaml
chore: Increase memory limits to 1Gi
N/A
https://issues.redhat.com/browse/CRW-5316
N/A
> chore: Increase memory limits to 1Gi

- build/scripts/release/prepare-community-operators-update.sh
Fix incorrect GH command
```bash
EOF
```
> fix: more fixes for gh command

- build/scripts/release/make-release.sh
- bundle/next/eclipse-che/manifests/che-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- deploy/deployment/kubernetes/combined.yaml
- deploy/deployment/kubernetes/objects/che-operator.Deployment.yaml
- deploy/deployment/openshift/combined.yaml
- deploy/deployment/openshift/objects/che-operator.Deployment.yaml
- helmcharts/next/templates/che-operator.Deployment.yaml
fix: use the latest configbump image
N/A
https://github.com/eclipse/che/issues/22767
N/A
> fix: use the latest configbump image

- bundle/next/eclipse-che/manifests/che-operator.clusterserviceversion.yaml
Somehow managed to misspell false. Fixing.
> Typo in 7.82.x

- bundle/next/eclipse-che/manifests/che-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- deploy/deployment/kubernetes/combined.yaml
- deploy/deployment/kubernetes/objects/che-operator.Deployment.yaml
- deploy/deployment/openshift/combined.yaml
- deploy/deployment/openshift/objects/che-operator.Deployment.yaml
- helmcharts/next/templates/che-operator.Deployment.yaml
```bash
spec: {}
EOF
```
```bash
```
```bash
```
> chore: Increase memory limit to 2Gi

- .ci/openshift-ci/Dockerfile
- .github/workflows/minikube-test-helm.yaml
- .github/workflows/minikube-test-operator.yaml
- .github/workflows/minikube-test-upgrade-stable-to-next.yaml
- .github/workflows/minikube-test-upgrade-stable-to-stable.yaml
ci: replacing chectl installation scripts
N/A
https://github.com/eclipse-che/che/issues/22921
```bash
spec: {}
EOF
```
```bash
```
```bash
```
> ci: replacing chectl installation scripts

- bundle/next/eclipse-che/manifests/che-operator.clusterserviceversion.yaml
- controllers/devworkspace/solver/che_routing.go
- pkg/deploy/gateway/gateway.go
- pkg/deploy/gateway/kube_rbac_proxy.go
- pkg/deploy/gateway/oauth_proxy.go
Configure probes for che-gateway containers
N/A
https://github.com/eclipse-che/che/issues/22786
```bash
spec: {}
EOF
```
```bash
```
```bash
```
> feat: Configure probes for che-gateway containers

- bundle/next/eclipse-che/manifests/che-operator.clusterserviceversion.yaml
- config/manifests/bases/che-operator.clusterserviceversion.yaml
fix: Documentation links
N/A
https://issues.redhat.com/browse/CRW-6352
```bash
spec: {}
EOF
```
```bash
```
```bash
```
> fix: Documentation links

- pkg/deploy/gateway/gateway.go
Fixes https://github.com/orgs/eclipse-che/projects/10?pane=issue&itemId=60861312
The 401/403 errors happen when these two steps happen back to back:
1. wss request happens that results in a 404 error.
2. A request that requires auth (provision POST request, pods GET request, devworkspace GET request, events GET request etc.) reuses the same TCP connection as the unsuccessful wss request.
The typical scenario where the 401/403 errors happen is when a user opens an editor, deletes the workspace, and leaves the editor open. Because the editor is left open, the websocket connection will be retried periodically. But since the workspace is deleted, the workspace's traefik config doesn't exist anymore, and the connection request would result in a 404.
This PR will add `Connection: Close` header …
> Close connection when traefik receives an unmatched request

- build/scripts/release/make-release.sh
> ci: fix make-release.sh

- .github/workflows/release.yml
> ci: release.yaml

- Makefile
- build/scripts/release/make-release.sh
> ci: make-release.sh

- bundle/next/eclipse-che/bundle.Dockerfile
ci: Update license header for bundle.Dockerfile
> ci: Update license header for bundle.Dockerfile

- pkg/deploy/dashboard/dashboard_deployment_test.go
- pkg/deploy/dashboard/deployment_dashboard.go
feat: Mount `CHE_DASHBOARD_INTERNAL_URL` into che-dashboard container
N/A
https://github.com/eclipse-che/che/issues/23026
```bash
spec: {}
EOF
```
```bash
```
```bash
```
> feat: Mount `CHE_DASHBOARD_INTERNAL_URL` into che-dashboard container

- devfile.yaml
```bash
spec: {}
EOF
```
```bash
```
```bash
```
> chore: Update devfile.yaml

- README.md
```bash
spec: {}
EOF
```
```bash
```
```bash
```
> chore: Update README.md with badges

- pkg/common/constants/constants.go
https://issues.redhat.com/browse/CRW-6889
Image - 
https://quay.io/repository/ibuziuk/che-operator?tab=tags&tag=[crw-6889](https://issues.redhat.com//browse/crw-6889)
```bash
spec: {}
EOF
```
```bash
```
```bash
```
> chore: bump memory limit for dashboard to 1Gi

- pkg/deploy/editors-definitions/editors_definitions.go
- pkg/deploy/editors-definitions/test-editors-definitions/devfile-broken.yaml
- pkg/deploy/editors-definitions/test-editors-definitions/devfile-empy.yaml
fix: Ignore empty editor definitions
N/A
https://github.com/eclipse-che/che/issues/23087
```bash
spec: {}
EOF
```
```bash
```
```bash
```
> fix: Ignore empty editor definitions

- .github/workflows/release-che-docs.yml
Fix docs release not being triggered due to incorrect branch parameter (and bash was supressing the failed curl request)
```bash
spec: {}
EOF
```
```bash
```
```bash
```
> fix: fix workflow for triggering docs release

- build/scripts/release/make-release.sh
Build and publish che operator image for linux/arm64 platforms to support running che-eclipse locally on machines such as Apple Silicon (M1) Macs
https://github.com/eclipse-che/che/issues/23128
verify that after this PR is accepted that che eclipse next version can be installed on an Apple Silicon Mac following the guide: https://eclipse.dev/che/docs/stable/administration-guide/installing-che-on-red-hat-openshift-local/ 
> fix: release container image for arm64 platform (#23128)

- .github/workflows/pr-check.yml
- .github/workflows/release-next-catalog-and-operator-image.yaml
- .github/workflows/release.yml
Build operator image next tag for linux/arm64 platform
N/A
https://github.com/eclipse-che/che/issues/23128
```bash
spec: {}
EOF
```
```bash
```
```bash
```
> feat: Build operator image next tag for linux/arm64 platform

- editors-definitions/che-pycharm-server-latest.yaml
- editors-definitions/che-pycharm-server-next.yaml
- editors-definitions/che-webstorm-server-latest.yaml
- editors-definitions/che-webstorm-server-next.yaml
It adds two tiles to the Dashboard - WebStorm and PyCharm editors- with remote development support via Gateway.
https://github.com/eclipse-che/che/issues/23057
```bash
spec: {}
EOF
```
```bash
```
```bash
```
> Add WebStorm and PyCharm via Gateway

- README.md
Trying to see if the prow happy path CI test is stable
n/a
n/a
n/a
> Do not merge: no-op commit to test prow CI

- editors-definitions/che-idea-server-latest.yaml
- editors-definitions/che-idea-server-next.yaml
- editors-definitions/che-pycharm-server-latest.yaml
- editors-definitions/che-pycharm-server-next.yaml
- editors-definitions/che-webstorm-server-latest.yaml
- editors-definitions/che-webstorm-server-next.yaml
Adds the `provider` attribute for the Jet Brains IDEs.
Mentions IDE version in the `version` attribute.
https://issues.redhat.com/browse/CRW-7547
```bash
spec: {}
EOF
```
```bash
```
```bash
```
> Adds the `provider` attribute for the Jet Brains IDEs and mention an IDE version

- bundle/next/eclipse-che/manifests/che-operator.clusterserviceversion.yaml
> chore: Update resources

- pkg/common/constants/constants.go
- pkg/deploy/server/server_configmap.go
- pkg/deploy/server/server_deployment.go
- pkg/deploy/server/server_deployment_test.go
Allow to configure 2 gitlab providers simultaneously
https://issues.redhat.com/browse/CRW-7142
See : https://github.com/eclipse-che/che-server/pull/731
> feat: Allow to configure 2 gitlab providers simultaneously

- editors-definitions/che-idea-server-latest.yaml
- editors-definitions/che-idea-server-next.yaml
- editors-definitions/che-pycharm-server-latest.yaml
- editors-definitions/che-pycharm-server-next.yaml
- editors-definitions/che-webstorm-server-latest.yaml
- editors-definitions/che-webstorm-server-next.yaml
Corrects the editor provider name.
```bash
spec: {}
EOF
```
```bash
```
```bash
```
> Correct the editor provider name

- editors-definitions/che-clion-server-latest.yaml
- editors-definitions/che-clion-server-next.yaml
Adds JetBrains CLion IDE as an editor option to the Dashboard.
```bash
spec: {}
EOF
```
```bash
```
```bash
```
> Add CLion IDE

- bundle/next/eclipse-che/manifests/che-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- deploy/deployment/kubernetes/combined.yaml
- deploy/deployment/kubernetes/objects/che-operator.Deployment.yaml
- deploy/deployment/openshift/combined.yaml
- deploy/deployment/openshift/objects/che-operator.Deployment.yaml
- helmcharts/next/templates/che-operator.Deployment.yaml
chore: Update OAuth2 proxy image to v7.6.0
N/A
https://github.com/eclipse-che/che/issues/23157
```bash
spec: {}
EOF
```
```bash
```
```bash
```
> chore: Update OAuth2 proxy image to v7.6.0

- bundle/next/eclipse-che/manifests/che-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- deploy/deployment/kubernetes/combined.yaml
- deploy/deployment/kubernetes/objects/che-operator.Deployment.yaml
- deploy/deployment/openshift/combined.yaml
- deploy/deployment/openshift/objects/che-operator.Deployment.yaml
- helmcharts/next/templates/che-operator.Deployment.yaml
chore: Update che-tls-secret-creator image
N/A
N/A
```bash
spec: {}
EOF
```
```bash
```
```bash
```
> chore: Update che-tls-secret-creator image

- api/v2/checluster_types.go
- api/v2/zz_generated.deepcopy.go
- bundle/next/eclipse-che/manifests/che-operator.clusterserviceversion.yaml
- bundle/next/eclipse-che/manifests/org.eclipse.che_checlusters.yaml
- config/crd/bases/org.eclipse.che_checlusters.yaml
- deploy/deployment/kubernetes/combined.yaml
- deploy/deployment/kubernetes/objects/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
- deploy/deployment/openshift/combined.yaml
- deploy/deployment/openshift/objects/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
- helmcharts/next/crds/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
```bash
spec: {}
EOF
```
```bash
```
```bash
```
> typo fixup in the CR description

- editors-definitions/che-code-server-latest.yaml
- editors-definitions/che-code-server-next.yaml
- fixes several typos in Che Code server editor definitions
- aligns the editor display name with JerBrains editor
https://github.com/eclipse-che/che/issues/23312, an addition to https://github.com/eclipse-che/che-operator/pull/1958
The result will be shown on the dashboard after update.
> chore: fix typo in Che Code Server editor definition

- .github/workflows/release-next-catalog-and-operator-image.yaml
fix: release-next-catalog-and-operator-image.yaml
N/A
N/A
```bash
spec: {}
EOF
```
```bash
```
```bash
```
> fix: release-next-catalog-and-operator-image.yaml

- .github/workflows/release-next-catalog-and-operator-image.yaml
- Makefile
- build/scripts/olm/release-catalog.sh
- bundle/next/eclipse-che/manifests/che-operator.clusterserviceversion.yaml
fix: Multiarch catalog and bundle builds
N/A
N/A
```bash
spec: {}
EOF
```
```bash
```
```bash
```
> fix: Multiarch catalog and bundle builds

- .github/workflows/release-next-catalog-and-operator-image.yaml
- build/scripts/olm/release-catalog.sh
- bundle/next/eclipse-che/manifests/che-operator.clusterserviceversion.yaml
chore: Allow to multi not multi-arch catalog and bundle images for testing purporse
N/A
N/A
```bash
spec: {}
EOF
```
```bash
```
```bash
```
> chore: Allow to multi not multi-arch catalog

- bundle/next/eclipse-che/manifests/che-operator.clusterserviceversion.yaml
- bundle/stable/eclipse-che/manifests/che-operator.clusterserviceversion.yaml
- config/manifests/bases/che-operator.clusterserviceversion.yaml
Sets the olm fips-compliant tag to false
https://issues.redhat.com/browse/CRW-8243
> CRW-8243 setting fips-compliant to false until CRW-7950 is resolved.

- editors-definitions/che-clion-server-latest.yaml
- editors-definitions/che-clion-server-next.yaml
- editors-definitions/che-code-insiders.yaml
- editors-definitions/che-code-latest.yaml
- editors-definitions/che-code-server-latest.yaml
- editors-definitions/che-code-server-next.yaml
- editors-definitions/che-idea-latest.yaml
- editors-definitions/che-idea-next.yaml
- editors-definitions/che-idea-server-latest.yaml
- editors-definitions/che-idea-server-next.yaml
- editors-definitions/che-pycharm-server-latest.yaml
- editors-definitions/che-pycharm-server-next.yaml
- editors-definitions/che-rubymine-server-latest.yaml
- editors-definitions/che-rubymine-server-next.yaml
- editors-definitions/che-webstorm-server-latest.yaml
- editors-definitions/che-webstorm-server-next.yaml
Updates the editor definitions schema to 2.3.0
No issue, the updating was discussed here https://github.com/eclipse-che/che-operator/pull/1958
> chore: update the schema version in the editors to 2.3.0

- helmcharts/stable/README.md
Update Eclipse Che helmcharts README:
- add descriptions
- add detailed steps to install cert-manager  and DWO
N/A
https://github.com/eclipse-che/che/issues/23388
```bash
spec: {}
EOF
```
```bash
```
```bash
```
> chore: Update Eclipse Che helmcharts README

- bundle/next/eclipse-che/manifests/che-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- deploy/deployment/kubernetes/combined.yaml
- deploy/deployment/kubernetes/objects/che-operator.Deployment.yaml
- deploy/deployment/openshift/combined.yaml
- deploy/deployment/openshift/objects/che-operator.Deployment.yaml
- helmcharts/next/templates/che-operator.Deployment.yaml
- pkg/deploy/dashboard/dashboard.go
- pkg/deploy/gateway/gateway.go
chore: Update traefik to 3.3.5 accordingly to https://doc.traefik.io/traefik/migration/v2-to-v3/
N/A
https://issues.redhat.com/browse/CRW-8628
```bash
spec: {}
EOF
```
```bash
```
```bash
```
> chore: Update traefik to 3.3.5

- pkg/deploy/server/server_deployment.go
Due to security reasons we can not mount self signed certificate to an environment variable. Mount the certificate to a file instead.
https://issues.redhat.com/browse/CRW-8654
```bash
spec: {}
EOF
```
```bash
```
```bash
```
3. Apply [self signed certificate](https://eclipse.dev/che/docs/stable/administration-guide/configuring-che-with-self-signed-certificate/).
4. Check the `che-server` pod has no `CHE_SELF__SIGNED__CERT` env variable, but the certificated is mounted to the …
> Mount self signed certificate to file instead of environment variable

- editors-definitions/che-clion-server-latest.yaml
- editors-definitions/che-clion-server-next.yaml
- editors-definitions/che-code-insiders.yaml
- editors-definitions/che-code-latest.yaml
- editors-definitions/che-code-server-latest.yaml
- editors-definitions/che-code-server-next.yaml
- editors-definitions/che-idea-latest.yaml
- editors-definitions/che-idea-next.yaml
- editors-definitions/che-idea-server-latest.yaml
- editors-definitions/che-idea-server-next.yaml
- editors-definitions/che-pycharm-server-latest.yaml
- editors-definitions/che-pycharm-server-next.yaml
- editors-definitions/che-rubymine-server-latest.yaml
- editors-definitions/che-rubymine-server-next.yaml
- editors-definitions/che-webstorm-server-latest.yaml
- editors-definitions/che-webstorm-server-next.yaml
This PR adds an array for supported architectures into editors-definitions.
https://github.com/eclipse-che/che/issues/23491
These changes are needed for https://github.com/eclipse-che/che-dashboard/pull/1360
The result will be shown on the dashboard after the update.
> feat: add the 'metadata.attributes.arch' array for supported architectures

- build/scripts/release/make-release.sh
fix: Force to build catalog for testing purpose
N/A
N/A
```bash
spec: {}
EOF
```
```bash
```
```bash
```
> fix: Force to build catalog for testing purpose

- olm-catalog/stable/eclipse-che.v7.107.0.bundle.yaml
Update charts (run make update-dev-resources) after latest changes.
```bash
spec: {}
EOF
```
```bash
```
```bash
```
> update 7.107.0 bundle resources
